### PR TITLE
Return actual value when throwing CheckAndSetException for DbKvs

### LINKED ISSUE #2195: CheckAndSetException not correctly populated correctly on Postgres
`LockStore.acquireBackupLock` is supposed to throw a CheckAndSetException with the actual encountered value populated, but on Postgres this field is not currently being populated. As well as making it impossible for users to tell from the error message what service holds the lock, it is also a source of P1/P0s for an internal product, which is attempting to _reacquire_ the backup lock if it is killed while it holds it. This is obviously only possible if the actualValues field is filled out.

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Fixes #2195

**Implementation Description (bullets)**: When catching CheckAndSetException in UpdateExecutor (used by DbKvs), we perform an additional DB check to fetch the current value.

**Concerns (what feedback would you like?)**: This check is not synchronised, so there's a race condition where we might fail to update, then some successful update happens before we check what the current value is. Do we care about this?

**Where should we start reviewing?**: Look at the test. It used to fail on Postgres. The change in UpdateExecutor makes it pass.

**Priority (whenever / two weeks / yesterday)**: We should merge this week. Ideally before next release as it's fairly small and would help an internal product ( @chrisalice for SA)

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2196)

### CODE REVIEW

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/UpdateExecutor.java [hunk 1]
```diff
@@ -55,8 +60,24 @@ public void update(Cell cell, long ts, byte[] oldValue, byte[] newValue) {
...
+                + " SELECT val FROM " + prefixedTableName
+                + " WHERE row_name = ?"
+                + " AND col_name = ?"
+                + " AND ts = ?";
+        Object[] args = new Object[] {
+                cell.getRowName(),
+                cell.getColumnName(),
+                ts
+        };
+        AgnosticLightResultSet results = conns.get().selectLightResultSetUnregisteredQuery(sqlString, args);
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/UpdateExecutor.java]: From @chrisalice : can (do?) you not just run the UPDATE and SELECT in a SQL transaction?

Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/UpdateExecutor.java]: You can't run "UPDATE, then SELECT if the UPDATE failed" in a single transaction, because when the update fails, the transaction will get rolled back. We don't want to do the SELECT first, because in most cases that would be a pointless DB round trip.

Comment (gbonik) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/UpdateExecutor.java]: I think selectLightResultSetUnregisteredQuery accept varargs, so you don't need to allocate an array explicitly
