### PR TITLE
Fix/timestamp table metadata

### LINKED ISSUE #636: _timestamp somehow created without corresponding table metadata for many many people
It's probably something weird with how early / basic in the atlas startup _timestamp needs to be made.

### PR DESCRIPTION
**Pull request by hsaraogi**
Fixes #636 

`getAllMetadataTables()` ignores all hidden tables, but the missing metadata error message was there for the `_timestamp` table. Now, we do not print such error messages for any hidden tables.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/716)

### CODE REVIEW

**Comment by gsheasby** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 161 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/716#-KNXXwO6yX3IT16RzX46:-KNXXwO6yX3IT16RzX47:-2042711597) ([raw file](https://github.com/palantir/atlasdb/blob/2dd853267e05cd032fedf0a534ac7ab9505f7903/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L161)):*
> ```Java
> 
>     public static CassandraKeyValueService create(CassandraKeyValueServiceConfigManager configManager, Optional<LeaderConfig> leaderConfig) {
>         return create(configManager,leaderConfig, LoggerFactory.getLogger(CassandraKeyValueService.class));
> ```

Missing space between the args. We should add this to checkstyle so we don't have to care about it during PRs.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 171 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/716#-KNXXbVqWwATnThCat2c:-KNXXbVqWwATnThCat2d:137363618) ([raw file](https://github.com/palantir/atlasdb/blob/2dd853267e05cd032fedf0a534ac7ab9505f7903/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L171)):*
> ```Java
>     }
> 
>     protected CassandraKeyValueService(Logger log, CassandraKeyValueServiceConfigManager configManager,
> ```

Args should be one-per line. We should add this to checkstyle so we don't have to care about it during PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/716)*

**Comment by gsheasby** [comment]
Looks fine apart from two very minor style issues.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/716#-:-KNXYFL8gJ0Sp5VIjxa2:411860313)*

**Comment by gsheasby** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/716)*

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 1]
```diff
@@ -224,7 +230,7 @@ private void upgradeFromOlderInternalSchema() {
                         log.warn("Upgrading table {} to new internal Cassandra schema", tableRef);
                         tablesToUpgrade.put(tableRef, clusterSideMetadata);
                     }
-                } else if (!(tableRef.equals(AtlasDbConstants.METADATA_TABLE) || tableRef.equals(schemaMutationLockTable.getOnlyTable()))) { // only expected cases
+                } else if (!hiddenTables.isHidden(tableRef)) {
```
Comment (jboreiko) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: Not quite related to this PR but demonstrates why this is a confusing problem.  There is a list of hidden tables inside AtlasDbConstants and the one held in HiddenTables (also it's not clear to me why HiddenTables is ever instantiated).  My recommendation would be that HiddenTables expose layers or we break it apart into the lists the correspond to the different levels of hidden, which as I currently understand it would be has follows: NO_METADATA_TABLES => (METADATA_TABLE, TIMESTAMP_TABLE), ATLASDB_HIDDEN_TABLES => (NO_METADATA_TABLES, PUNCH_TABLE, SCRUB_TABLE, TRANSACTION_TABLE), <KVS>_HIDDEN_TABLES => e.g. CASSANDRA_HIDDEN_TABLES => (ATLADB_HIDDEN_TABLES, LOCK_TABLE)

Comment (jboreiko) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: Just going to file this as a ticket.
