### PR TITLE
Fix/cassandra simple db lock

### LINKED ISSUE #431: Additional serialization required for table creation in C* versions 2.1+
## BLUF
In C* 2.1+ concurrent table creation can cause apparent data loss, but only much later after the first time a cluster is restarted and re-gossips new CfId around correctly. We need to add additional locking that was previously not necessary.

## Background
Previously, we were able to, with multiple atlas instances talking with multiple C* coordinators, create the same CF to back a createTable(s) call at the same time, and then wait for schema to fully gossip / settle at the end of this operation.

C* <2.1 CfId is a UUID based on KS and CF names.
C* 2.1+ fixes another bug we've run into in the past (that you can occasionally read data written before a drop table after creating a table at a later time with the same name; this is commonly found by things like repeated tests that use and teardown things like "test_table_1", etc) by generating CfId backed by wallclock time.

As a result, C* 2.1+ createTable cannot happen concurrently and does not natively handle the idempotency we require from our KVS.createTable(s) spec; it's possible to get into a state where two nodes both have knowledge of a table, but know it to have differing CfMetadata.cfId because of differing generation wallclock times on different coordinators. Disturbingly, this generates errors that get logged (to the tune of the ConfigurationException attached below), but does allow gossip to settle on a consistent schema version hash despite having different underlying CfId. (imho this is a bug with C*, but we can also solve this ourselves by enhancing our schemas-have-settled-check to look at all CfMetadata on each node as well as the thrift describe_schema_versions() call from each)

Even CQL verb "create table if not exists" ('if not exists' also being something added in 2.1.1+) does not handle concurrent table creation on different coordinators correctly and can get into the same situation that we saw.

In general fixing this class of issues is part of upstream Cassandra epic https://issues.apache.org/jira/browse/CASSANDRA-9424 .

> `
 1329 ERROR [MigrationStage:1] 2016-04-30 17:36:29,485 CassandraDaemon.java:183 - Exception in thread Thread[MigrationStage:1,5,main]
1330 org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 125bfc90-0efa-11e6-bb6f-fdf3c6b1908a; expected 1256f380-0efa-11e6-bb6f-fdf3c6b1908a)
1331 »»»»at org.apache.cassandra.config.CFMetaData.validateCompatility(CFMetaData.java:812) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1332 »»»»at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:740) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1333 »»»»at org.apache.cassandra.config.CFMetaData.reload(CFMetaData.java:726) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1334 »»»»at org.apache.cassandra.config.Schema.updateTable(Schema.java:489) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1335 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeTables(LegacySchemaTables.java:527) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1336 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeSchema(LegacySchemaTables.java:424) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1337 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeSchema(LegacySchemaTables.java:392) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1338 »»»»at org.apache.cassandra.db.DefinitionsUpdateVerbHandler$1.runMayThrow(DefinitionsUpdateVerbHandler.java:50) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1339 »»»»at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1340 »»»»at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
1341 »»»»at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
1342 »»»»at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
1343 »»»»at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
1344 »»»»at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
`
 
## Fix

There are numerous ways to fix this, they're all not great for many reasons.

- Some people serialize all DDL through a single static node (the other large now-London product that leverages C* opts to do this) but this is bad because it's relatively against the concepts of HA and having a live-updatable node list and having clients with slightly different views of the Cassandra cluster.

- We could make a table and use C* compare and swap (CAS) to provide a DB lock around table creation, but this unfortunately requires an already-done table creation

- We could use our own Lock service
-- But this is not good for our abstraction / code smell
-- And we currently package it as LockAndTimestampService which gives you a circular dependency because TimestampService has a KVS dependency so it can storeUpperLimit

### PR DESCRIPTION
**Pull request by jboreiko**
Fixes #431 

Is a derivative of #435 .  The difference being that this does not allow other nodes to override the currently held lock after a period of time.  This is an 'at most once' methodology for table creation.  All nodes will attempt to connect to Cassandra and grab a global lock.  If they are unable to acquire the lock after a given period of time they will throw a timeout exception indicating that they were unable to start up and that further action may be required (shutting down all connected atlas's and deleting the _locks table) if attempting to restart the node continues to fail.

### CODE REVIEW

File: atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTestSuite.java [hunk 1]
```diff
@@ -33,23 +32,20 @@
 
 @RunWith(Suite.class)
 @SuiteClasses({
```
Comment (clockfort) [inline atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTestSuite.java]: you probably did this just for testing your changes quickly (I do this too) and forgot to revert this section, I will add the other tests back in to the suite

Comment (joelea) [inline atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTestSuite.java]: Oh, whoops, I thought John put these back in.

Comment (joelea) [inline atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTestSuite.java]: fixed.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 2]
```diff
@@ -1427,9 +1430,124 @@ public Void apply(Client client) throws Exception {
...
+                            expected = ImmutableList.<Column>of();
+                        } else {
+                            Column existingValue = Iterables.getOnlyElement(casResult.getCurrent_values(), null);
+                            if (existingValue == null) {
+                                throw new IllegalStateException("Something is wrong with underlying locks. Consult support for guidance on manually examining and clearing locks from " + CassandraConstants.LOCK_TABLE + " table.");
+                            }
+                            expected = ImmutableList.of(lockColumnWithValue(Longs.toByteArray(CassandraConstants.GLOBAL_DDL_LOCK_CLEARED_VALUE)));
+                        }
+
+                        if (timeSlept > configManager.getConfig().schemaMutationTimeoutMillis() * 4) { // possibly dead remote locker
```
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: (background for other people reading, I originally had automated logic here to after a few minutes of looking at the same lock resume everything assuming the existing lock was dead)
I understand but personally dislike this balance of safety vs. likelihood of support burden / manual fixup, because I think this case is going to happen often (cassandra table creation / schema gossip waiting is a slow and occasionally error prone process)

Maybe as an in-between, this error could at least include what we would always have people do, which is shut down all atlases and cqlsh truncate _locks

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 3]
```diff
@@ -1427,9 +1430,124 @@ public Void apply(Client client) throws Exception {
...
+                            throw new TimeoutException(String.format("We have timed out waiting on the current schema mutation lock holder.  " +
+                                    "We have tried to grab the lock for %d milliseconds unsuccessfully.  Please try restarting the AtlasDB client." +
+                                    "If this occurs repeatedly it may indicate that the current lock holder has died without releasing the lock." +
+                                    "This will require manual intervention to repair, please contact support.", timeSlept));
+                        }
+
+
+                        long timeToSleep = CassandraConstants.TIME_BETWEEN_LOCK_ATTEMPT_ROUNDS_MILLIS * (long) Math.pow(2, timesAttempted++);
+                        Thread.sleep(timeToSleep);
+                        timeSlept += timeToSleep;
```
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: might as well make this an actual timer, as some of the operations here actually can take a significant amount of time (default CAS contention timeout is 5 seconds)

**Comment by clockfort** [comment]
other than the 3 comments, lgtm.

@jboreiko correct, not used re-entrantly and not anticipated to ever need to be.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 4]
```diff
@@ -1476,17 +1478,17 @@ public Void apply(Client client) throws Exception {
                             expected = ImmutableList.of(lockColumnWithValue(Longs.toByteArray(CassandraConstants.GLOBAL_DDL_LOCK_CLEARED_VALUE)));
                         }
 
-                        if (timeSlept > configManager.getConfig().schemaMutationTimeoutMillis() * 4) { // possibly dead remote locker
+                        if (stopwatch.elapsed(TimeUnit.MILLISECONDS) > configManager.getConfig().schemaMutationTimeoutMillis() * 4) { // possibly dead remote locker
                             throw new TimeoutException(String.format("We have timed out waiting on the current schema mutation lock holder.  " +
                                     "We have tried to grab the lock for %d milliseconds unsuccessfully.  Please try restarting the AtlasDB client." +
                                     "If this occurs repeatedly it may indicate that the current lock holder has died without releasing the lock." +
-                                    "This will require manual intervention to repair, please contact support.", timeSlept));
+                                    "This will require manual intervention to repair, please contact support.", TimeUnit.MILLISECONDS));
```
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: bug

**Comment by tpetracca** [comment]
So what are the failure scenarios here?  Is there a world in which we enter a bad state where we need to manually truncate the _locks table (in which case we should wrap it in an atlas-cli command).  Would be good to have an explicit definition and docs.

**Comment by joelea** [comment]
Yes, that's pretty much exactly the potential case. This would require an atlas node dying inbetween taking the lock and releasing the lock. The only thing that happens in that gap is schema changes.

I think it would be a very good idea to add docs and CLIs but want to get something out ASAP so product teams can get busy with their releases, which needs to happen before it hits the field. I can hold off for another release if you think this stuff needs to happen before we have people using it.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 5]
```diff
@@ -505,10 +512,11 @@ public Void apply(Cassandra.Client client) throws Exception {
         }
     };
 
-    final FunctionCheckedException<Cassandra.Client, Void, Exception> createInternalMetadataTable = new FunctionCheckedException<Cassandra.Client, Void, Exception>() {
+    final FunctionCheckedException<Cassandra.Client, Void, Exception> createInternalTables = new FunctionCheckedException<Cassandra.Client, Void, Exception>() {
         @Override
         public Void apply(Cassandra.Client client) throws Exception {
             createTableInternal(client, CassandraConstants.METADATA_TABLE);
```
Comment (tpetracca) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: Are we not worried about the metadata table either?

Comment (jboreiko) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: To close out, this concern is resolved in #447
