### PR TITLE
Fix/shrink oracle se

### LINKED ISSUE #2262: Oracle compact internally might be able to SHRINK SPACE on Non-EE
We might be able to use `SHRINK SPACE` to avoid the table bloat on Non-EE instead of logging a message which noone notices. This has caused disks to fill up at a deployment bringing the world to a stop as the DB could not be written to(PDS-55840). The solution was to add disks and run `SHRINK SPACE`. 

@clockfort for SA.

The code in question:
```
    @Override
    public void compactInternally() {
        if (config.enableOracleEnterpriseFeatures()) {
            try {
                conns.get().executeUnregisteredQuery(
                        "ALTER TABLE " + oracleTableNameGetter.getInternalShortTableName(conns, tableRef)
                                + " MOVE ONLINE");
            } catch (PalantirSqlException e) {
                log.error("Tried to clean up {} bloat after a sweep operation,"
                        + " but underlying Oracle database or configuration does not support this"
                        + " (Enterprise Edition that requires this user to be able to perform DDL operations)"
                        + " feature online. Since this can't be automated in your configuration,"
                        + " good practice would be do to occasional offline manual maintenance of rebuilding"
                        + " IOT tables to compensate for bloat. You can contact Palantir Support if you'd"
                        + " like more information. Underlying error was: {}", tableRef, e.getMessage());
            } catch (TableMappingNotFoundException e) {
                throw Throwables.propagate(e);
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by hsaraogi**
**Goals (and why)**: Fix #2262.

**Implementation Description (bullets)**: If enterprise features are not enabled, use shrink space commands. Tested using the KVS and Sweeper tests on the internal oracle repo.

**Concerns (what feedback would you like?)**:
1. Should be warn users of the possible table lock when running `ALTER TABLE .. SHRINK SPACE` though we expect it to be short.
2. Should this be wrapped in a config flag - I think yes and it should be live reloadable?
3. When running shrink we should 
> disable any triggers based on rowid for table segments you want to shrink

This is beacuse rowids will be altered. Do we have any such triggers? - I think there are no such Atlas level triggers.

**Where should we start reviewing?**: OracleDdlTable

**Priority (whenever / two weeks / yesterday)**: one day.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2286)

### CODE REVIEW

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 1]
```diff
@@ -243,26 +243,38 @@ public void compactInternally() {
...
                 throw new RuntimeException(e);
             }
-        } else {
-            log.warn(compactionFailureTemplate,
-                    tableRef,
-                    "(If you are running against Enterprise Edition,"
-                    + " you can set enableOracleEnterpriseFeatures to true in the configuration.)");
+        } else if (config.enableShrinkOnOracleStandardEdition()) {
+            try {
+                conns.get().executeUnregisteredQuery(
```
Comment (dyonbalding) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: For Sigfred purposes, could we please get some logging before and after these two queries. That will give us an idea of how long they are taking, and also that they are running.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java [hunk 2]
```diff
@@ -60,6 +60,11 @@ public boolean enableOracleEnterpriseFeatures() {
     }
 
     @Value.Default
+    public boolean enableShrinkOnOracleStandardEdition() {
```
Comment (dyonbalding) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java]: Does this mean we can turn this off and on with preferences?

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java (hunk 1 above)
Comment (hsaraogi) [reply atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: Sure.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 3]
```diff
@@ -243,26 +246,50 @@ public void compactInternally() {
...
+            try {
+                Stopwatch shrinkAndCompactTimer = Stopwatch.createStarted();
+                conns.get().executeUnregisteredQuery(
+                        "ALTER TABLE " + oracleTableNameGetter.getInternalShortTableName(conns, tableRef)
+                                + " SHRINK SPACE COMPACT");
+                log.info("Call to SHRINK SPACE COMPACT on table {} took {} ms.",
+                        tableRef, shrinkAndCompactTimer.elapsed(TimeUnit.MILLISECONDS));
+
+                Stopwatch shrinkTimer = Stopwatch.createStarted();
+                conns.get().executeUnregisteredQuery(
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: We should catch issues with `SHRINK SPACE` and `SHRINK SPACE COMPACT` separately. If `COMPACT` completes but the full shrink fails, then the impl could try to complete the shrink during off-peak hours ([link](https://docs.oracle.com/cd/B28359_01/server.111/b28310/schema003.htm#CBBBIADA)).

Otherwise, what benefit do we get by using `COMPACT` and then immediately trying to finish the shrink?

Comment (hsaraogi) [reply atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: How will the IMPL know which tables to shrink? The log lines are sufficient to tell which operation failed. 

The benefit is that locks on the entire table are held for a much shorter duration.

Comment (gsheasby) [reply atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: If the `PalantirSqlException` contain the command that failed, then that's OK.
Can we assume that deployments will have `info` logging enabled?

Comment (hsaraogi) [reply atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: yes, `PalantirSqlException` will contain the command that failed.

**Comment by gsheasby** [comment]
"Should be warn users of the possible table lock when running ALTER TABLE .. SHRINK SPACE though we expect it to be short."

Let's validate this. @dyonbalding, when you test this out, would you be able to let us know how long the tables were locked for? Thanks!

**Comment by hsaraogi** [comment]
Discussed with @dyonbalding offline, we will ensure that these info logs are enabled and monitor the time taken in these operations.
