### PR TITLE
Exclude swept time from SweepResults.equals

### LINKED ISSUE #3059: AbstractSweepTaskRunnerTest is flaky
This seems to be failing
```
private void assertEmptyResultWithNoMoreToSweep(SweepResults results) {
        assertTimeSweepStartedWithinDeltaOfSystemTime(results);
        assertThat(results.getTimeInMillis()).isLessThanOrEqualTo(1000L);
        assertThat(results.getTimeInMillis()).isGreaterThanOrEqualTo(0L);
        assertEquals(results, SweepResults.builder()
                .from(SweepResults.createEmptySweepResultWithNoMoreToSweep())
                .timeSweepStarted(results.getTimeSweepStarted())
                .timeInMillis(results.getTimeInMillis())
                .build());
    }
```

Build 9817
```
[00:04:20] com.palantir.atlasdb.keyvalue.dbkvs.DbkvsPostgresTestSuite > com.palantir.atlasdb.keyvalue.dbkvs.DbkvsPostgresSweepTaskRunnerTest.testSweepStrategyNothing FAILED
[00:04:20]     java.lang.AssertionError: expected:<SweepResults{previousStartRow=Optional.empty, nextStartRow=Optional.empty, cellTsPairsExamined=0, staleValuesDeleted=0, minSweptTimestamp=9223372036854775807, timeInMillis=0, timeSweepStarted=1521052988386}> but was:<SweepResults{previousStartRow=Optional.empty, nextStartRow=Optional.empty, cellTsPairsExamined=0, staleValuesDeleted=0, minSweptTimestamp=9223372036854775807, timeInMillis=0, timeSweepStarted=1521052988385}>
```

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Fixes #3059 

A few tests break because we create a couple of empty results, which
have System.currentTimeMillis as the started time, and then expect them
to equals() each other. Adding Value.Auxiliary excludes this field from
equals().

As a side-effect, the field is also excluded from toString(), but since
this class isn't serialised, we don't mind.

[no release notes]

**Concerns (what feedback would you like?)**: Should we stop using currentTimeMillis in createEmptySweepResults instead?

**Priority (whenever / two weeks / yesterday)**: ASAP, causing tests to flake including external project tests

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3062)

### CODE REVIEW

File: atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java [hunk 1]
```diff
@@ -21,6 +21,7 @@
 
 import com.palantir.atlasdb.encoding.PtBytes;
 
+// Note that this class has an Auxiliary field, and therefore serialization might not work as expected
```
Comment (jeremyk-91) [inline atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java]: I think it's fine. We don't specify the JSON serialize/deserialize annotations - and I did a quick test, and if we did the `timeSweepStarted` is still serialized.

Nice! I would have guessed such a feature must exist somewhere, but have never used it

File: atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java [hunk 2]
```diff
@@ -243,6 +244,7 @@ public void testSweeperFailsHalfwayThroughOnDeleteTable() {
                         .maxCellTsPairsToExamine(DEFAULT_BATCH_SIZE)
                         .build(),
                 nextStartRow);
+        Thread.sleep(1);
```
Comment (jeremyk-91) [inline atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java]: Not sure I understand why we need the `Thread.sleep(1)` here - I get that it would be a failing test for the original impl with a non-Auxiliary start time for sweep, though I think we have the test in `SweepResultsTest` that already does that.

File: atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java [hunk 3]
```diff
@@ -57,6 +58,7 @@
     /**
      * Time in milliseconds when we started sweeping this table.
      */
+    @Value.Auxiliary
```
Comment (gmaretic) [inline atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java]: Awesome find :)

File: atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java (hunk 1 above)
Comment (gsheasby) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/SweepResults.java]: Oh cool. @gmaretic and I weren't sure if excluding the field from `toString()` would mess with `JsonSerialize` - thanks for doing the legwork here. I'll remove the comment, as it isn't needed.

File: atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java (hunk 2 above)
Comment (gsheasby) [reply atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java]: Yep, that's why I put it there - I can revert that bit.

Comment (gmaretic) [reply atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java]: Looks to me like it was left from debugging. I'd remove it
