### PR TITLE
Fix migration cli not updating the timestamp on ToKVS

### LINKED ISSUE #1192: KVS Migration Breaks TimestampService Contract
The timestamp service contract / api states:
```
    /**
     * This will get a fresh timestamp that is guaranteed to be newer than any other timestamp
     * handed out before this method was called.
     */
```

The act of doing a KVS migration with an embedded timestamp service whose timestamp data is co-located in the same KVS and keyspace/database/etc as the Atlas data causes the timestamps to reset back to the logical beginning of time (timestamp 1). This breaks the contract and anyone who might be relying on that contract being true (though it's generally rare to see an embedded TimestampService being used by a client other than Atlas).

I propose we change the logic to the following: At the beginning of the KVS migration, fetch a fresh timestamp from the old timestamp/service and use that timestamp to fast-forward the new TimestampService. Then continue on as usual.

### PR DESCRIPTION
**Pull request by jboreiko**
This solution involves exposing fastForwardTimestamp on the timestampService interface

The KVS migration needs more testing, but wanted to get validation that this idea is reasonable.

Resolves #1192

Todos:
- [ ] release notes
- [ ] increase unit testing of kvs migration cli
- [ ] submit follow up PR with some refactoring of migration code

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1199)

### CODE REVIEW

**Comment by jeremyk-91** [comment]
We had some discussion today about whether it made sense for the `fastForwardTimestamp()` to be exposed separately (perhaps through an administrative interface / admin connector), as that method is not considered likely to be used by applications.

File: timestamp-api/src/main/java/com/palantir/timestamp/TimestampService.java [hunk 1]
```diff
@@ -40,4 +40,20 @@
     @Path("fresh-timestamps")
     @Produces(MediaType.APPLICATION_JSON)
     TimestampRange getFreshTimestamps(@QueryParam("number") int numTimestampsRequested);
+
+    /**
+     * Fast forwards the timestamp to the specified one so that no one can be served fresh timestamps prior
+     * to it from now on.
+     *
+     * Sets the upper limit in the TimestampBoundStore as well as increases the minimum timestamp that can
+     * be allocated from this instantiation of the TimestampService moving forward.
```
Comment (jeremyk-91) [inline timestamp-api/src/main/java/com/palantir/timestamp/TimestampService.java]: Just a note: these 2 lines were specific to the impl for persistent and should be removed?

**Comment by jeremyk-91** [comment]
We had some discussion today about whether it made sense for the `fastForwardTimestamp()` to be exposed separately (perhaps through an administrative interface / admin connector), as that method is not considered likely to be used by applications.

**Comment by SerialVelocity** [comment]
Yes, to add something onto what @jeremyk-91 said:
We should probably get this fix in without adding `fastFowardTimestamp` to this interface and then have a chat about how we would like to go forward. If it turns out that we *do* want to add it to this interface, we can then submit a refactor PR.

**Comment by tpetracca** [comment]
Out of curiosity, what's the concern around adding that endpoint? When we switch to external timelock, we won't have a choice but to add it.

**Comment by rhero** [comment]
We should use the fastforwarding work that recently merged for the Timelock service. Moving to To Do so we will actually take a look.

**Comment by jeremyk-91** [comment]
I'm taking ownership of this one going forward, and going to rebase onto develop since this is super old.

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java [hunk 2]
```diff
@@ -173,19 +174,27 @@ public AtlasDbServices connectToServices() throws IOException {
...
-                .getTimestampService()
-                .getFreshTimestamp());
-        toServices.getTransactionService().putUnlessExists(migrationTimestampSupplier.get(), toServices
-                .getTimestampService()
-                .getFreshTimestamp());
+        long migrationStartTimestamp = fromServices.getTimestampService().getFreshTimestamp();
+        long migrationCommitTimestamp = fromServices.getTimestampService().getFreshTimestamp();
+
+        TimestampService toTimestampService = toServices.getTimestampService();
+        if (!(toTimestampService instanceof PersistentTimestampService)) {
```
Comment (jeremyk-91) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java]: `ManagedTimestampService` is specific to TimeLock though. Since we don't use fresh timestamps, `TimestampManagementService` should suffice (this is how we do it in automigrations as well). I've changed to that.

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java [hunk 3]
```diff
@@ -173,19 +174,27 @@ public AtlasDbServices connectToServices() throws IOException {
...
+            printer.error("Timestamp service must be of type {}, but yours is {}.  Exiting.",
+                    PersistentTimestampService.class.toString(), toTimestampService.getClass().toString());
+            throw new IllegalArgumentException("Timestamp service was the wrong type");
+        }
+        PersistentTimestampService toPersistentTimestampService = (PersistentTimestampService) toTimestampService;
```
Comment (jeremyk-91) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java]: (yes. As above changed to just `TimestampManagementService`)

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java [hunk 4]
```diff
@@ -173,19 +174,27 @@ public AtlasDbServices connectToServices() throws IOException {
...
-                .getTimestampService()
-                .getFreshTimestamp());
+        long migrationStartTimestamp = fromServices.getTimestampService().getFreshTimestamp();
+        long migrationCommitTimestamp = fromServices.getTimestampService().getFreshTimestamp();
+
+        TimestampService toTimestampService = toServices.getTimestampService();
+        if (!(toTimestampService instanceof PersistentTimestampService)) {
+            printer.error("Timestamp service must be of type {}, but yours is {}.  Exiting.",
+                    PersistentTimestampService.class.toString(), toTimestampService.getClass().toString());
+            throw new IllegalArgumentException("Timestamp service was the wrong type");
```
Comment (jeremyk-91) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java]: Agreed, will fix this.

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java [hunk 5]
```diff
@@ -171,22 +173,25 @@ public AtlasDbServices connectToServices() throws IOException {
         return DaggerAtlasDbServices.builder().servicesConfigModule(scm).build();
     }
 
-    private KeyValueServiceMigrator getMigrator(AtlasDbServices fromServices, AtlasDbServices toServices)
+    @VisibleForTesting
```
Comment (gsheasby) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java]: This method could probably be moved to a factory class, and tested there, so we wouldn't need `@VisibleForTesting`.

File: atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+    @Test
+    public void testFastForwardTimestamp() throws Exception {
+        InMemoryTestRunner runner = makeRunner("timestamp", "-t", Long.toString(TEST_TIMESTAMP), FAST_FORWARD_COMMAND);
+        AtlasDbServices atlasDbServices = runner.connect(moduleFactory);
+
+        long currentTimestamp = atlasDbServices.getTimestampService().getFreshTimestamp();
+        assertThat(currentTimestamp).isLessThan(TEST_TIMESTAMP);
+
+        String response = runner.run();
+        assertThat(response).contains("Timestamp successfully fast-forwarded to 400");
```
Comment (gsheasby) [inline atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java]: nit: could use `TEST_TIMESTAMP` instead of hard-coded `"400"` here.

File: atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+import io.airlift.airline.Command;
+
+public class TestFastForwardTimestampCommand {
+    private static final String FAST_FORWARD_COMMAND = FastForwardTimestamp.class.getAnnotation(Command.class).name();
+    private static final Long TEST_TIMESTAMP = 400L;
+
+    private static AtlasDbServicesFactory moduleFactory = createModuleFactory();
+
+    @Test
+    public void testFastForwardTimestamp() throws Exception {
```
Comment (gsheasby) [inline atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java]: How about tests for attempting to fast-forward to a value less than `currentTimestamp`, or a negative value?

File: atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java (hunk 6 above)
Comment (jeremyk-91) [inline atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java]: Yep, changed a fair bit in new impl (which parameterises the expected target)

File: atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java (hunk 7 above)
Comment (jeremyk-91) [inline atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java]: Yep, this class has been changed to first grab a timestamp N, and then test FFs:

* N+777 should bring the bound to N+777
* N-777 should leave the bound as is
* Long.MIN_VALUE should leave the bound as is

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java (hunk 5 above)
Comment (jeremyk-91) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java]: Sure, extracted `KeyValueServiceMigrators`.

**Comment by jeremyk-91** [comment]
In addition to Glenn's comments I added some more tests on the migrator, including verifying it does a put-unless-exists into the transaction table + sanity checks on that, and also upfront checks that throw if the number of threads or batch size is negative (these would have failed in the past but you would have gotten weird error messages, either from Executors or BatchingVisitables).

**Comment by jeremyk-91** [comment]
Glenn has reviewed this, Himangi's out this week (I think I've addressed everything there) and I've added Ben's desired test (``KeyValueServiceMigratorsTest#setupMigratorFastForwardsTimestamp``), so going ahead here.
