### PR TITLE
Do not log the stacktrace on failure to gain leadership.

### LINKED ISSUE #550: Misconfigured Paxos errors confusing
Seen on internal ticket PDS-43887

WARN [2016-06-09 01:01:17,107] leadership: Leadership was not gained
! com.palantir.paxos.PaxosRoundFailureException: failed to acquire quorum in paxos phase one
! at com.palantir.paxos.PaxosProposerImpl.phaseOne(PaxosProposerImpl.java:158) ~[leader-election-impl-0.6.0.jar:na]
! at com.palantir.paxos.PaxosProposerImpl.propose(PaxosProposerImpl.java:89) ~[leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.PaxosLeaderElectionService.proposeLeadership(PaxosLeaderElectionService.java:343) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.PaxosLeaderElectionService.blockOnBecomingLeader(PaxosLeaderElectionService.java:140) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy.gainLeadership(AwaitingLeadershipProxy.java:106) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy.access$000(AwaitingLeadershipProxy.java:45) [leader-election-impl-0.6.0.jar:na]
! at com.palantir.leader.proxy.AwaitingLeadershipProxy$1.run(AwaitingLeadershipProxy.java:94) [leader-election-impl-0.6.0.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
! at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55) [commons-executors-0.6.0.jar:na]
! at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486) [commons-executors-0.6.0.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
WARN [2016-06-09 01:01:17,108] com.palantir.leader.PaxosLeaderElectionService: unable to get uuid from server

The result of the support ticket was a misconfigured leader block that lead to none of the hosts able to reach the others.  Would be valuable if the error here was clearer to reduce debugging time for engineers in the field.

### PR DESCRIPTION
**Pull request by gbrova**
Fixes #550 

The stacktrace for a PaxosRoundFailureException is not useful because it just indicates that
a Paxos round did not reach quorum without showing the underlying reason.

By removing the stack trace here, we get a cleaner log message: 

```
ete1_1 | WARN  [2016-06-28 14:55:35,270] com.palantir.paxos.PaxosQuorumChecker: We encountered an error while trying to request an acknowledgement from another paxos node. This could mean the node is down, or we cannot connect to it for some other reason.
ete1_1 | ! java.net.UnknownHostException: hostThatDoesNotExist
...
```

Will leave this at the warn level, because it's a relatively rare event that _does_ indicate some network weirdness.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/630)

### CODE REVIEW

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java [hunk 1]
```diff
@@ -345,7 +345,7 @@ private void proposeLeadership(LeadershipToken token) {
             proposer.propose(seq, null);
         } catch (PaxosRoundFailureException e) {
             // We have failed trying to become the leader.
-            leaderLog.warn("Leadership was not gained", e);
+            leaderLog.warn("Leadership was not gained");
```
Comment (schlosna) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: would still be useful to include the exception message as to which phase failed

Comment (gbrova) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: Happy to include it. 

However, I'm not convinced that information adds much signal.  As I understand the implementation, a `PaxosRoundFailureException` can be thrown if: 

 - in Phase 1, if too many nodes either: 
    - had their logs truncated, or
    - timed out
 - in Phase 2, if too many nodes either: 
    - responded to another prepare request with a higher pid, or
    - timed out 

In all of these cases, the sensible thing is to retry the leadership election. And regardless of which phase fails, it's not clear whether the failure was due to timeouts or some other reason. 

We plan to revisit use of this exception as part of a broader refactor in #444, and should get more explicit errors then.

Comment (gbrova) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: Sorry, was thinking out loud and got carried away. To summarize, (1) I'm aware that even if we include information about which round failed, the root cause is still difficult to understand so the logging in this PR is still not perfect, but (2) we are trying to address this as part of a separate refactor, and (3) in the meantime, I will still log which phase failed in the spirit of not throwing away data.

Comment (gbrova) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: Actually, can probably add more clarity here without significantly changing things. Will update again tomorrow.

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java [hunk 2]
```diff
@@ -345,7 +345,10 @@ private void proposeLeadership(LeadershipToken token) {
             proposer.propose(seq, null);
         } catch (PaxosRoundFailureException e) {
             // We have failed trying to become the leader.
-            leaderLog.warn("Leadership was not gained", e);
+            leaderLog.warn("Leadership was not gained because: " + e.getMessage() + ". "
```
Comment (joelea) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: I wouldn't put the exception in the middle, you probably want the full exception being passed as the exception argument at the end, then you'll get the full stacktrace.

Comment (schlosna) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: Isn't the goal of this change to avoid log spam and not log the full stacktrace when leadership is not gained? If so, the current version of this change seems fine to me.

Comment (joelea) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: I'd be fearful of doing that at the expense of people having the logs they need. I think a thing we talked about was having more information available at the debug level.

File: docs/source/release_notes/release-notes.rst [hunk 3]
```diff
@@ -36,6 +36,9 @@ v0.6.1
     *    - |improved|
          - Reduced memory footprint of Cassandra KVS, esp. for workflows of many consecutive large reads (#568)
 
+    *    - |improved|
+         - The warning emitted when an attempted leadership election fails is now more descriptive. (#630)
```
Comment (joelea) [inline docs/source/release_notes/release-notes.rst]: Can you add a proper link (see current release notes for info)

**Comment by gbrova** [comment]
Removing do-not-merge.  I'm fine for this to go in as-is, though we hope to eventually make this log message even more explicit as part of #444.

**Comment by jboreiko** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java, line 348 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-o_-r2-348:-KLvZRbFFiHqhJ7zPdxp:-1429532433) ([raw file](https://github.com/palantir/atlasdb/blob/cb00c381f3cc0571f0fc5972cbe840f54c41b0bd/leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java#L348)):*
<details><summary><i>Previously, joelea wrote…</i></summary>
> I'd be fearful of doing that at the expense of people having the logs they need. I think a thing we talked about was having more information available at the debug level.
</details>
I'm wondering if stating that this should happen rarely is correct.  From what I recall this will happen quite a bit at a cluster start up since there is always going to be a node the beats the other ones up and starts spewing these (this being the very reason I filed the ticket to remove the troublesome stack traces in the first place).  Might be better to indicate this in the message, otherwise people may still be concerned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by jboreiko** [comment]
:lgtm: once we have a resolution to the comments below

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630#-:-KLviXAJk4dwm3iQhvBI:-1210972710)*

**Comment by gbrova** [comment]
*[leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java, line 348 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-o_-r2-348:-KLwoLzKAo9omoft-A89:1461267166) ([raw file](https://github.com/palantir/atlasdb/blob/cb00c381f3cc0571f0fc5972cbe840f54c41b0bd/leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java#L348)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> I'm wondering if stating that this should happen rarely is correct.  From what I recall this will happen quite a bit at a cluster start up since there is always going to be a node the beats the other ones up and starts spewing these (this being the very reason I filed the ticket to remove the troublesome stack traces in the first place).  Might be better to indicate this in the message, otherwise people may still be concerned.
</details>
The first suggestion in the message is to verify the other nodes are reachable -- clearly they won't be during startup. So this is correct if we agree that more than half the nodes being down is rare :-)

I can imagine it being confusing though, so I'm happy to just remove "this should happen rarely" (it's not really useful information either way).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by jboreiko** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by gbrova** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/source/release_notes/release-notes.rst, line 40 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-oa-r2-40:-KM-cZu9hKIg4MbbRHF5:-499146009) ([raw file](https://github.com/palantir/atlasdb/blob/cb00c381f3cc0571f0fc5972cbe840f54c41b0bd/docs/source/release_notes/release-notes.rst#L40)):*
<details><summary><i>Previously, joelea wrote…</i></summary>
> Can you add a proper link (see current release notes for info)
</details>
Done.

---

*[leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java, line 348 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-o_-r1-348:-KM-cqigof2IRIjVdFWu:-499146009) ([raw file](https://github.com/palantir/atlasdb/blob/3d666582f0c61f108b29057f749cea46ca983cc9/leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java#L348)):*
<details><summary><i>Previously, gbrova (George Brova) wrote…</i></summary>
> Actually, can probably add more clarity here without significantly changing things. Will update again tomorrow.  
</details>
Done.

---

*[leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java, line 348 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-o_-r2-348:-KM-cyyavfh17kNlSVfN:-499146009) ([raw file](https://github.com/palantir/atlasdb/blob/cb00c381f3cc0571f0fc5972cbe840f54c41b0bd/leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java#L348)):*
<details><summary><i>Previously, gbrova (George Brova) wrote…</i></summary>
> The first suggestion in the message is to verify the other nodes are reachable -- clearly they won't be during startup. So this is correct if we agree that more than half the nodes being down is rare :-)
> 
> I can imagine it being confusing though, so I'm happy to just remove "this should happen rarely" (it's not really useful information either way).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by joelea** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by joelea** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630#-:-KM07Y-W_dvCYacdovkU:1417088721)*

**Comment by jboreiko** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java, line 348 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/630#-KLcA-mKCJcABNvLH-o_-r1-348:-KM0Q8oeJneJlfj3xKxC:5173665) ([raw file](https://github.com/palantir/atlasdb/blob/3d666582f0c61f108b29057f749cea46ca983cc9/leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java#L348)):*
<details><summary><i>Previously, gbrova (George Brova) wrote…</i></summary>
> Done.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/630)*

**Comment by clockfort** [comment]
It might be nice in future to make things like these log only at info, but when turned to debug or trace to pop up stack traces of how we got here, because I imagine some of this stuff is a nightmare to debug otherwise in prod. Logic could probably be a logging utility function?

**Comment by gsheasby** [comment]
Isn't that pretty much what we're doing here?

**Comment by jboreiko** [comment]
I think @clockfort is just saying that we should generalize this pattern and make it into a logging utility function since there seem to be quite a few places where we want to have a simple compact log that an event occurred and then when switching to debug want a stack spit out as well.  I would agree.
