### PR TITLE
Fix/clean cass locks state 2

### LINKED ISSUE #2852: clean-cass-locks-state throws "Multiple schema mutation lock tables have been created"
On running:
PCLOUD [palantir@xxxx service]$ ./bin/atlasdb-cli --offline -c var/conf/install.yml clean-cass-locks-state

We got:

```
19:36:14.149 [main calling cassandra host keppel-soa-cassandra-16.ops.palantir.local/10.3.41.149:9160 started at 2018-01-11T19:36:14.147Z - 5] DEBUG c.p.a.k.c.CassandraClientPoolingContainer - During com.palantir.atlasdb.keyvalue.cassandra.qos.QosCassandraClient@640f11a1 check-in, cleaned up a read buffer of 1277 bytes of host keppel-soa-cassandra-16.ops.palantir.local
19:36:14.153 [main] ERROR com.palantir.atlasdb.cli.AtlasCli - Fatal exception thrown during cli command execution.  Exiting.
java.lang.IllegalStateException: Multiple schema mutation lock tables have been created.
This happens when multiple nodes have themselves as lockLeader in the configuration.
Please ensure the lockLeader is the same for each node, stop all Atlas clients using this keyspace, restart your cassandra cluster and run the clean-cass-locks-state cli command.
The tables that clashed were: [_locks_5fe819e3_7ff0_4884_b3a7_b7f96091bc58, _locks_c146b83a_27ae_40b4_9498_2fe69959dbb8]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.getSingleTable(UniqueSchemaMutationLockTable.java:87) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.ensureLockTableExists(UniqueSchemaMutationLockTable.java:80) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.UniqueSchemaMutationLockTable.getOnlyTable(UniqueSchemaMutationLockTable.java:48) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.tryInitialize(CassandraKeyValueServiceImpl.java:320) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.access$000(CassandraKeyValueServiceImpl.java:155) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl$InitializingWrapper.tryInitialize(CassandraKeyValueServiceImpl.java:166) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.async.initializer.AsyncInitializer.tryInitializeInternal(AsyncInitializer.java:141) ~[atlasdb-commons-0.72.0.jar:0.72.0]
        at com.palantir.async.initializer.AsyncInitializer.initialize(AsyncInitializer.java:64) ~[atlasdb-commons-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:266) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:235) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueServiceImpl.create(CassandraKeyValueServiceImpl.java:227) ~[atlasdb-cassandra-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.command.CleanCassLocksStateCommand.call(CleanCassLocksStateCommand.java:43) ~[atlasdb-cli-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.command.CleanCassLocksStateCommand.call(CleanCassLocksStateCommand.java:32) ~[atlasdb-cli-0.72.0.jar:0.72.0]
        at com.palantir.atlasdb.cli.AtlasCli.main(AtlasCli.java:65) ~[atlasdb-cli-0.72.0.jar:0.72.0]```

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Allow the clean-cass-locks-state CLI to run. Fixes #2852.

**Implementation Description (bullets)**:
- Move lock-cleaning code to `CassandraSchemaLockCleaner`
- Have `CleanCassLocksStateCommand` use `CassandraSchemaLockCleaner`
- Have tests use this method too
- Remove `CassandraKeyValueService.cleanUpSchemaMutationLockTablesState`

**Concerns (what feedback would you like?)**:
- The integration test for the command is kind-of shoehorned on to existing C* integration tests (right next to code that tests the method that the CLI calls).
- A bunch of stuff was made public. Is this necessary/wise?

**Where should we start reviewing?**: CassandraSchemaLockCleaner.java

**Priority (whenever / two weeks / yesterday)**: this week
 
Note: I ported the integration test over to develop, and proved that it fails with the message reported in #2852 - see [this branch](https://github.com/palantir/atlasdb/commits/temp/failing-integ-test) and its build.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2948)

### CODE REVIEW

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java [hunk 1]
```diff
@@ -2106,28 +2105,6 @@ public boolean performanceIsSensitiveToTombstones() {
         return true;
     }
 
-    /**
-     * Does not require all Cassandra nodes to be up and available, works as long as quorum is achieved.
```
Comment (fsamuel-bs) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java]: I think this comment is misleading. We still require all nodes to be up when dropping a table — we wait for schema agreement from all the Cassandra nodes. Let's add another comment, saying if there's one table, quorum is fine, but if there're 2 or more tables, we require all tables to be up.

Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java]: This comment was removed, so there's nothing to do here.
