### PR TITLE
Long instead of int

### LINKED ISSUE #2226: Oracle cannot store more than INT_MAX large values
Once the AtlasDB Overflow sequence goes beyond INT_MAX, applications will start receiving `Numeric Overflow` errors. This is a bug due to typecasting a long to an integer and back to a long. Fixed by #2224. 

Stacktrace reported:
```
2017-07-31 12:57:49,573 INFO [OperationalTransform-3] com.palantir.common.base.Throwables user: user_id: - Rewraping throwable com.palantir.exception.PalnatirSqlException: While attempting to execute the SQL '/* UnregisteredSQLString */ SELECT a_overflow_seq.NEXTVAL FROM DUAL' we caught a SQLException.
The SQL was executed with the following bind args:
()
End of verbose SQLException error message: Numeric Overflow with newMessage While attempting to execute the SQL '/* UnregisteredSQLString */ SELECT a_overflow_seq.NEXTVAL FROM DUAL' we caught a SQLException.
The SQL was executed with the following bind args:
()
End of verbose SQLException error message: Numeric Overflow
2017-07-31 12:57:49,573 WARN [OperationalTransform-3] com.palantir.tritium.event.log.logging.InvocationEventHandler user: user_id: - Failed throwable com.palantir.exception.PalantirSqlException: While attempting to execute the SQL '/* UnregisteredSQLString */ SELECT a_overflow_seq.NEXTVAL FROM DUAL' we caught a SQLException.
The SQL was executed with the following bind args:
()
End of verbose SQLException error message: Numeric Overflow
com.palantir.exception.PalantirSqlException: While attempting to execute the SQL '/* UnregisteredSQLString */ SELECT a_overflow_seq.NEXTVAL FROM DUAL' we caught a SQLException.
The SQL was executed with the following bind args:
()
End of verbose SQLException error message: Numeric Overflow
     at sun.reflect.GeneratedConstructorAccesssor211.newinstance(Unknown Source)
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at com.palantir.common.base.Throwables.rewrap(Throwables.java:175)
     at com.palantir.common.base.Throwables.rewrapAndThrowIfInstance(Throwables.java:132)

### PR DESCRIPTION
**Pull request by hsaraogi**
**Goals (and why)**: Fix #2226.

**Implementation Description (bullets)**: The query for overflow sequence Oracle should return long rather than typecasting it to an int.

Smoke tested by inserting more than INT_MAX value into the DB after a repro.

**Concerns (what feedback would you like?)**: not really.

**Where should we start reviewing?**: Small change.

**Priority (whenever / two weeks / yesterday)**: today

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2224)

### CODE REVIEW

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnection.java [hunk 1]
```diff
@@ -33,6 +33,7 @@
     boolean selectExists(String key, Object... vs) throws PalantirSqlException, PalantirInterruptedException;
     boolean selectExists(final RegisteredSQLString sql, Object... vs) throws PalantirSqlException, PalantirInterruptedException;
     int selectIntegerUnregisteredQuery(String sql, Object... vs) throws PalantirSqlException, PalantirInterruptedException;
+    long selectLongUnregisteredQuery(String sql, Object... vs) throws PalantirSqlException, PalantirInterruptedException;
```
Comment (schlosna) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnection.java]: Do we have impl for this? Are there other places we should be reading as longs that are time bombs?

File: atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/OverflowSequenceSupplierTest.java [hunk 2]
```diff
@@ -65,7 +65,7 @@ public void shouldSkipValuesReservedByOtherSupplier() throws Exception {
         final SqlConnection sqlConnection = mock(SqlConnection.class);
 
         when(conns.get()).thenReturn(sqlConnection);
-        when(sqlConnection.selectIntegerUnregisteredQuery(anyString())).thenReturn(1, 1001, 2001);
+        when(sqlConnection.selectLongUnregisteredQuery(anyString())).thenReturn(1L, 1001L, 2001L);
```
Comment (schlosna) [inline atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/OverflowSequenceSupplierTest.java]: Fine doing this in a follow up PR, but can we improve the test cases around sequences > Integer.MAX_VALUE

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnection.java (hunk 1 above)
Comment (schlosna) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnection.java]: Looking at this in IDE now and this is implemented by `com.palantir.nexus.db.sql.ConnectionBackedSqlConnectionImpl#selectLongUnregisteredQuery` -> `com.palantir.nexus.db.sql.SqlConnectionHelper#selectLongUnregisteredQuery` -> `com.palantir.nexus.db.sql.BasicSQL#selectLongInternal`
