### PR TITLE
Reimplement KeyValueServiceScrubberStore

### LINKED ISSUE #2230: Background scrubbing doesn't work well
**Background Information**

The background scrubber is basically a more targeted sweeper. When a transaction run in hard delete mode commits, the writes that it made are recorded in a scrubber store. Later, a background thread reads the cells recorded in the scrubber store and does effectively a targeted sweep of those cells.

**Current Implementation**

The scrubber store maintains a table in your key value service called `_scrub` that tracks the cells and tables that need to be scrubbed. The table is structured as follows
```
row: the row of the cell to be scrubbed
col: the column of the cell to be scrubbed
ts: the start timestamp of the hard delete transaction that made the scrub request
value: the list of tables containing the cell to be scrubbed.
```

The background scrubber periodically does a `getRange` request on this table, checks that the corresponding hard delete transactions actually committed (or rolls them back if necessary), loads the timestamps for the cells it should delete, deletes those cells at the appropriate timestamps, then deletes those cells from the `_scrub` table.

**Problem**

When the background scrubber deletes from the `_scrub` table, it only deletes what it read from the `getRange` request. The `getRange` request only returns the most recent recorded version of each cell. Hence, if a cell is queued for scrubbing more frequently than the background scrubber is run, the scrub queue will grow without bound. If the cell was queued for scrubbing in some table in the past, and then is repeatedly queued for scrubbing in another table, it will not get scrubbed from the first table.

**Proposed Solution**

Fixing the problem with the existing form of the scrub queue is tricky because the historic values of the cells in the scrub queue have useful data, the tables to scrub. A solution that keeps the current schema would need to do historic reads and merge those tables together.

Instead, I want to create a new scrub queue of the form
```
row: the row of the cell to be scrubbed
col: the table containing the cell to be scrubbed + the column of the cell to be scrubbed
ts: the start timestamp of the hard delete transaction that made the scrub request
value: new byte[] {0}
```
and change the scrubber to delete the corresponding (table, cell, ts) from the scrub queue whenever it deletes from normal tables.

It is possible to do a migration from the old scrub queue to the new one (since no new information is tracked), but I'd rather not because
1) It adds additional complexity in the form of a potentially expensive upgrade task.
2) It's not necessary to maintain the guarantees that background scrub provides (a full background sweep deletes the same data, just not as quickly).
3) The existing scrub queues that suffer from this problem are mostly full of garbage. The cells they reference have mostly already been scrubbed.

Instead, I plan to simply drop the old `_scrub` table and create a new `_scrub2` table.

### PR DESCRIPTION
**Pull request by tjwilson90**
also adds a cli to either truncate the old scrub queue or migrate its
contents to the new scrub queue.

Fixes #2230

**Goals (and why)**:

**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2232)

### CODE REVIEW

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java [hunk 1]
```diff
@@ -255,9 +256,8 @@ void runBackgroundScrubTask(final TransactionManager txManager) {
             final byte[] endRow = rangeBoundaries.get(i + 1);
             readerFutures.add(readerExec.submit(() -> {
                 BatchingVisitable<SortedMap<Long, Multimap<TableReference, Cell>>> scrubQueue = scrubberStore
-                        .getBatchingVisitableScrubQueue(batchSize, maxScrubTimestamp, startRow, endRow);
-                // Take one at a time since we already batched them together in KeyValueServiceScrubberStore.
-                BatchingVisitableView.of(scrubQueue).batchAccept(1, batch -> {
+                        .getBatchingVisitableScrubQueue(maxScrubTimestamp, startRow, endRow);
+                scrubQueue.batchAccept(batchSize, batch -> {
```
Comment (hsaraogi) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java]: `BatchingVisitableView.of(scrubQueue)` was removed here? Just wanted to understand the motivation behind removing it?

File: atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/scrub/KeyValueServiceScrubberStoreTest.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+        scrubStore.queueCellsForScrubbing(ImmutableMultimap.of(cell1, ref1, cell2, ref1), timestamp1, 1000);
+        scrubStore.queueCellsForScrubbing(ImmutableMultimap.of(cell1, ref1, cell3, ref2), timestamp2, 1000);
+        Assert.assertEquals(
+                ImmutableList.of(ImmutableSortedMap.of(
+                        timestamp1, ImmutableMultimap.of(ref1, cell2),
+                        timestamp2, ImmutableMultimap.of(ref2, cell3, ref1, cell1))),
+                getScrubQueue());
+        scrubStore.markCellsAsScrubbed(ImmutableMap.of(
+                ref2, ImmutableMultimap.of(cell3, timestamp2),
+                ref1, ImmutableMultimap.of(cell1, timestamp1)), 1000);
```
Comment (hsaraogi) [inline atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/scrub/KeyValueServiceScrubberStoreTest.java]: Looks like we should mark `cell1`, `timestamp2` as scrubbed here, since the scrub queue returns the cell at `timestamp2`.

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+import com.palantir.common.base.ClosableIterator;
+
+import io.airlift.airline.Command;
+import io.airlift.airline.Option;
+
+@Command(name = "scrub-queue-migration",
+        description = "Move the contents of the old scrub queue into the new "
+                + "scrub queue. This operation is resumable.")
+public class ScrubQueueMigrationCommand extends SingleBackendCommand {
+    private static final byte[] EMPTY_CONTENTS = new byte[] {1};
```
Comment (tjwilson90) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java]: will do

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+                    + "in the scrub queue).")
+    boolean truncateOldQueue;
+
+    @Option(name = {"--batch-size"},
+            description = "Batch size for copying rows, defaults to 1000.")
+    Integer batchSize;
+
+    @Override
+    public int execute(AtlasDbServices services) {
+        PrintWriter output = new PrintWriter(System.out, true);
```
Comment (tjwilson90) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java]: will do

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+        Multimap<Cell, Long> batchToDelete = ArrayListMultimap.create();
+        while (iter.hasNext()) {
+            RowResult<Value> rowResult = iter.next();
+            byte[] row = rowResult.getRowName();
+            for (Entry<byte[], Value> entry : rowResult.getColumns().entrySet()) {
+                byte[] col = entry.getKey();
+                Value value = entry.getValue();
+                long timestamp = value.getTimestamp();
+                String[] tableNames = StringUtils.split(
+                        PtBytes.toString(value.getContents()), '\0');
```
Comment (tjwilson90) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java]: will do

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServiceScrubberStore.java [hunk 6]
```diff
@@ -60,24 +57,24 @@
...
                 new ColumnMetadataDescription(new DynamicColumnDescription(
                         NameMetadataDescription.create(ImmutableList.of(
-                                new NameComponentDescription("name", ValueType.STRING))),
-                        ColumnValueDescription.forType(ValueType.STRING))),
-                        ConflictHandler.IGNORE_ALL).persistToBytes());
+                                new NameComponentDescription("table", ValueType.VAR_STRING),
+                                new NameComponentDescription("col", ValueType.BLOB))),
+                        ColumnValueDescription.forType(ValueType.VAR_LONG))),
+                ConflictHandler.IGNORE_ALL);
+        keyValueService.createTables(ImmutableMap.of(
```
Comment (tjwilson90) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServiceScrubberStore.java]: nope

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java (hunk 1 above)
Comment (tjwilson90) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java]: Wrapping a BatchingVisitable in a batchingVisitableView just to call batchAccept on it is exactly like wrapping an Iterable in a FluentIterable just to call iterate on it. It accomplishes nothing.

File: atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/scrub/KeyValueServiceScrubberStoreTest.java (hunk 2 above)
Comment (tjwilson90) [inline atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/scrub/KeyValueServiceScrubberStoreTest.java]: Sure, the test is just checking that after deleting some stuff the scrub queue is in the expected state. I was not carefully making sure to delete the same stuff the scrubber would. I'll do that though.
