### PR TITLE
Register the right exception mapper and modify tests

### LINKED ISSUE #1984: Embedded clients cannot deserialize 503s responses with NotCurrentLeaderException
Seen on internal testing infrastructure: when clients receive a NotCurrentLeaderException, they throw the error:

`com.palantir.atlasdb.shaded.com.palantir.remoting2.errors.SerializableErrorToExceptionConverter:
Failed to deserialize exception: Error 503. Reason: Service Unavailable. Failed to parse error body and deserialize exception: Can not deserialize instance of java.lang.String out of START_OBJECT token at <stack_trace>`

This does not make the test fail, just makes the response harder to parse and increases its size.

### PR DESCRIPTION
**Pull request by hsaraogi**
#**Goals (and why)**: AtlasDBEteServer should be able to deserialize HTTP exceptions in embedded mode. Fixes #1984.

**Implementation Description (bullets)**:
1. Register the ExceptionMappers from http-remoting.
2. Fix test code

**Concerns (what feedback would you like?)**: every application need to register HttpRemotingJerseyFeature with the dropwizard environment if running in the embedded mode. Most already do! Should we modify docs for this?

**Where should we start reviewing?**: AtlasDbEteServer.java

**Priority (whenever / two weeks / yesterday)**: normal

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1998)

### CODE REVIEW

File: atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java [hunk 1]
```diff
@@ -127,9 +128,9 @@ private void assertNoLongerExposesEmbeddedTimestampService() {
 
         // as() is not compatible with assertThatThrownBy - see
         // http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/Assertions.html
-        softAssertions.assertThat(catchThrowable(timestampClient::getFreshTimestamp))
-                .as("no longer exposes an embedded timestamp service")
-                .hasMessageContaining("404");
+        softAssertions.assertThat(
+                ((AtlasDbRemoteException) catchThrowable(timestampClient::getFreshTimestamp)).getStatus())
+                .as("no longer exposes an embedded timestamp service");
```
Comment (jeremyk-91) [inline atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java]: I think we also want to check that the status is equal to 404 as well...
