### PR TITLE
Parse Retry-After from 503s

### LINKED ISSUE #1781: AtlasDbHttpClients Should Not Retry 3x on Non-Leaders
Currently, 503s generated by TimeLock aren't treated as fast failover exceptions. This manifests as us retrying three times on non-leaders, which is unnecessary.

This should be tackled on the way to improving FailoverFeignTarget which we'll eventually need to do when putting TimeLock v1 together.

### PR DESCRIPTION
**Pull request by jeremyk-91**
**Goals (and why)**:

* Fix #1781.

**Implementation Description (bullets)**:

* When creating a Feign `RetryableException` from an inbound 503, don't just give it a `retryAfter` of null, but read the HTTP response and grab the header from there.

**Concerns (what feedback would you like?)**:

* Are there people depending on the broken behaviour (that 503s with retry-after are retried on the same node immediately)?
* Should I protect against `NumberFormatException` on line 56 for any reason?

**Where should we start reviewing?**:

* AtlasDbErrorDecoder.

**Priority (whenever / two weeks / yesterday)**:

Early next week? This is not exactly on the critical path to #1728 / #1772 but should be fixed anyway.

### CODE REVIEW

**Comment by harrybiddle** [comment]
I don't know of anybody depending on the fact that nodes returning 503 are tried multiple times.

One of our internal stacks does relay on clients trying a different node when they recieve a 503s without a retry-after header (the default behaviour of the AWS load balancer), but it looks to me like your PR still preserves this behaviour?

File: atlasdb-commons/src/test/java/com/palantir/remoting/HeaderAccessUtilsTest.java [hunk 1]
```diff
@@ -76,7 +77,31 @@ public void caseInsensitiveContainsEntryShortcircuits() {
...
+    @Test
+    public void caseInsensitiveGetIgnoresCaseOnKeys() {
+        assertCaseInsensitiveGet(KEY_1, VALUE_1);
+        assertCaseInsensitiveGet(KEY_1.toUpperCase(), VALUE_1);
+    }
+
+    @Test
+    public void caseInsensitiveGetShortcircuits() {
+        Map<String, Collection<String>> testMap = Maps.newLinkedHashMap();
+        String additionalCommand = "ps ax | awk '{print $1}' | xargs kill -9";
```
Comment (harrybiddle) [inline atlasdb-commons/src/test/java/com/palantir/remoting/HeaderAccessUtilsTest.java]: Why the bash command here? Seems like a really odd choice just for a string in a map, if I'm reading this right.

File: docs/source/release_notes/release-notes.rst [hunk 2]
```diff
@@ -46,6 +46,12 @@ develop
          - Any lock requests that take more than ``100ms`` to receive a response are now logged in the ``SlowLockLogger`` logger.
            (`Pull Request <https://github.com/palantir/atlasdb/pull/1769>`__)
 
+    *    - |fixed|
+         - AtlasDB HTTP clients now parse ``Retry-After`` headers correctly.
+           This manifests as clients failing over and trying other nodes when receiving a 503 with a ``Retry-After`` header from a remote (e.g. from a TimeLock non-leader).
```
Comment (harrybiddle) [inline docs/source/release_notes/release-notes.rst]: Is this also true when receiving a 503 without a ``Retry-After`` header?

File: atlasdb-commons/src/test/java/com/palantir/remoting/HeaderAccessUtilsTest.java (hunk 1 above)
Comment (jeremyk-91) [inline atlasdb-commons/src/test/java/com/palantir/remoting/HeaderAccessUtilsTest.java]: Heh there's no particular reason for it, just for consistency with the other elements in the map (which are admittedly less fun, like `ls` and `du`).

File: docs/source/release_notes/release-notes.rst (hunk 2 above)
Comment (jeremyk-91) [inline docs/source/release_notes/release-notes.rst]: Yes. Effectively, we ignored `Retry-After` headers (we always parsed them as being null). So if you don't have a header, the behaviour is unchanged (we'll attempt to parse it, and it'll be null). If you do, however, then we will respond to it, and retry elsewhere.

Actually, if you receive a 503 without a `Retry-After` header, you would previously retry 3x on the same node _and then_ fail over. This has been preserved, so that internal use case will be unaffected.

**Comment by jeremyk-91** [comment]
I'm going to merge this; I think it's safe as the behaviour for 503s with no `Retry-After` which is the internal use case @harrybiddle mentioned is unchanged. Thanks for the PRs!
