### PR TITLE
Fully Paxos-Backed Timelock Server Implementation

### LINKED ISSUE #645: AtlasDB server: Have a cluster that can offer timestamps and locks to clients in multiple keyspaces

### LINKED ISSUE #1192: KVS Migration Breaks TimestampService Contract
The timestamp service contract / api states:
```
    /**
     * This will get a fresh timestamp that is guaranteed to be newer than any other timestamp
     * handed out before this method was called.
     */
```

The act of doing a KVS migration with an embedded timestamp service whose timestamp data is co-located in the same KVS and keyspace/database/etc as the Atlas data causes the timestamps to reset back to the logical beginning of time (timestamp 1). This breaks the contract and anyone who might be relying on that contract being true (though it's generally rare to see an embedded TimestampService being used by a client other than Atlas).

I propose we change the logic to the following: At the beginning of the KVS migration, fetch a fresh timestamp from the old timestamp/service and use that timestamp to fast-forward the new TimestampService. Then continue on as usual.

### LINKED ISSUE #1292: Validation of LeaderAndTerm is too strict
When a new leader is elected, we don't update the leader info (which is used by individual classes to decide whether to serve requests or not) if the term is not newer than what's already there. Ordinarily, this is correct because terms are increasing. However, this is incorrect in a specific case, where all nodes in a cluster crash. We have from the Atomix API docs (for [Election](http://atomix.io/atomix/api/latest/io/atomix/group/election/Election.html)):

> The Term.term() is guaranteed to be unique and monotonically increasing _throughout the lifetime of a group._ (emphasis mine)

But if all nodes in a cluster crash or are otherwise stopped, (if I'm not wrong) the group's lifetime is considered to have ended. This is definitely the case on a 1 node cluster:

```java
INFO  [2016-11-25 20:29:56,025] io.atomix.copycat.server.state.ServerContext: localhost/127.0.0.1:8700 - Transitioning to LEADER
INFO  [2016-11-25 20:29:56,028] io.atomix.copycat.server.state.ServerContext: localhost/127.0.0.1:8700 - Found leader localhost/127.0.0.1:8700
INFO  [2016-11-25 20:29:56,035] io.atomix.copycat.server.state.ServerStateMachine: localhost/127.0.0.1:8700 - Installing snapshot 1
INFO  [2016-11-25 20:29:56,078] io.atomix.copycat.server.CopycatServer: Server started successfully!
INFO  [2016-11-25 20:29:56,112] io.atomix.copycat.client.session.ClientSession: Registered session 208
INFO  [2016-11-25 20:29:56,153] com.palantir.atlasdb.timelock.TimeLockServer: Not setting the leader to LeaderAndTerm{term=0, leaderId=384f2ea7-2152-4fd9-9f6d-9dea455e2e11} since it is not newer than the current leader LeaderAndTerm{term=8, leaderId=2a332a28-0984-4f03-9387-7f6bed4e7467}
```

In this case it seems that Atomix starts again from 0, and so no one will touch the existing LeaderAndTerm. This means the ID remains as that of the leader immediately before the cluster crashed, and this seems to be some UUID that's freshly generated i.e. **no one is the leader**, which means that timestamps and locks cannot be issued at all.

Workaround/recovery: open a separate atomix client, have it join the cluster and explicitly clear the leader value.

If Timelock was fully in use I'd lean towards a P0 (especially if it was compulsory, as single node clusters are completely unusable), but since it's not I've put it as P1 for now.

### LINKED ISSUE #1310: Timelock Server can issue decreasing and duplicated timestamps after network partition
During @harrybiddle's Jepsen testing, we found that the Timelock Service could give duplicated and increasing timestamps. We probed further into the logs and found that this seemed to be an issue with recovery from network partitions. Consider the following logs:

```java
2016-11-29 13:20:19,846{GMT}	INFO	[jepsen worker 4] jepsen.util: 4	:invoke	:read-operation	nil
2016-11-29 13:20:19,847{GMT}	INFO	[jepsen worker 0] jepsen.util: 0	:invoke	:read-operation	nil
2016-11-29 13:20:19,864{GMT}	INFO	[jepsen worker 4] jepsen.util: 4	:ok	:read-operation	3681
2016-11-29 13:20:19,864{GMT}	INFO	[jepsen worker 0] jepsen.util: 0	:ok	:read-operation	3680
2016-11-29 13:20:20,748{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	"Cut off {:n3 #{:n4 :n2 :n5}, :n1 #{:n4 :n2 :n5}, :n4 #{:n3 :n1}, :n2 #{:n3 :n1}, :n5 #{:n3 :n1}}"
2016-11-29 13:20:43,527{GMT}	INFO	[jepsen worker 4] jepsen.util: 4	:fail	:read-operation	nil	feign.FeignException: status 500 reading TimestampService#getFreshTimestamp(); content:
{
  "message" : "a27c4c51-11d3-474d-8712-ec21a465a002",
  "exceptionClass" : "com.google.common.util.concurrent.UncheckedExecutionException",
  "stackTrace" : null
}
2016-11-29 13:20:40,749{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	nil
2016-11-29 13:20:40,961{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	"fully connected"
2016-11-29 13:20:43,570{GMT}	INFO	[jepsen worker 4] jepsen.util: 4	:invoke	:read-operation	nil
2016-11-29 13:20:43,582{GMT}	INFO	[jepsen worker 4] jepsen.util: 4	:ok	:read-operation	3680 // what??
```

This is wrong on two counts: it is a duplicate, and also does not obey the contract that timestamps are monotonically increasing. Looking at the other Jepsen messages, it seems that what happened was as follows:

* n3 was the leader
* At 13:20:20, the Jepsen nemesis created a network partition, splitting the network to {n1 n3} and {n2 n4 n5}.
* At 13:20:40, the Jepsen nemesis restored the network.

Looking at the logs for n3:

```java
10.0.42.1 - - [29/Nov/2016:13:20:19 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 200 4 "-" "okhttp/2.5.0" 3
10.0.42.1 - - [29/Nov/2016:13:20:19 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 200 4 "-" "okhttp/2.5.0" 6
WARN  [2016-11-29 13:20:20,640] io.atomix.copycat.server.state.LeaderAppender: n3/10.0.0.4:8700 - AppendRequest to n4/10.0.0.5:8700 failed. Reason: request timed out
(some comments about netty failing)
WARN  [2016-11-29 13:20:25,643] io.atomix.copycat.server.state.LeaderAppender: n3/10.0.0.4:8700 - Suspected network partition. Stepping down
INFO  [2016-11-29 13:20:25,654] io.atomix.copycat.server.state.ServerContext: n3/10.0.0.4:8700 - Transitioning to FOLLOWER
(keep polling everyone)
ERROR [2016-11-29 13:20:43,485] com.palantir.remoting1.servers.jersey.JsonExceptionMapper: Error 3595d8f0-3290-4e39-bf6f-9620c4766b54: io.atomix.copycat.session.ClosedSessionException: session closed
ERROR [2016-11-29 13:20:43,493] com.palantir.remoting1.servers.jersey.JsonExceptionMapper: Error 6d995374-2b57-4e85-9241-9db2a41d5b37: Could not contact the cluster. Has this node (6083989b-fa2e-4284-bcf0-b466298ab7e8) been partitioned off?
10.0.42.1 - - [29/Nov/2016:13:20:20 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 500 165 "-" "okhttp/2.5.0" 23464
10.0.42.1 - - [29/Nov/2016:13:20:22 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 503 143 "-" "okhttp/2.5.0" 20508
10.0.42.1 - - [29/Nov/2016:13:20:38 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 503 143 "-" "okhttp/2.5.0" 5272
10.0.42.1 - - [29/Nov/2016:13:20:19 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 500 165 "-" "okhttp/2.5.0" 23537
10.0.42.1 - - [29/Nov/2016:13:20:25 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 503 143 "-" "okhttp/2.5.0" 17532
10.0.42.1 - - [29/Nov/2016:13:20:38 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 503 143 "-" "okhttp/2.5.0" 5280
(more of the "partitioned off?" errors, which are fine)
ERROR [2016-11-29 13:20:43,505] com.palantir.remoting1.servers.jersey.JsonExceptionMapper: Error 5bd6fdb8-f015-40a8-acae-ea4b57fae576: io.atomix.copycat.error.UnknownSessionException: unknown member session
ERROR [2016-11-29 13:20:43,509] com.palantir.remoting1.servers.jersey.JsonExceptionMapper: Error ee2f2753-b3bf-407b-9f87-a34e50e041c5: Could not contact the cluster. Has this node (6083989b-fa2e-4284-bcf0-b466298ab7e8) been partitioned off?
(more of the "partitioned off?" errors, which are unusual at this point!)
INFO  [2016-11-29 13:20:43,538] io.atomix.copycat.client.session.ClientSession: Registered session 3999
10.0.42.1 - - [29/Nov/2016:13:20:43 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 200 4 "-" "okhttp/2.5.0" 8
10.0.42.1 - - [29/Nov/2016:13:20:43 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 200 4 "-" "okhttp/2.5.0" 5
10.0.42.1 - - [29/Nov/2016:13:20:43 +0000] "POST /test/timestamp/fresh-timestamp HTTP/1.1" 200 4 "-" "okhttp/2.5.0" 4
(gives out more timestamps)
INFO  [2016-11-29 13:20:47,330] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n2/10.0.0.3:8700
INFO  [2016-11-29 13:20:47,701] io.atomix.copycat.server.state.FollowerState: n3/10.0.0.4:8700 - Polling members [ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n1/10.0.0.2:8700, clientAddress=n1/10.0.0.2:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n2/10.0.0.3:8700, clientAddress=n2/10.0.0.3:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n4/10.0.0.5:8700, clientAddress=n4/10.0.0.5:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n5/10.0.0.6:8700, clientAddress=n5/10.0.0.6:8700]]
INFO  [2016-11-29 13:20:47,702] io.atomix.copycat.server.state.ServerContext: n3/10.0.0.4:8700 - Transitioning to CANDIDATE
INFO  [2016-11-29 13:20:47,702] io.atomix.copycat.server.state.CandidateState: n3/10.0.0.4:8700 - Starting election
INFO  [2016-11-29 13:20:47,731] io.atomix.copycat.server.state.CandidateState: n3/10.0.0.4:8700 - Requesting votes from [ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n1/10.0.0.2:8700, clientAddress=n1/10.0.0.2:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n2/10.0.0.3:8700, clientAddress=n2/10.0.0.3:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n4/10.0.0.5:8700, clientAddress=n4/10.0.0.5:8700], ServerMember[type=ACTIVE, status=AVAILABLE, serverAddress=n5/10.0.0.6:8700, clientAddress=n5/10.0.0.6:8700]]
INFO  [2016-11-29 13:20:47,762] io.atomix.copycat.server.state.ServerContext: n3/10.0.0.4:8700 - Transitioning to LEADER
```

Let's probe a bit further into the logs; during the partition, n2 transitioned to be the leader, but was never recognised as such (I guess it failed to write to the distributed LeaderAndTerm).

```java
INFO  [2016-11-29 13:20:23,218] io.atomix.copycat.server.state.ServerContext: n2/10.0.0.3:8700 - Transitioning to LEADER
INFO  [2016-11-29 13:20:23,221] io.atomix.copycat.server.state.ServerContext: n2/10.0.0.3:8700 - Found leader n2/10.0.0.3:8700
WARN  [2016-11-29 13:20:23,909] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - Failed to configure n1/10.0.0.2:8700
WARN  [2016-11-29 13:20:23,910] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - AppendRequest to n1/10.0.0.2:8700 failed. Reason: request timed out
WARN  [2016-11-29 13:20:23,953] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - Failed to configure n3/10.0.0.4:8700
WARN  [2016-11-29 13:20:23,954] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - AppendRequest to n3/10.0.0.4:8700 failed. Reason: request timed out
INFO  [2016-11-29 13:20:23,987] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n1/10.0.0.2:8700
INFO  [2016-11-29 13:20:23,987] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n3/10.0.0.4:8700
INFO  [2016-11-29 13:20:24,238] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n1/10.0.0.2:8700
INFO  [2016-11-29 13:20:24,238] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n3/10.0.0.4:8700
INFO  [2016-11-29 13:20:26,103] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n5/10.0.0.6:8700
INFO  [2016-11-29 13:20:26,104] io.atomix.catalyst.transport.netty.NettyClient: Connected to n5/10.0.0.6:8700
WARN  [2016-11-29 13:20:28,992] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - AppendRequest to n1/10.0.0.2:8700 failed. Reason: io.netty.channel.ConnectTimeoutException: connection timed out: n1/10.0.0.2:8700
WARN  [2016-11-29 13:20:28,992] io.atomix.copycat.server.state.LeaderAppender: n2/10.0.0.3:8700 - AppendRequest to n3/10.0.0.4:8700 failed. Reason: io.netty.channel.ConnectTimeoutException: connection timed out: n3/10.0.0.4:8700
INFO  [2016-11-29 13:20:28,992] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n1/10.0.0.2:8700
INFO  [2016-11-29 13:20:28,998] io.atomix.catalyst.transport.netty.NettyClient: Connecting to n3/10.0.0.4:8700
ERROR [2016-11-29 13:20:29,004] com.palantir.remoting1.servers.jersey.JsonExceptionMapper: Error 47c6e030-66e7-48d4-a066-1551ddb796ec: This node (d2566ef2-d33d-4270-b79f-cd79dad52b93) is not the leader (LeaderAndTerm{term=8, leaderId=6083989b-fa2e-4284-bcf0-b466298ab7e8})
```

I'm in the process of investigating this further.

Filing as P0, as this is a correctness bug (and happened with just a few thousand timestamps!)

### LINKED ISSUE #1315: Timelock Server can fail to issue timestamps from a majority network partition
_Moved from #1310; this probably isn't it, but is something else I found while debugging #1310._

I think I've got a bit more insight into the problem, after some debugging.

There are multiple leaders in place when we run Atomix:
* When we create an Atomix cluster, we use Raft to decide a group leader.
* The `DistributedGroup` is a separate notion, which sits on top of the Atomix cluster; its leader election is distinct from the leader election of the Atomix cluster.

Consider that all Timelock operations are dependent on the `DistributedGroup` leader, not the cluster leader. This is because that's what's used to write to `LeaderAndTerm`. Furthermore, if a server leaves the network and rejoins it owing to a closed session, a new client is constructed, with a new session ID. Critically, _this means it is no longer a member of the `DistributedGroup`_. The other nodes will do a re-election on the reduced group.

In fact, this is consistent with what happened during the Jepsen run. Investigating the behaviour of the nemesis, we had

```java
2016-11-29 13:18:33,806{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	nil
2016-11-29 13:18:34,985{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	"Cut off {:n2 #{:n3 :n4 :n5}, :n1 #{:n3 :n4 :n5}, :n3 #{:n2 :n1}, :n4 #{:n2 :n1}, :n5 #{:n2 :n1}}"
2016-11-29 13:18:54,987{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	nil
2016-11-29 13:18:55,198{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	"fully connected"
2016-11-29 13:19:00,200{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	nil
2016-11-29 13:19:01,380{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	"Cut off {:n3 #{:n4 :n2 :n1}, :n5 #{:n4 :n2 :n1}, :n4 #{:n3 :n5}, :n2 #{:n3 :n5}, :n1 #{:n3 :n5}}" // no news about a re-election?
2016-11-29 13:19:21,381{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	nil
2016-11-29 13:19:21,593{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	"fully connected"
2016-11-29 13:19:26,594{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	nil
2016-11-29 13:19:27,935{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	"Cut off {:n5 #{:n3 :n4 :n2}, :n1 #{:n3 :n4 :n2}, :n3 #{:n5 :n1}, :n4 #{:n5 :n1}, :n2 #{:n5 :n1}}"
2016-11-29 13:19:47,936{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	nil
2016-11-29 13:19:48,145{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:stop	"fully connected"
2016-11-29 13:19:53,146{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	nil
2016-11-29 13:19:54,408{GMT}	INFO	[jepsen nemesis] jepsen.util: :nemesis	:info	:start	"Cut off {:n4 #{:n3 :n5 :n1}, :n2 #{:n3 :n5 :n1}, :n3 #{:n4 :n2}, :n5 #{:n4 :n2}, :n1 #{:n4 :n2}}"
```

Observe that during the first partition the majority is {n3, n4, n5} including the then-leader. From the cluster's point of view, n1 and n2 left. So the `timeLockGroup` likely still had n3, n4 and n5; since n3 was the starting leader, no re-election took place. The next group would have had n4 leave, and the one after that have n5 leave, leaving n3 as the _only_ leader of the `timeLockGroup` regardless of whatever happens in the Atomix groups. 

Now only n3 can ever issue anything (because the invalidating leader proxy blocks all of the other nodes), and so if the network is partitioned with the majority not including n3 then no one can issue timestamps or locks (because they aren't going to update the `LeaderAndTerm` even if there are any more elections).

Running more tests with @harrybiddle that feature additional logging now, but offhand it seems like a reasonable solution could be to use persistent groups (but we need to explore the semantics of that).

Some of this will be fixed by atomix/atomix#190, but their CI build didn't pass so it wasn't published.

If not, we might want to see if there's a way we can work around this, as well.

### PR DESCRIPTION
**Pull request by jeremyk-91**
This change provides a "fully" Paxos-backed implementation of the Timelock Server. This is one way of getting around several Timelock correctness issues, such as #1292, #1310, #1315. More comprehensively:

* Builds on @carrino's work on `PaxosTimestampBoundStore`: wiring it up with the Timelock Server, supporting multiple namespaces and more configurability; also fixing a bootstrapping issue.
* Adds `PaxosServerImplementation` which sets up a gatekeeping leader election service around `InvalidatingLeaderProxy`s for clients; each client has a timestamp service backed by `PaxosTimestampBoundStore`, as well as a lock service.
* Adds `PaxosConfiguration` as an allowed algorithm configuration.
* Switches default configuration as well as test configuration used for Jepsen tests to point at Paxos.
* Adds heavy unit and some one-node integration tests for the config changes, `PaxosTimestampBoundStore` and `PaxosServerImplementation`.
* **[BREAKING]** Clients can no longer have names starting with two underscores; I have reserved this for internal usage. I'm happy to change this protocol if required.

I realise this PR is already massive, so I have *not* included the following in this PR:

* Docs updates (I will update #1279 after this merges)
* Fast-forward functionality (needed for migrations)
* Removing Atomix support from `develop` for now

That said of the ~1700 diff it seems ~1000 of that is test code.

I'd like to merge this in quickly so that we can continue with future Timelock work, so ping me with feedback and I'll be right on it! (within reasonable limits of course)

Things I need to do:

- [x] Add Javadoc for `PaxosTimestampBoundStore` and flesh out the `TimestampBoundStore` one a little more
- [x] Rename TimeLockServer and TimeLockServerImplementation classes once we're happy with the naming conventions

Things deferred:

- Certain refactoring issues 1461-1463: test-commons, PaxosTBS state manager, LeaderElectionService constructor
- SSL testing (nontrivial, has been manually tested) 1464

Fixes #1292.
Fixes #1310.
Fixes #1315.
Fixes #645.
Fixes #1192.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1442)

### CODE REVIEW

**Comment by jeremyk-91** [comment]
(There are some changes to #1425 that I'll need to make and cherry-pick onto this.)

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+    private static final String NONEXISTENT_CLIENT = "nonexistent";
+    private static final String INVALID_CLIENT = "test2\b";
+
+    private static final Optional<SSLSocketFactory> NO_SSL = Optional.absent();
+    private static final String LOCK_CLIENT_NAME = "lock-client-name";
+    private static final SortedMap<LockDescriptor, LockMode> LOCK_MAP = ImmutableSortedMap.of(
+            StringLockDescriptor.of("lock1"), LockMode.WRITE);
+
+    @ClassRule
+    public static final DropwizardAppRule<TimeLockServerConfiguration> APP = new DropwizardAppRule<>(
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: APP -> TIMELOCK_SERVER

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+            TimeLockServer.class,
+            ResourceHelpers.resourceFilePath("paxosSingleServer.yml"));
+
+    @AfterClass
+    public static void tearDownClass() throws Exception {
+        FileUtils.deleteDirectory(new File("var/test/data"));
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Is it safe to run tests with deleting the directory, I am afraid in production operations will run without cleaning it each time.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+        lockService1.unlock(token1);
+        lockService2.unlock(token2);
+    }
+
+    @Test
+    public void lockServiceShouldNotAllowUsToRefreshLocksFromDifferentNamespaces() throws InterruptedException {
+        RemoteLockService lockService1 = getLockService(CLIENT_1);
+        RemoteLockService lockService2 = getLockService(CLIENT_2);
+
+        LockRefreshToken token1 = lockService1.lock(LOCK_CLIENT_NAME, LockRequest.builder(LOCK_MAP)
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: token1 -> token

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java [hunk 4]
```diff
@@ -0,0 +1,170 @@
...
+        TimestampService timestampService1 = getTimestampService(CLIENT_1);
+        TimestampService timestampService2 = getTimestampService(CLIENT_2);
+
+        long firstServiceFirstTimestamp = timestampService1.getFreshTimestamp();
+        long secondServiceFirstTimestamp = timestampService2.getFreshTimestamp();
+
+        long firstServiceSecondTimestamp = timestampService1.getFreshTimestamp();
+        long secondServiceSecondTimestamp = timestampService2.getFreshTimestamp();
+
+        assertThat(firstServiceFirstTimestamp + 1).isEqualTo(firstServiceSecondTimestamp);
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Is +1 guranteed? Are we no longer caching timestamps?

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+    @After
+    public void tearDown() throws IOException {
+        FileUtils.deleteDirectory(new File(LOG_DIR));
+    }
+
+    @Test
+    public void canAddClients() {
+        paxosResource.addClient(CLIENT_1);
+        assertThat(paxosResource.getPaxosLearner(CLIENT_1)).isNotNull();
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: try hitting a learner/acceptor endpoints like `learn` or `accept` too. This will ensure the endpoint is available here.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+    @Test
+    public void throwsIfTryingToAddClientTwice() {
+        paxosResource.addClient(CLIENT_1);
+        assertThatThrownBy(() -> paxosResource.addClient(CLIENT_1)).isInstanceOf(IllegalStateException.class);
+    }
+
+    @Test
+    public void returnsNullIfClientNotAdded() {
+        paxosResource.addClient(CLIENT_1);
+        assertThat(paxosResource.getPaxosLearner(CLIENT_2)).isNull();
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: Testing endpoints might add more value to this test.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 2 above)
Comment (harrybiddle) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Sorry - I'm a bit confused. Why would this test code run in production?

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 4 above)
Comment (harrybiddle) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: the only guarantee that we need is that the timestamps are strictly higher. in practice for the current implementation, without nodes dying, this is the case.

we are testing that timestamps rise independently for different clients, but i think that's a difficult test if we don't also leverage the fact that the timestamps are incrementing by one.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfigurationTest.java [hunk 7]
```diff
@@ -51,6 +51,12 @@ public void shouldRejectClientsWithInvalidCharacters() {
     }
 
     @Test
+    public void shouldRejectClientsConflictingWithInternalClients() {
+        assertThatThrownBy(() -> new TimeLockServerConfiguration(null, CLUSTER, ImmutableSet.of("__leader")))
```
Comment (harrybiddle) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfigurationTest.java]: `PaxosServerImplementation.LEADER_NAMESPACE`

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java [hunk 8]
```diff
@@ -0,0 +1,170 @@
...
+
+public class PaxosTimeLockServerIntegrationTest {
+    private static final String NOT_FOUND_CODE = "404";
+
+    private static final String CLIENT_1 = "test";
+    private static final String CLIENT_2 = "test2";
+    private static final String NONEXISTENT_CLIENT = "nonexistent";
+    private static final String INVALID_CLIENT = "test2\b";
+
+    private static final Optional<SSLSocketFactory> NO_SSL = Optional.absent();
```
Comment (harrybiddle) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Is it worth it / feasible to test SSL here? Aware that there's a few lines of code in `PaxosServerImplementation` around setting up SSL; I'm wondering if we can fire it, or even mock it. Although `ServerImplementation` doesn't look too mockable ;/.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 9]
```diff
@@ -0,0 +1,233 @@
...
+                client,
+                optionalSecurity,
+                PaxosLearner.class);
+        learners.add(paxosResource.getPaxosLearner(client));
+
+        PaxosProposer proposer = PaxosProposerImpl.newProposer(
+                paxosResource.getPaxosLearner(client),
+                ImmutableList.copyOf(acceptors),
+                ImmutableList.copyOf(learners),
+                acceptors.size() / 2 + 1,
```
Comment (harrybiddle) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: I'm just trying to figure this out - but is this all cool if there is only one node in the configuration, and it's localhost? As far as I can tell, `acceptors.size() = 0`, and I wasn't sure if that was OK.

In a one-node configuration, are you still constructing a kind of one-node Paxos?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 10]
```diff
@@ -0,0 +1,214 @@
...
+    }
+
+    private Optional<SequenceAndBound> getLearnedState(long seq) {
+        if (seq <= PaxosAcceptor.NO_LOG_ENTRY) {
+            return Optional.of(ImmutableSequenceAndBound.of(PaxosAcceptor.NO_LOG_ENTRY, 0L));
+        }
+        List<PaxosLong> responses = PaxosQuorumChecker.collectQuorumResponses(
+                ImmutableList.copyOf(learners),
+                l -> getLearnedValue(seq, l),
+                1,
```
Comment (harrybiddle) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Confused by what the magic `1` is here: could you make it a field?

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 8 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Based on having had problems with SSL in tests in the past, we'd probably be better off assuming `NO_SSL` throughout, except for a small number of tests where we actually test the SSL bit.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 11]
```diff
@@ -0,0 +1,214 @@
...
+import com.palantir.paxos.PaxosLearner;
+import com.palantir.paxos.PaxosProposer;
+import com.palantir.paxos.PaxosQuorumChecker;
+import com.palantir.paxos.PaxosResponse;
+import com.palantir.paxos.PaxosRoundFailureException;
+import com.palantir.paxos.PaxosValue;
+import com.palantir.timestamp.MultipleRunningTimestampServiceError;
+import com.palantir.timestamp.TimestampBoundStore;
+
+public class PaxosTimestampBoundStore implements TimestampBoundStore {
```
Comment (harrybiddle) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: We could add some Javadoc to this class, given that it's all fresh in your mind how it works. Just an idea; I wouldn't block the PR on it!

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 2 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: @hsaraogi might mean "on the build server"?

Also, the safe thing to do here is to use a `@TemporaryFolder`.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 4 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: nit/personal preference: I prefer `Assert.assertEquals` here (expected = fSFT+1, actual = fSST)

**Comment by hsaraogi** [comment]
When discussing offline, we saw these endpoints:
```
    GET     /leader/ping (com.palantir.leader.PaxosLeaderElectionService)
    GET     /leader/uuid (com.palantir.leader.PaxosLeaderElectionService)
    POST    /{client: [a-zA-Z0-9_-]+}/acceptor/accept/{seq} (com.palantir.paxos.PaxosAcceptor)
    POST    /{client: [a-zA-Z0-9_-]+}/acceptor/latest-sequence-prepared-or-accepted (com.palantir.paxos.PaxosAcceptor)
    POST    /{client: [a-zA-Z0-9_-]+}/acceptor/prepare/{seq} (com.palantir.paxos.PaxosAcceptor)
    GET     /{client: [a-zA-Z0-9_-]+}/learner/greatest-learned-value (com.palantir.paxos.PaxosLearner)
    POST    /{client: [a-zA-Z0-9_-]+}/learner/learn/{seq:.+} (com.palantir.paxos.PaxosLearner)
    GET     /{client: [a-zA-Z0-9_-]+}/learner/learned-value/{seq:.+} (com.palantir.paxos.PaxosLearner)
    GET     /{client: [a-zA-Z0-9_-]+}/learner/learned-values-since/{seq:.+} (com.palantir.paxos.PaxosLearner)
    POST    /{client: [a-zA-Z0-9_-]+}/lock/current-time-millis (com.palantir.lock.LockService)
    POST    /{client: [a-zA-Z0-9_-]+}/lock/lock/{client: .*} (com.palantir.lock.LockService)
```

Endpoint with `/leader` is dangerous as a client may share the name.

**Comment by carrino** [comment]
I just wanted to chime in to make sure we were on the same page with
respect to the guarantees we are checking for.

I wouldn't describe the TS guarantee as monotonic because that loses a lot
of nuance with respect to how fail overs happen.

I don't have a good name for it but "resulting ts greater than any
observable ts at request time " is the core guarantee we must provide for
atlas txn protocol to work

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 12]
```diff
@@ -0,0 +1,233 @@
...
+
+    private TimestampService createPaxosBackedTimestampService(String client) {
+        paxosResource.addClient(client);
+
+        ExecutorService executor = Executors.newCachedThreadPool(new ThreadFactoryBuilder()
+                .setNameFormat("atlas-consensus-" + client + "-%d")
+                .setDaemon(true)
+                .build());
+
+        List<PaxosAcceptor> acceptors = getNamespacedProxies(
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: `acceptors` and `learners` assignment is same as in `registerLeadershipElectionService` except for client instead of LEADER_NS.

File: atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml [hunk 13]
```diff
@@ -0,0 +1,12 @@
+algorithm:
+  type: paxos
+  paxosDataDir: var/test/data
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml]: Did you mean this to be a relative path?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java [hunk 14]
```diff
@@ -0,0 +1,74 @@
...
+
+import io.dropwizard.setup.Environment;
+
+@JsonSerialize(as = ImmutablePaxosConfiguration.class)
+@JsonDeserialize(as = ImmutablePaxosConfiguration.class)
+@Value.Immutable
+public abstract class PaxosConfiguration implements TimeLockAlgorithmConfiguration {
+    @Value.Default
+    public File paxosDataDir() {
+        return new File("var/data/paxos");
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: again, did we want a relative path here?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+
+    public abstract Optional<SslConfiguration> sslConfiguration();
+
+    @Value.Default
+    public long pingRateMs() {
+        return 5000L;
+    }
+
+    @Value.Default
+    public long randomWaitBeforeProposalMs() {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: (aside: reminds me of http://xkcd.com/221/)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+    }
+
+    @Value.Check
+    protected final void check() {
+        Preconditions.checkArgument(paxosDataDir().exists() || paxosDataDir().mkdirs(),
+                "Paxos data directory '%s' does not exist and cannot be created.", paxosDataDir());
+        Preconditions.checkArgument(pingRateMs() > 0,
+                "Ping rate must be positive; found '%s'.", pingRateMs());
+        Preconditions.checkArgument(randomWaitBeforeProposalMs() > 0,
+                "Random wait before proposal must be positive; found '%s'.", randomWaitBeforeProposalMs());
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: (this is just a note to remind me that if the variable name changes, so must the string)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResource.java [hunk 17]
```diff
@@ -0,0 +1,75 @@
...
+import com.google.common.base.Preconditions;
+import com.google.common.collect.Maps;
+import com.palantir.paxos.PaxosAcceptor;
+import com.palantir.paxos.PaxosAcceptorImpl;
+import com.palantir.paxos.PaxosLearner;
+import com.palantir.paxos.PaxosLearnerImpl;
+
+@Path("/{client: [a-zA-Z0-9_-]+}")
+public final class PaxosResource {
+    public static final String DEFAULT_LOG_DIRECTORY = "var/data/";
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResource.java]: relative path

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 18]
```diff
@@ -0,0 +1,233 @@
...
+import com.palantir.paxos.PaxosLearner;
+import com.palantir.paxos.PaxosProposer;
+import com.palantir.paxos.PaxosProposerImpl;
+import com.palantir.remoting.ssl.SslSocketFactories;
+import com.palantir.timestamp.PersistentTimestampService;
+import com.palantir.timestamp.TimestampService;
+
+import io.dropwizard.setup.Environment;
+
+public class PaxosServerImplementation implements ServerImplementation {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: `ServerImplementation` is a weak name, too, especially for an interface! I'd go with `PaxosTimelockServer implements TimelockServer`.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 19]
```diff
@@ -0,0 +1,233 @@
...
+    public static final String LEADER_NAMESPACE = "__leader";
+
+    private final PaxosConfiguration paxosConfiguration;
+    private final Environment environment;
+
+    private Set<String> remoteServers;
+    private Optional<SSLSocketFactory> optionalSecurity = Optional.absent();
+
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: nit: this newline is slightly random.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 18 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Although you already have something else called `TimeLockServer`. Hmm. We need to think about this.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 20]
```diff
@@ -0,0 +1,233 @@
...
+        PaxosProposer proposer = PaxosProposerImpl.newProposer(
+                paxosResource.getPaxosLearner(LEADER_NAMESPACE),
+                ImmutableList.copyOf(acceptors),
+                ImmutableList.copyOf(learners),
+                getQuorumSize(configuration),
+                executor);
+
+        // Build and store a gatekeeping leader election service
+        leaderElectionService = new PaxosLeaderElectionService(
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: This is a long list of constructor arguments to have to keep in the right order. Consider adding a builder.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 21]
```diff
@@ -0,0 +1,233 @@
...
+                proposer,
+                paxosResource.getPaxosLearner(LEADER_NAMESPACE),
+                otherLeaders,
+                ImmutableList.copyOf(acceptors),
+                ImmutableList.copyOf(learners),
+                executor,
+                paxosConfiguration.pingRateMs(),
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: this uses most of `PaxosConfiguration`. At this point you might as well pass in the configuration as a separate argument.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 22]
```diff
@@ -0,0 +1,233 @@
...
+    }
+
+    @Override
+    public void onStop() {
+        // Nothing to do
+    }
+
+    @Override
+    public void onStartupFailure() {
+        // Nothing
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: not even a message? Where is this called?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 23]
```diff
@@ -0,0 +1,233 @@
...
+    }
+
+    private void registerPaxosResource() {
+        paxosResource = PaxosResource.create(paxosConfiguration.paxosDataDir().toString());
+        paxosResource.addClient(LEADER_NAMESPACE);
+        environment.jersey().register(paxosResource);
+    }
+
+    private void registerLeaderElectionService(TimeLockServerConfiguration configuration) {
+        remoteServers = getRemotePaths(configuration);
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: A lot of code is reused in the `createPaxosBackedTimestampService` method below, too.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 9 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Sounds like a set of unit tests waiting to happen :-)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 24]
```diff
@@ -0,0 +1,233 @@
...
+                        new PaxosTimestampBoundStore(
+                                proposer,
+                                paxosResource.getPaxosLearner(client),
+                                ImmutableList.copyOf(acceptors),
+                                ImmutableList.copyOf(learners),
+                                paxosConfiguration.randomWaitBeforeProposalMs())),
+                leaderElectionService);
+    }
+
+    private static Set<String> getRemoteAddresses(TimeLockServerConfiguration configuration) {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Consider if `getRemoteServers` or `getRemoteServerAddresses` would be better here.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 25]
```diff
@@ -0,0 +1,233 @@
...
+        return Sets.difference(configuration.cluster().servers(),
+                ImmutableSet.of(configuration.cluster().localServer()));
+    }
+
+    private Set<String> getRemotePaths(TimeLockServerConfiguration configuration) {
+        String protocolPrefix = paxosConfiguration.sslConfiguration().isPresent()
+                ? "https://" : "http://";
+        return getRemoteAddresses(configuration).stream()
+                .map(address -> protocolPrefix + address)
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: is the address guaranteed not to include `http(s)://`?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 11 above)
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: There is already a (brief) javadoc in `TimestampBoundStore`, but I would be happy to see more detail added (also not blocking).

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 26]
```diff
@@ -0,0 +1,214 @@
...
+        this.acceptors = acceptors;
+        this.learners = learners;
+        this.randomWaitBeforeProposalMs = randomWaitBeforeProposalMs;
+    }
+
+    @Override
+    public synchronized long getUpperLimit() {
+        List<PaxosLong> responses = PaxosQuorumChecker.collectQuorumResponses(
+                ImmutableList.copyOf(acceptors),
+                a -> ImmutablePaxosLong.of(a.getLatestSequencePreparedOrAccepted()),
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Does checkstyle not complain about this (one-char variable)?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 27]
```diff
@@ -0,0 +1,214 @@
...
+        this.proposer = proposer;
+        this.knowledge = knowledge;
+        this.acceptors = acceptors;
+        this.learners = learners;
+        this.randomWaitBeforeProposalMs = randomWaitBeforeProposalMs;
+    }
+
+    @Override
+    public synchronized long getUpperLimit() {
+        List<PaxosLong> responses = PaxosQuorumChecker.collectQuorumResponses(
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: this and the check could be split into a method called `getLatest(WhateverThisIs*)FromAcceptors`

* - are we fetching the sequence number of associated value?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 28]
```diff
@@ -0,0 +1,214 @@
...
+                true);
+        if (!PaxosQuorumChecker.hasQuorum(responses, proposer.getQuorumSize())) {
+            throw new ServiceNotAvailableException("could not get a quorum");
+        }
+        PaxosLong max = Ordering.natural().onResultOf(PaxosLong::getValue).max(responses);
+        agreedState = getAgreedState(max.getValue());
+        return agreedState.getBound();
+    }
+
+    @VisibleForTesting
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: This class is pretty long, and there is clearly testable behaviour here. I lack syntax highlighting here, but perhaps we can pull out a class (or classes) with public (maybe static?) methods that we can test.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 29]
```diff
@@ -0,0 +1,214 @@
...
+
+        Optional<SequenceAndBound> state = getLearnedState(seq);
+        if (state.isPresent()) {
+            return state.get();
+        }
+
+        while (true) {
+            try {
+                byte[] value = proposer.propose(seq, oldState == null ? null : PtBytes.toBytes(oldState));
+                // propose must never be null.  We only pass in null for things we know are agreed upon already.
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: propose --> value? `proposedValue`?

Comment (gsheasby) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: propose --> value? proposedValue

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 1 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Sure, changed.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 3 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Hmm, did you mean on the next test? This one should stay as it is I think (since there are two tokens), but the next method has a single token that's named `token1`

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 2 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: This specific directory will only be created when the server processes the test config, so it won't be created in prod.

I'll switch to `@TemporaryFolder` though.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 4 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: Unfortunately we don't have a way of reading the timestamp bound easily. We still do cache timestamps but as @harrybiddle has pointed out in the 1 node case (or, actually, as long as you have a consistent leader throughout) this behaviour is safe.

However, I would _not_ include this as a test in say, an abstract integration test for TimeLockServer implementations, since it's kind of specific to this implementation (if you think about it, maintaining a single timestamp service for everyone would satisfy the timestamp service contract).

Changed to use `Assert.assertEquals` (that said, the original AssertJ one I wrote is the wrong way round in terms of expected/actual).

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java (hunk 5 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: Sure, touched the endpoints a little.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java (hunk 6 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: The endpoints aren't actually exposed (we don't actually listen on the port) so I'm not sure what you mean here. I think the integration test does cover this case (`returnsNotFoundOnQueryingNonexistentClient`) already.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementationTest.java [hunk 30]
```diff
@@ -0,0 +1,79 @@
...
+import com.palantir.atlasdb.timelock.config.ImmutableClusterConfiguration;
+import com.palantir.atlasdb.timelock.config.ImmutablePaxosConfiguration;
+import com.palantir.atlasdb.timelock.config.TimeLockServerConfiguration;
+import com.palantir.leader.LeaderElectionService;
+
+import io.dropwizard.jersey.setup.JerseyEnvironment;
+import io.dropwizard.setup.Environment;
+
+public class PaxosServerImplementationTest {
+    private static final File TEST_DATA_DIRECTORY = new File("testLogs/");
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementationTest.java]: relative, in case you're going through and fixing these.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 31]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    @Test
+    public void canStoreUpperLimit() {
+        store.storeUpperLimit(TIMESTAMP_1);
+        assertThat(store.getUpperLimit()).isGreaterThanOrEqualTo(TIMESTAMP_1);
+    }
+
+    @Test
+    public void throwsIfStoringLimitLesserThanUpperLimit() {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: nit: `LessThan`

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 32]
```diff
@@ -0,0 +1,280 @@
...
+    public void throwsIfCannotObtainQuorum() {
+        failureToggles.get(1).set(true);
+        failureToggles.get(2).set(true);
+        failureToggles.get(3).set(true);
+        assertThatThrownBy(() -> store.getUpperLimit()).isInstanceOf(ServiceNotAvailableException.class);
+    }
+
+    @Test
+    public void retriesProposeUntilSuccessful() throws Exception {
+        store = createOnceFailingPaxosTimestampBoundStore(0);
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: is there some way we can check that we tried more than once here?

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 33]
```diff
@@ -0,0 +1,280 @@
...
+    @Test
+    public void throwsIfBoundUnexpectedlyChangedUnderUs() {
+        PaxosTimestampBoundStore additionalStore = createPaxosTimestampBoundStore(1);
+        additionalStore.storeUpperLimit(TIMESTAMP_1);
+        assertThatThrownBy(() -> store.storeUpperLimit(TIMESTAMP_2))
+                .isInstanceOf(MultipleRunningTimestampServiceError.class);
+    }
+
+    @Test
+    public void canReadStateFromDistributedLogs() {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: So you can have multiple servers running, as long as they refresh state and don't get out of sync? Neat.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 34]
```diff
@@ -0,0 +1,280 @@
...
+        PaxosTimestampBoundStore additionalStore = createPaxosTimestampBoundStore(1);
+        additionalStore.storeUpperLimit(TIMESTAMP_1);
+        assertThat(store.getUpperLimit()).isGreaterThanOrEqualTo(TIMESTAMP_1);
+        store.storeUpperLimit(TIMESTAMP_2);
+        assertThat(store.getUpperLimit()).isGreaterThanOrEqualTo(TIMESTAMP_2);
+    }
+
+    @Test
+    public void canReadStateThroughLeaderChanges() {
+        PaxosTimestampBoundStore additionalStore1 = createPaxosTimestampBoundStore(1);
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: What do `1` and `0` mean here? And how is the leader change initiated?

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 35]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    @Test
+    public void canSafelyGetAgreedStateFromPrehistory() {
+        assertThat(store.getAgreedState(Long.MIN_VALUE).getBound()).isEqualTo(0);
+    }
+
+    @Test
+    public void canGetAgreedStateAfterNodeDown() {
+        failureToggles.get(1).set(true);
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: seems a bit brittle - how does `store` relate to `1`?

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 36]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    @Test
+    public void cannotGetAgreedStateFromTheFuture() {
+        assertThatThrownBy(() -> store.getAgreedState(Long.MAX_VALUE))
+                .isInstanceOf(NullPointerException.class);
+    }
+
+    @Test
+    public void canSafelyForceAgreedStateFromPrehistory() {
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: can you do this from the present? What about the near future?

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 37]
```diff
@@ -0,0 +1,280 @@
...
+        assertThat(store.forceAgreedState(Long.MIN_VALUE, Long.MIN_VALUE).getBound()).isEqualTo(0);
+    }
+
+    @Test
+    public void retriesForceAgreedStateUntilSuccessful() throws Exception {
+        store = createOnceFailingPaxosTimestampBoundStore(0);
+        store.forceAgreedState(1, TIMESTAMP_1);
+        assertThat(store.getUpperLimit()).isGreaterThanOrEqualTo(TIMESTAMP_1);
```
Comment (gsheasby) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: Again, some metric of "we tried twice before succeeding" might be useful here.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java (hunk 15 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: @harrybiddle your understanding is right (this is done in PaxosTimestampBoundStore::getRandomBackoffTime). Post offline discussion I'll rename this to `maximumWaitBeforeProposalMs()`

Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: I grabbed the name from the old `leader-election-impl`, but it can be a little confusing, yes.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfigurationTest.java (hunk 7 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfigurationTest.java]: Good spot, changed.

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 8 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: I'll mark this as a TODO and get back to this later. Agree with @gsheasby that this should be a small number of tests which verify we can use SSL if the config says so.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 9 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: The acceptors.size() should always be equal to the number of servers in the cluster, as far as our impl is concerned (even if localhost; you talk to yourself as well). In the one-node case, you have `1/2 + 1 = 1` which is fine, and we do still construct a one-node Paxos, though we pretty much immediately declare ourselves the leader.

I've refactored this to `getQuorumSize()` and added a bunch of unit tests.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 10 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay. I ported these over without changing them, sorry about that.

`1` here is the minimum quorum size. Since we're talking only to the learners, this is fine, because Paxos guarantees that values that are learned have safely been agreed upon (rather, no 2 learners will learn different values for the same log entry).

The `true` is used by the quorum checker to log failures e.g. `ConnectException`s etc. only if it fails to reach a quorum.

I've renamed these to `QUORUM_OF_ONE` and `ONLY_LOG_ON_QUORUM_FAILURE`, respectively.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 11 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Agree that this would be a good idea. Looking at later comments we might refactor this out, so I'll leave this as a TODO to be settled at the end.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 18 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: A little verbose, but `PaxosTimeLockServerImplementation implements TimeLockServerImplementation` is certainly an option.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 38]
```diff
@@ -0,0 +1,233 @@
...
+import com.palantir.paxos.PaxosProposer;
+import com.palantir.paxos.PaxosProposerImpl;
+import com.palantir.remoting.ssl.SslSocketFactories;
+import com.palantir.timestamp.PersistentTimestampService;
+import com.palantir.timestamp.TimestampService;
+
+import io.dropwizard.setup.Environment;
+
+public class PaxosServerImplementation implements ServerImplementation {
+    public static final String LEADER_NAMESPACE = "__leader";
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: This is probably Paxos specific (though unfortunately the rule about clients needs to be a general rule). There are a bunch of useful constants that could be refactored out though so I'll probably make a `PaxosTimeLockConstants`.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java [hunk 39]
```diff
@@ -0,0 +1,233 @@
...
+    public PaxosServerImplementation(PaxosConfiguration configuration, Environment environment) {
+        this.paxosConfiguration = configuration;
+        this.environment = environment;
+    }
+
+    @Override
+    public void onStartup(TimeLockServerConfiguration configuration) {
+        registerPaxosResource();
+
+        if (paxosConfiguration.sslConfiguration().isPresent()) {
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Good call. Amazingly this simplifies the code a lot (because of Guava's `transform()`) as well!

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 20 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: (I tried to refrain from touching the leader election classes at all. I guess it's time to dig in!)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 23 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: The other key difference is the `Environment` used in `LeaderElectionService`'s `create()` is not the same as the `Environment` we use. I think it's feasible - some refactoring required though. Looking in to it now.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 12 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: It is. I'm going to divide the existing impl of `Leaders.create()` into several smaller pieces, so that we can reuse bits of it.

File: atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml (hunk 13 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml]: (Has been replaced with a placeholder because I switched to using `@TemporaryFolder`. But isn't this a relative path itself?)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java (hunk 14 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java]: A little confused - isn't this path relative to the working directory in which the timelock server runs?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResource.java (hunk 17 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResource.java]: (would that be `"./var/data/"`? Sorry, not sure I understand this - I thought this is already relative to the directory in which TimeLock runs)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 19 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Removed; I don't remember why it was there.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 20 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: (Leader creation's now all in the `Leaders` class. I'll leave this as a TODO for later on to refactor the existing code.)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 21 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: (I took @hsaraogi's suggestion of using the existing `LeaderConfig` class, building one of those from our config.)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 22 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: This is called in `TimeLockServer`, when startup throws an exception. This would be important if we create additional external services. (This was put in to address #1282; that issue would also apply to Timelock failing whilst starting up).

For Paxos we don't have any "other" services that need to be shut down, in that sense, so there is no work here. I've given the `onStop()` and `onStartupFailure()` no-op defaults in `TimeLockServerImplementation`, and removed these empty impls.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 24 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: `getRemoteServerAddresses` is probably the most descriptive, so I've renamed it to that.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 25 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Yes. `ClusterConfiguration::checkHostPortString` verifies that the server addresses are of the form `host:port` (there's also a test that checks this specific case, that `http://foo:bar` gets rejected).

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java [hunk 40]
```diff
@@ -0,0 +1,129 @@
...
+import static org.mockito.Mockito.when;
+
+import java.io.File;
+
+import org.junit.Test;
+
+public class PaxosConfigurationTest {
+    private static final long POSITIVE_LONG = 100L;
+    private static final long ZERO_LONG = 0L;
+    private static final long NEGATIVE_LONG = -100L;
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java]: Okay, removed the 0 case.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java [hunk 41]
```diff
@@ -0,0 +1,76 @@
...
+import java.io.IOException;
+import java.nio.file.Paths;
+
+import org.apache.commons.io.FileUtils;
+import org.junit.After;
+import org.junit.Before;
+import org.junit.Test;
+
+public class PaxosResourceTest {
+    private static final String LOG_DIR = "testLogs/";
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: Done without seeing this comment, when I refactored the `PaxosResourceTest` earlier. :)

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java [hunk 42]
```diff
@@ -0,0 +1,76 @@
...
+
+    private static final String CLIENT_1 = "andrew";
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: The choice of `bob` for client 2 was pretty random (a name starting with B) actually, I wasn't thinking along these lines at all :)

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementationTest.java (hunk 30 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementationTest.java]: (as above, I thought this is relative to the working directory?)

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 31 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: OK, changed.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 33 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: Yep, that's right - the triggering condition for MRTSE is actually when you try to update the bound and your own bound is not synced up.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 34 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: `1` and `0` refer to the IDs of the Paxos proposer that makes the proposals for the timestamp bound store that was created. The "leader change" here admittedly is implicit (because we maintain only one active Paxos proposer at a time); if you're doing `storeUpperBound(...)` without a `get()` before it, you would have to be the leader.

I should probably reword this since the concept of leadership doesn't really exist at this level of abstraction.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 36 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: You *can*, though it's semantically awkward for Paxos. `Force(seq, num)` basically behaves as follows:

* If consensus for `seq` is already known by any learner, return it
* Otherwise, have the proposer propose `num`.
* The proposer will return a value that a quorum agreed on (maybe `num`, maybe not).
* We return this value.

If `num` is null (this is a signal that we want to find out a value, as opposed to setting it) and the cluster hasn't agreed on a value, we fail. Using null for `num` is typically done only if learner state is lost.

Multi-Paxos allows there to be gaps in state as far as an individual node is concerned (though that's from my understanding of the algorithm, not about our specific impl), so there's nothing _wrong_ with this behaviour in theory.

I've beefed up the tests for force(), in any case.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 32 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: This sounds like a use case for a spy, so yes.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 37 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: As above, added spy-based test.

**Comment by jeremyk-91** [comment]
State of the world (Friday evening):

* I've responded to comments from all of the reviews, except those that touch `PaxosTimestampBoundStore`.
* I'm tracking three `TODO` items in the overall summary.
* On Monday, I plan to start drilling through `PaxosTimestampBoundStore`. I'll then proceed to the TODOs as time permits.

@hsaraogi I've shifted all the leadership resources to be housed under their own `LeadershipResource`, so the inconsistent namespacing for the ping/uuid endpoints has been fixed. I've also extended the integration test to check that you can have clients called `leader`, `learner` and `acceptor`, for safety.

@carrino Thanks for the reminder. As you say, failover makes describing it as monotonic not quite right, since (A makes request to leader, another server becomes leader, B makes request to new leader, B receives 1000001, A receives 1) is allowed. I'll make sure to keep this in mind especially when writing the docs for this.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 29 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay, renamed to `acceptedValue` (`propose()` for a given sequence number and value will try and propose that value, but it could return another value if there's already something accepted for that sequence number). We rely on this being known by a quorum of the nodes from here on out, so I think this is clearer.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 43]
```diff
@@ -0,0 +1,214 @@
...
+                Preconditions.checkNotNull(value, "Proposed value can't be null, but was in sequence %s", seq);
+                return ImmutableSequenceAndBound.of(seq, PtBytes.toLong(value));
+            } catch (PaxosRoundFailureException e) {
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Yes, that's thrown by the `PaxosProposerImpl` if it can't get a quorum (see javadocs of its `phaseOne()` and `phaseTwo()` methods).

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 44]
```diff
@@ -0,0 +1,214 @@
...
+        }
+    }
+
+    private Optional<SequenceAndBound> getLearnedState(long seq) {
+        if (seq <= PaxosAcceptor.NO_LOG_ENTRY) {
+            return Optional.of(ImmutableSequenceAndBound.of(PaxosAcceptor.NO_LOG_ENTRY, 0L));
+        }
+        List<PaxosLong> responses = PaxosQuorumChecker.collectQuorumResponses(
+                ImmutableList.copyOf(learners),
+                l -> getLearnedValue(seq, l),
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Right, updated to `learner`

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 45]
```diff
@@ -0,0 +1,214 @@
...
+        PaxosValue value = learner.getLearnedValue(seq);
+        if (value == null) {
+            throw new NoSuchElementException();
+        }
+        return ImmutablePaxosLong.of(PtBytes.toLong(value.getData()));
+    }
+
+    @Override
+    public synchronized void storeUpperLimit(long limit) throws MultipleRunningTimestampServiceError {
+        Preconditions.checkArgument(agreedState == null || limit >= agreedState.getBound());
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay. I've refactored this bit a little - we initialize `newSeq` to 0 first, and then if the agreed state isn't null we check `limit >= agreedState.getBound()`, throwing with `Tried to store an upper limit %s less than the current limit %s` if that fails, and then set `newSeq = agreedState.getSeqId() + 1` if needed.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 46]
```diff
@@ -0,0 +1,214 @@
...
+        if (responses.isEmpty()) {
+            return Optional.empty();
+        }
+        return Optional.of(ImmutableSequenceAndBound.of(seq, responses.iterator().next().getValue()));
+    }
+
+    private static PaxosLong getLearnedValue(long seq, PaxosLearner learner) {
+        PaxosValue value = learner.getLearnedValue(seq);
+        if (value == null) {
+            throw new NoSuchElementException();
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay, added `Tried to get a learned value for sequence number '%d' which didn't exist`. Unfortunately there doesn't seem to be an easy way to, from just the PaxosLearner itself, identify where this happened.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 47]
```diff
@@ -0,0 +1,214 @@
...
+                if (!value.getLeaderUUID().equals(proposer.getUUID())) {
+                    throw new MultipleRunningTimestampServiceError("concurrent proposal: " + value);
+                }
+                long newLimit = PtBytes.toLong(value.getData());
+                agreedState = ImmutableSequenceAndBound.of(newSeq, newLimit);
+                if (newLimit >= limit) {
+                    return;
+                }
+            } catch (PaxosRoundFailureException e) {
+                log.info("failed during propose", e);
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: How does `Paxos proposal couldn't complete, because we could not connect to a quorum of nodes. We will retry in {}ms` sound? Agree that without familiarity with the code/paxos it looks concerning.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 48]
```diff
@@ -0,0 +1,214 @@
...
+    @Override
+    public synchronized void storeUpperLimit(long limit) throws MultipleRunningTimestampServiceError {
+        Preconditions.checkArgument(agreedState == null || limit >= agreedState.getBound());
+        long newSeq = agreedState == null ? 0 : agreedState.getSeqId() + 1;
+        while (true) {
+            try {
+                proposer.propose(newSeq, PtBytes.toBytes(limit));
+                PaxosValue value = knowledge.getLearnedValue(newSeq);
+                if (!value.getLeaderUUID().equals(proposer.getUUID())) {
+                    throw new MultipleRunningTimestampServiceError("concurrent proposal: " + value);
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay. Actually the PaxosValue has quite a lot of information, the only additional info that I think we have here is our UUID and the value we tried to propose. I've added that, cleaned this up a fair bit, in any case, and made it more readable.

```java
String errorMsg = String.format(
        "Timestamp limit changed from under us for sequence '%s' (leader with UUID '%s' changed"
        + " it, our UUID is '%s'). This suggests that another timestamp store for this"
        + " namespace is running. The offending bound was '%s'; we tried to propose"
        + " a bound of '%s'. (The offending Paxos value was '%s'.)",
        newSeq,
        value.getLeaderUUID(),
        proposer.getUUID(),
        PtBytes.toLong(value.getData()),
        limit,
        value);
```

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 49]
```diff
@@ -0,0 +1,324 @@
...
+        long fortyThree = FORTY_TWO + 1;
+        assertThat(store.forceAgreedState(1, FORTY_TWO)).isEqualTo(ONE_AND_FORTY_TWO);
+        assertThat(store.forceAgreedState(0, fortyThree)).isEqualTo(ImmutableSequenceAndBound.of(0, fortyThree));
+        assertThat(store.getAgreedState(0)).isEqualTo(ImmutableSequenceAndBound.of(0, fortyThree));
+        assertThat(store.getAgreedState(1)).isEqualTo(ONE_AND_FORTY_TWO);
+    }
+
+    @Test
+    public void forceAgreedStateThrowsIfNoStateWasAgreedUpon() {
+        assertThatThrownBy(() -> store.forceAgreedState(1, null)).isInstanceOf(NullPointerException.class);
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: Should we rely on the NPE here or throw an IllegalStateException using `Preconditions.checkstate()`?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 27 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: updated - there's a new `getLatestSequenceNumbersFromAcceptors()` that handles this part only.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java [hunk 50]
```diff
@@ -0,0 +1,108 @@
...
+    }
+
+    @Test
+    public void canCreateDirectoryForPaxosDirectory() {
+        File mockFile = mock(File.class);
+        when(mockFile.exists()).thenReturn(false);
+        when(mockFile.mkdirs()).thenReturn(true);
+        ImmutablePaxosConfiguration.builder()
+                .paxosDataDir(mockFile)
+                .build();
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java]: verify mkdirs is called exactly once.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java [hunk 51]
```diff
@@ -0,0 +1,108 @@
...
+    }
+
+    @Test
+    public void canUseExistingDirectoryAsPaxosDirectory() {
+        File mockFile = mock(File.class);
+        when(mockFile.exists()).thenReturn(true);
+        when(mockFile.mkdirs()).thenReturn(false);
+        ImmutablePaxosConfiguration.builder()
+                .paxosDataDir(mockFile)
+                .build();
```
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java]: verify mkdirs is never called.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 18 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: 👍

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 52]
```diff
@@ -0,0 +1,214 @@
...
+        }
+        return ImmutablePaxosLong.of(PtBytes.toLong(value.getData()));
+    }
+
+    @Override
+    public synchronized void storeUpperLimit(long limit) throws MultipleRunningTimestampServiceError {
+        Preconditions.checkArgument(agreedState == null || limit >= agreedState.getBound());
+        long newSeq = agreedState == null ? 0 : agreedState.getSeqId() + 1;
+        while (true) {
+            try {
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: (Done; took out the waiting/retry logic into one, and the MRTSE part into `checkAgreedBoundIsOurs()`)

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java (hunk 26 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Hmm, it didn't. I think it's not supported yet; there's an [issue](https://github.com/checkstyle/checkstyle/issues/3009) on this.

Anyway changed to `acceptor`, which is clearer.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 53]
```diff
@@ -0,0 +1,247 @@
...
+    }
+
+    private List<PaxosLong> getLatestSequenceNumbersFromAcceptors() {
+        List<PaxosLong> responses = PaxosQuorumChecker.collectQuorumResponses(
+                ImmutableList.copyOf(acceptors),
+                acceptor -> ImmutablePaxosLong.of(acceptor.getLatestSequencePreparedOrAccepted()),
+                proposer.getQuorumSize(),
+                executor,
+                PaxosQuorumChecker.DEFAULT_REMOTE_REQUESTS_TIMEOUT_IN_SECONDS,
+                true);
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Yes, good spot.

**Comment by gsheasby** [comment]
Reviewed 9 of 28 files at r1, 31 of 32 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 34 unresolved discussions, some commit checks failed.

---

*[atlasdb-jepsen-tests/src/integTest/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckerIntegrationTest.java, line 53 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabMUKtOrWd5bNZ1Ri2:-KabMUKuySR42t5zb3zs:b-j7oy71) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-jepsen-tests/src/integTest/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckerIntegrationTest.java#L53)):*
> ```Java
>         List<Map<Keyword, ?>> convertedAllEvents = getClojureMapFromFile("liveness_failing_history.json");
> 
>         Map<Keyword, Object> results = JepsenHistoryCheckers.createWithCheckers(
> ```

Are we no longer using the other timestamp checkers?

---

*[atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java, line 16 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabNCGUfotJoW_cdyaz:-KabNCGVPpukoRlLUyAk:bhkshvb) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java#L16)):*
> ```Java
>  * limitations under the License.
>  */
> package com.palantir.atlasdb.timelock;
> ```

This seems rather more general than just for timelock. Have you considered moving it to one of the commons/utils projects?

---

*[atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml, line 3 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4uvahXPUnFRjsB-r5-3:-KabNsQ4OQ5fX2Dnf8ha:bcaxmta) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/integTest/resources/paxosSingleServer.yml#L3)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

(Has been replaced with a placeholder because I switched to using `@TemporaryFolder`. But isn't this a relative path itself?)
</blockquote></details>

Not as relevant with `@TemporaryFolder`, because it gets auto-deleted (so you don't care where it is).

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabOA1ij8VhV4TqIU_0:-KabOA1jKN-dEWOk1JEz:b-cs9ytd) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java#L20)):*
> ```Java
> import com.palantir.atlasdb.timelock.config.TimeLockServerConfiguration;
> 
> public interface TimeLockServerImplementation {
> ```

It still feels odd to me that an interface has `Implementation` in the name - but then, I think you use `TimeLockServer` elsewhere?

Naming is hard =(

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java, line 49 at r1](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5p-r1-49:-KabOldBO_lJEWVVLCok:bu677c1) ([raw file](https://github.com/palantir/atlasdb/blob/a9b450e52f0d947571b1afcd5ef7d83c96c0b79d/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java#L49)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

I grabbed the name from the old `leader-election-impl`, but it can be a little confusing, yes.
</blockquote></details>

I like this name!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java, line 38 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5p-r5-38:-KabOUxcCK8FkWzk2yvv:b-ahu0ar) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java#L38)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

A little confused - isn't this path relative to the working directory in which the timelock server runs?
</blockquote></details>

I guess it could be; `var/data` just looks to me like it should be an absolute path, because `/var` is one of the default folders in Unix systems. (Satisfied now)

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabPAnJCY0VMSDNgAn0:-KabPAnJCY0VMSDNgAn1:b-7yvo8c) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L20)):*
> ```Java
> public final class PaxosTimeLockConstants {
>     public static final String DEFAULT_LOG_DIRECTORY = "var/data/";
>     public static final String LEARNER_PATH = "/learner";
> ```

These are duplicated in `LeadershipResource`. Can we eliminate this duplication?

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 123 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-123:-KabPtOXacD56XRw0Swu:b-81nlyp) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L123)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Okay, renamed to `acceptedValue` (`propose()` for a given sequence number and value will try and propose that value, but it could return another value if there's already something accepted for that sequence number). We rely on this being known by a quorum of the nodes from here on out, so I think this is clearer.
</blockquote></details>

SGTM!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 126 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-126:-KabQ-YmBwEH28yMAY6p:b-1ugqoo) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L126)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Yes, that's thrown by the `PaxosProposerImpl` if it can't get a quorum (see javadocs of its `phaseOne()` and `phaseTwo()` methods).
</blockquote></details>

Ack. I'm not a fan, but this is definitely not the time for that particular refactor.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 151 at r7](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabWxBTIvb3WYiA3BBC:-KabWxBTIvb3WYiA3BBD:bhz3lr7) ([raw file](https://github.com/palantir/atlasdb/blob/4c2e7080ed7c3a8e67fe0b6bfee1f0953e1bcc3f/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L151)):*
> ```Java
>     /**
>      * Forces agreement to be reached for a given sequence number; if the cluster hasn't reached agreement yet,
>      * attempt to propose a given value. This method only returns when a value has been agreed upon for the provided
> ```

There's a slight change of tense here - looks like `attempt` --> `attempts` would fix it.

---

*[atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java, line 141 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp61-r5-141:-KabSlxHp3GuABWeK2-h:b-83sjoh) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java#L141)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

This sounds like a use case for a spy, so yes.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java [hunk 54]
```diff
@@ -0,0 +1,324 @@
...
+            ImmutableSequenceAndBound.of(1, FORTY_TWO);
+
+    private static final String STILL_RUNNING_MESSAGE =
+            "Some threads are still hanging around! Can't proceed or they might corrupt future tests.";
+    private static final RuntimeException EXCEPTION = new RuntimeException("exception");
+
+    private final ExecutorService executor = PTExecutors.newCachedThreadPool();
+    private final List<PaxosAcceptor> acceptors = Lists.newArrayList();
+    private final List<PaxosLearner> learners = Lists.newArrayList();
+    private final List<AtomicBoolean> failureToggles = Lists.newArrayList();
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: Each `ToggleableExceptionProxy` has a reference to an AtomicBoolean, which determines whether to throw an exception or to send the method call through to the real method. See `ToggleableExceptionProxy#invoke()` for how it works.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 23 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Looks good now

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java (hunk 50 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java]: Ack, added check for this.

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java (hunk 51 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java]: Nice, agree that's a better check! (Rather than only refusing to create the directory, which is what I did)

File: atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java (hunk 3 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java]: oh, yes. 👍

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java (hunk 5 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourceTest.java]: Looks good!

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 49 above)
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: Hmm, the original code actually has an explicit `Preconditions.checkNotNull()` to throw this. The docs of NPE say that "Applications should throw instances of this class to indicate other illegal uses of the null object". I'm quite neutral on this (calling force with a null when it isn't agreed is an illegal use, so I think NPE is okay) - what do you think?

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java (hunk 12 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java]: Thanks for doing that. I know we wanted to not touch some pieces of the code, but these piece of refactoring seems valuable. We could probably have a separate refactor PR if this seems to add complexity to the current PR.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 55]
```diff
@@ -0,0 +1,247 @@
...
+                ImmutableList.copyOf(learners),
+                learner -> getLearnedValue(seq, learner),
+                QUORUM_OF_ONE,
+                executor,
+                PaxosQuorumChecker.DEFAULT_REMOTE_REQUESTS_TIMEOUT_IN_SECONDS,
+                ONLY_LOG_ON_QUORUM_FAILURE);
+        if (responses.isEmpty()) {
+            return Optional.empty();
+        }
+        return Optional.of(ImmutableSequenceAndBound.of(seq, responses.iterator().next().getValue()));
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: `Iterables.getFirst()` requires a default value, though. This pattern is actually recommended from the docs for `Iterables`:

```
   * If no default value is desired (and the caller instead wants a
   * {@link NoSuchElementException} to be thrown), it is recommended that
   * {@code iterable.iterator().next()} is used instead.
```

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 54 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: ohh, I see now. This is some dope stuff.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 56]
```diff
@@ -0,0 +1,286 @@
...
+    interface SequenceAndBound {
+        @Value.Parameter
+        long getSeqId();
+
+        @Value.Parameter
+        long getBound();
+    }
+
+    private interface BackoffAction {
+        void accept(long backoffTime) throws InterruptedException;
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: Okay. We do need the interface because the retry methods throw a checked exception; there isn't direct support for this, it seems, and [solutions](http://stackoverflow.com/questions/27644361/how-can-i-throw-checked-exceptions-from-inside-java-8-streams) generally involve defining one's own functional interfaces.

I used `accept` for consistency with Java's `Consumer` which is what this class is essentially supposed to be (if not for the `InterruptedException` I would have just used a `Consumer<Long>`. That said I agree that overloading the paxos terminology can quickly get confusing, so I've renamed the method to `backoff`.

File: atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java [hunk 57]
```diff
@@ -0,0 +1,214 @@
...
+                    wait(backoffTime);
+                } catch (InterruptedException e1) {
+                    Thread.currentThread().interrupt();
+                }
+            }
+        }
+    }
+
+    private long getRandomBackoffTime() {
+        return (long) (randomWaitBeforeProposalMs * Math.random());
```
Comment (jeremyk-91) [inline atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java]: minimum = 1 is fine for now, I think. Since `Math.random()` can't actually return 1, as you say the maximum is still respected, so I've just added 1.

**Comment by jeremyk-91** [comment]
Review status: 31 of 34 files reviewed at latest revision, 33 unresolved discussions, some commit checks failed.

---

*[atlasdb-jepsen-tests/src/integTest/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckerIntegrationTest.java, line 53 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabMUKtOrWd5bNZ1Ri2:-KabhrdRj0lzISEqJNfC:bcjizbc) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-jepsen-tests/src/integTest/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckerIntegrationTest.java#L53)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Are we no longer using the other timestamp checkers?
</blockquote></details>

I think this was changed when @harrybiddle removed the liveness checker from the default timestamp checkers. We removed it from CI because none of our implementations can pass it reliably (though it's still a very useful tool for comparison/analysis).

I've put the other checkers back in too, in any case.

---

*[atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java, line 16 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabNCGUfotJoW_cdyaz:-KabkM5gS_YECdJ_xQ7-:b-ilkiuw) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java#L16)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

This seems rather more general than just for timelock. Have you considered moving it to one of the commons/utils projects?
</blockquote></details>

Note that from what we've seen from the leader-election-impl, depending on test classes seems to be quite a pain. I think having a separate atlasdb-test-commons or something like that would definitely be useful, though!

(I'd prefer to do this in a separate PR if that's okay, this one is already massive)

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabOA1ij8VhV4TqIU_0:-Kabgo23LTyK8c_ApwC1:bosh5h6) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java#L20)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

It still feels odd to me that an interface has `Implementation` in the name - but then, I think you use `TimeLockServer` elsewhere?

Naming is hard =(
</blockquote></details>

Yeah, `TimeLockServer` is the actual server class that sets up dropwizard related things, jersey endpoints, healthchecks etc. Maybe *that* could be renamed to `TimeLockServerLauncher` or something along those lines though?

@harrybiddle @hsaraogi your thoughts on renaming this interface to `TimeLockServer` and the thing that sets up the Dropwizard related things `TimeLockServerLauncher`?

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java, line 38 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5p-r5-38:-KabgXdika-TN2DXfjZl:bwadwrp) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java#L38)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

I guess it could be; `var/data` just looks to me like it should be an absolute path, because `/var` is one of the default folders in Unix systems. (Satisfied now)
</blockquote></details>

Ah, okay. Yeah... out of context it can look absolute. This is an unfortunate overlap with our internal convention here.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java, line 65 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5p-r5-65:-KabWxkJZef5ZVyYGv9o:bgepkjk) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/PaxosConfiguration.java#L65)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

(this is just a note to remind me that if the variable name changes, so must the string)
</blockquote></details>

(It has been changed!)

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabPAnJCY0VMSDNgAn0:-Kabj9WNg-Vx7p3dYHCu:b-66yo91) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L20)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

These are duplicated in `LeadershipResource`. Can we eliminate this duplication?
</blockquote></details>

I initially intended for these to be conceptually different things (the constant here is supposed to be the subdirectories within the filesystem where the paxos logs are stored, not the path of the sub-resource on the server), actually, so not sure we should merge it. I've renamed the constants to be clearer on this issue.

(kind of related: `LEADER_NAMESPACE` should definitely be deduplicated, though, since that *must* be the same).

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 91 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-91:-Kabk4wESOQJv6dLKp3j:b-cybsov) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L91)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

This class is pretty long, and there is clearly testable behaviour here. I lack syntax highlighting here, but perhaps we can pull out a class (or classes) with public (maybe static?) methods that we can test.
</blockquote></details>

Ack - marking as TODO. Some of the internal utils can be extracted.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 151 at r7](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabWxBTIvb3WYiA3BBC:-KabkF1fuFYSlaM57K5Q:bc6o35n) ([raw file](https://github.com/palantir/atlasdb/blob/4c2e7080ed7c3a8e67fe0b6bfee1f0953e1bcc3f/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L151)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

There's a slight change of tense here - looks like `attempt` --> `attempts` would fix it.
</blockquote></details>

Good catch. I tacked on the 2nd part later and forgot to check this!

---

*[atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java, line 89 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5y-r5-89:-KabgIM1eoyDuCk_o8mk:b-6feok5) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/PaxosConfigurationTest.java#L89)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

more names that'll need to change if `randomWaitBeforeProposalMs` changes.
</blockquote></details>

(Ack; it has been changed.)

---

*[leader-election-impl/build.gradle, line 21 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp63-r6-21:-Kabfi53AYypI_QCJQ-h:b-rf7kad) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/leader-election-impl/build.gradle#L21)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

You probably don't need `testArtifacts`.  `classifier:test` will help you depend on the test classes.
</blockquote></details>

Hmm, I get `Could not set unknown property 'classifier' for DefaultProjectDependency{dependencyProject='project ':leader-election-impl'', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.`. If I'm not wrong this [looks like it applies to external dependencies](https://docs.gradle.org/current/userguide/dependency_management.html)?

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java, line 56 at r3](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5t-r3-56:-KabdBdkBAu6CjaCySqa:be193m6) ([raw file](https://github.com/palantir/atlasdb/blob/7b7bb4c39f4d6763bed373a5a7af751f59c2b8f1/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java#L56)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

👍 
</blockquote></details>

(Just a confirmatory note - it has been changed to that.)

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java, line 92 at r3](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5t-r3-92:-KabdHxqcn652ClSt_-V:be17u8d) ([raw file](https://github.com/palantir/atlasdb/blob/7b7bb4c39f4d6763bed373a5a7af751f59c2b8f1/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java#L92)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

Looks good now
</blockquote></details>

Ack, thanks.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java, line 175 at r3](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5t-r3-175:-KabhesuS0-Bn7V9y2Y1:bu5babz) ([raw file](https://github.com/palantir/atlasdb/blob/7b7bb4c39f4d6763bed373a5a7af751f59c2b8f1/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosServerImplementation.java#L175)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

Thanks for doing that. I know we wanted to not touch some pieces of the code, but these piece of refactoring seems valuable. We could probably have a separate refactor PR if this seems to add complexity to the current PR.
</blockquote></details>

Yep. There's even more cleanup that can be done and possibly should be done in the future, but this is a good starting point I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

File: leader-election-impl/build.gradle [hunk 58]
```diff
@@ -11,3 +11,13 @@ dependencies {
...
   testCompile group: 'org.assertj', name: 'assertj-core'
 }
+
+configurations {
+    testArtifacts {
+       extendsFrom testRuntime
+    }
+}
+
+artifacts {
```
Comment (jeremyk-91) [inline leader-election-impl/build.gradle]: Copypaste from reviewable: 

Hmm, I get Could not set unknown property 'classifier' for DefaultProjectDependency{dependencyProject='project ':leader-election-impl'', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.. If I'm not wrong [this looks like it applies to external dependencies](https://docs.gradle.org/current/userguide/dependency_management.html)?

**Comment by jeremyk-91** [comment]
Review status: 25 of 34 files reviewed at latest revision, 31 unresolved discussions, some commit checks failed.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 91 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-91:-Kabs5S5mn9TDp3hiRUs:b-rdbap7) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L91)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Ack - marking as TODO. Some of the internal utils can be extracted.
</blockquote></details>

(Probably we could have a `PaxosStateManager` that publicly manages these internals. Statics would be quite messy as we'd have a lot to pass around. I find there are tests at two different levels of abstraction in the PaxosTBS test, so this should help resolve that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

File: atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java (hunk 49 above)
Comment (hsaraogi) [inline atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java]: cool, wouldnt push on this. checking NPE is fine. Thanks for pointing out the check already exists :)

File: leader-election-impl/build.gradle (hunk 58 above)
Comment (hsaraogi) [inline leader-election-impl/build.gradle]: oops, missed the comment, sorry for the double query.

**Comment by gsheasby** [comment]
Reviewed 1 of 32 files at r6, 1 of 3 files at r8, 8 of 8 files at r9.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java, line 16 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabNCGUfotJoW_cdyaz:-Kac4SPCSZ4J_g0LSbhY:b-61p01r) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java#L16)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Note that from what we've seen from the leader-election-impl, depending on test classes seems to be quite a pain. I think having a separate atlasdb-test-commons or something like that would definitely be useful, though!

(I'd prefer to do this in a separate PR if that's okay, this one is already massive)
</blockquote></details>

Yep, fine for this to go in a separate PR. Is there a "separate PR" laundry list somewhere?

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabOA1ij8VhV4TqIU_0:-Kac4Z_tTCu-zRCK8LGr:b-6w3psx) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java#L20)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Yeah, `TimeLockServer` is the actual server class that sets up dropwizard related things, jersey endpoints, healthchecks etc. Maybe *that* could be renamed to `TimeLockServerLauncher` or something along those lines though?

@harrybiddle @hsaraogi your thoughts on renaming this interface to `TimeLockServer` and the thing that sets up the Dropwizard related things `TimeLockServerLauncher`?
</blockquote></details>

That sounds good to me!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 91 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-91:-Kac28PqRgzNMEYiXqms:bc529hu) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L91)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

(Probably we could have a `PaxosStateManager` that publicly manages these internals. Statics would be quite messy as we'd have a lot to pass around. I find there are tests at two different levels of abstraction in the PaxosTBS test, so this should help resolve that.
</blockquote></details>

IMO it's best for this refactoring to go in as a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Up to date. Most of the "unresolved"s on reviewable are because Himangi/Harry commented and I didn't "dismiss" them.

Remaining for me:
- Fixing the naming (I like @jeremyk-91's suggestion of TimelockServerLauncher)
- A list of refactors that will happen after this PR
- SSL by default (is that a separate PR too?)

---

Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-:-Kac4rcQyO5FZa5yinEd:b-vhnlut)*

**Comment by jeremyk-91** [comment]
Immediately after this, I'll open tickets for refactors:

* Common test utils
* PaxosStateManager (we'll need to take out the SequenceAndBound and PaxosLong too)
* LeaderElectionService builder (we got round this with LeaderConfig's builder for now)

Remaining:

* SSL tests
* Rename the classes once everyone's happy

SSL by default: @hsaraogi for SA - I think this is easier to implement in our configuration for our internal product, since I'm not sure how to give meaningful defaults here.

---

Review status: all files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java, line 16 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabNCGUfotJoW_cdyaz:-Kac5vtHU9o6zg4a_gzj:b-nl33wt) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java#L16)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Yep, fine for this to go in a separate PR. Is there a "separate PR" laundry list somewhere?
</blockquote></details>

I'm going to begin spawning tickets!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java, line 20 at r6](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KabOA1ij8VhV4TqIU_0:-Kac5yHn_TO5OXFRmQlW:bonpoi8) ([raw file](https://github.com/palantir/atlasdb/blob/93ba56b728bdc5ca2c8e79e96e379c9226e75673/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerImplementation.java#L20)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

That sounds good to me!
</blockquote></details>

Ok. I'll wait for a bit more input and then make this change.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java, line 91 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaCAJ4vYdYkzz5BDp5u-r5-91:-Kac5VgSM1N_hlOpqVX8:b-g2m9gz) ([raw file](https://github.com/palantir/atlasdb/blob/8893725e280eef1f663e84e09aafd359611d2840/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java#L91)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

IMO it's best for this refactoring to go in as a separate PR.
</blockquote></details>

Yeah, agreed. I don't like the 2 levels of abstraction in the test, but this is a fairly involved change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-:-Kac640N9fZLlf1TaYIZ:bc9o16t)*

**Comment by hsaraogi** [comment]
@jeremyk-91 The module used for deployment will have ssl parameters set by default. We don't need to change the config here.

**Comment by jeremyk-91** [comment]
(Plan to defer SSL testing to another PR as well, since that looks to be pretty involved. This can probably be done by repurposing the scripts used to test http-remoting...)

**Comment by gsheasby** [comment]
Reviewed 1 of 31 files at r1, 4 of 37 files at r6, 28 of 28 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-KagldLPD_6LKyKy9gYN:b-vavlww) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
> ```Java
>     }
> 
>     public static LocalPaxosServices createLocalServices(LeaderConfig config,
> ```

Looks like it would be quite easy to mix these parameters up. However, Intellij informs me that we can make this method private, which would be an acceptable alternative IMO.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-KagplOq9UaHxRRBUnWq:b-7d708a) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
> ```Java
> 
>     // This is not great, but needed to preserve backwards compatibility for Leader Election Service
>     public static final String LEADER_PAXOS_NAMESPACE = "__leader";
> ```

Wasn't the `__leader` notation introduced elsewhere in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-KagrSb91eVkkHaDriOB:bt6phra) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Looks like it would be quite easy to mix these parameters up. However, Intellij informs me that we can make this method private, which would be an acceptable alternative IMO.
</blockquote></details>

Hmm, you're right that this is potentially confusing! 

Huh, IntelliJ must be misinformed though (the reason for this class is to support `PaxosTimeLockServer`'s complicated requirements). I'll see if I can write a parameter object with Immutables (and get a builder out of that for free).

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-Kags0CI0agP6vguLmhR:b-m7pqx) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Wasn't the `__leader` notation introduced elsewhere in this PR?
</blockquote></details>

It was. I tried to remove it at one point in an effort to clean things up a bit... but that's when I ran into the hardcoding issues I mentioned, so I gave up and reverted to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-KagsiwIS8BxA5SRgtKU:b-pef0gl) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Hmm, you're right that this is potentially confusing! 

Huh, IntelliJ must be misinformed though (the reason for this class is to support `PaxosTimeLockServer`'s complicated requirements). I'll see if I can write a parameter object with Immutables (and get a builder out of that for free).
</blockquote></details>

Ah yes. When I run `./gradlew idea`, another usage magically appears. Immutable object sounds good!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-KagssNfL3u-i7A-S0yP:b60sc2w) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

It was. I tried to remove it at one point in an effort to clean things up a bit... but that's when I ran into the hardcoding issues I mentioned, so I gave up and reverted to this.
</blockquote></details>

Do we need to have them both called "leader" though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
Review status: 34 of 36 files reviewed at latest revision, 25 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-Kagu_dhpgrT4E_3epy6:b-9e3sn3) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Ah yes. When I run `./gradlew idea`, another usage magically appears. Immutable object sounds good!
</blockquote></details>

Yep, added.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-KagugtLkeEQxhaT4QQY:b-nrrqwu) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Do we need to have them both called "leader" though?
</blockquote></details>

This one can be anything apart from `leader` explicitly; the hard-coded one is the next one, actually. I'm happy to rename this if there's a better idea.

(Note: JAX-RS operates by picking the class of the resource that matches a path, without backtracking. Our LeaderElectionService is hardcoded to eat up the `leader` path and doesn't play well with being a sub-resource, but we can pick anything other than `leader`. I tried to come up with something that no one is likely to use.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Reviewed 1 of 28 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 25 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-KahZrv7op_v4aFJeVN8:bswukud) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Yep, added.
</blockquote></details>

nit: This can now be one line...

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-Kah_8x-pc9OZp8ZFVGA:b-2qizzf) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

This one can be anything apart from `leader` explicitly; the hard-coded one is the next one, actually. I'm happy to rename this if there's a better idea.

(Note: JAX-RS operates by picking the class of the resource that matches a path, without backtracking. Our LeaderElectionService is hardcoded to eat up the `leader` path and doesn't play well with being a sub-resource, but we can pick anything other than `leader`. I tried to come up with something that no one is likely to use.)
</blockquote></details>

As discussed, my main concern is that `leader` and `__leader` can be conflated.
We suggested something matching `(__p|atlasP|p)axosLeader`, and excluding either the specific string, or all that start with `__`. I'm deferring to collective wisdom as to which exclusion would be better, but am pretty neutral to the name, as long as it isn't so similar to `leader`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Review status: 35 of 36 files reviewed at latest revision, 25 unresolved discussions.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-KahaULxVL_X9X1kHUPw:bv9xw3x) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

nit: This can now be one line...
</blockquote></details>

Did this myself!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
Review status: all files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 77 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagldLPD_6LKyKy9gYM:-Kahe1tu7rhgWHHbAda6:be17u80) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L77)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Did this myself!
</blockquote></details>

Ack, thanks!

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java, line 24 at r10](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KagplOq9UaHxRRBUnWp:-KaheDj2mB64qzL2dX-Y:b-16g7yw) ([raw file](https://github.com/palantir/atlasdb/blob/b29b4e0522802c8c5df631ac6358ed0fc62cc366/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java#L24)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

As discussed, my main concern is that `leader` and `__leader` can be conflated.
We suggested something matching `(__p|atlasP|p)axosLeader`, and excluding either the specific string, or all that start with `__`. I'm deferring to collective wisdom as to which exclusion would be better, but am pretty neutral to the name, as long as it isn't so similar to `leader`.
</blockquote></details>

Post offline discussion (esp. with @jaceklach) and crowdsourcing, a few changes:

- Use a `.internal` root and put everything under that. This clearly doesn't match `[a-zA-Z0-9_-]+` so we have no conflicts.
- Rename PaxosResource and the `__leader` part to an internal namespace, possibly to `.internal/paxos/{client}` and `.internal/paxosLeader` (this is OK because there's no conflict, and we don't need the unsightly underscores within our internal namespace.)
- Re-allow all clients apart from `leader` which we're unfortunately forced to keep because of the legacy leader election service.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

File: atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java [hunk 59]
```diff
@@ -99,13 +112,46 @@ public static LeaderElectionService create(
...
+        return PaxosProposerImpl.newProposer(
+                    ourLearner,
+                    ImmutableList.copyOf(acceptors),
+                    ImmutableList.copyOf(learners),
+                    quorumSize,
+                    executor);
+    }
 
-        return leader;
+    public static List<PaxosAcceptor> createAcceptorList(
```
Comment (hsaraogi) [inline atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java]: `createAcceptorList` and `createLearnerList` can be parameterized to `createList`?

File: atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckers.java [hunk 60]
```diff
@@ -32,8 +32,7 @@ private JepsenHistoryCheckers() {
     static final List<Supplier<Checker>> TIMESTAMP_CHECKERS = ImmutableList.of(
             MonotonicChecker::new,
             NonOverlappingReadsMonotonicChecker::new,
-            UniquenessChecker::new,
-            NemesisResilienceChecker::new);
+            UniquenessChecker::new);
```
Comment (hsaraogi) [inline atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckers.java]: Why are we getting rid of`NemesisResilienceChecker` in Jepsen tests?

File: atlasdb-timelock-server/build.gradle [hunk 61]
```diff
@@ -16,8 +16,10 @@ jacocoTestReport {
 check.dependsOn integTest
 
 dependencies {
-    compile project(":timestamp-api")
+    compile project(":timestamp-impl")
```
Comment (hsaraogi) [inline atlasdb-timelock-server/build.gradle]: good-catch!

File: atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckers.java (hunk 60 above)
Comment (jeremyk-91) [inline atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckers.java]: The only impl that passed this regularly was the KVS based one that we've decided not to use going forward; this one would fail about 5% of the time. We'd rather not have Jepsen flake by default, though we're keeping the checker around in case we want to do more involved testing on our own.

File: atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java (hunk 59 above)
Comment (jeremyk-91) [inline atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java]: Sure, will change this.

**Comment by gsheasby** [comment]
Reviewed 1 of 37 files at r6, 2 of 28 files at r10, 10 of 11 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java, line 137 at r13](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KaNT2w79f7UaUeCdU5L-r13-137:-KamO5k0ww4yxdDo_d8o:b-8fx2u7) ([raw file](https://github.com/palantir/atlasdb/blob/2bfddd972afe2cfa2df06c217d2dc26d0dc67ac2/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java#L137)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Sure, will change this.
</blockquote></details>

:+1: 

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 33 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamOBelPxRrusChYPR8:-KamOBelPxRrusChYPR9:b-8eluqk) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L33)):*
> ```Java
> public class LeadersTest {
>     @Test
>     public void canCreateProxyAndLocalList() {
> ```

Could also check for the other class, and ensure there's some error if you pass in the wrong class.

---

*[atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstantsTest.java, line 26 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamPIqM_zeaMvZaW8WS:-KamPIqNE3-B8skXna5S:b-mi5hp) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstantsTest.java#L26)):*
> ```Java
> public class PaxosTimeLockConstantsTest {
>     @Test
>     public void internalNamespaceShouldNotBeParsableAsClient() {
> ```

How about aa positive `ParsableAsClient` test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
Review status: all files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 33 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamOBelPxRrusChYPR8:-KamRud4liK6gsdSizOk:b-mq22if) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L33)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Could also check for the other class, and ensure there's some error if you pass in the wrong class.
</blockquote></details>

Added a test for Paxos acceptors, as suggested. Also added 3 more tests: that it does create a singleton list if no remote addresses are provided, throws if it tries to create proxies to a class which doesn't have jax-rs annotated methods, and throws if the class passed is null.

The class argument itself is parameterised, so it's nontrivial to pass in the wrong class unless I'm missing something.

---

*[atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstantsTest.java, line 26 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamPIqM_zeaMvZaW8WS:-KamQ5aFqW4O2yOE9Dx5:bveot3r) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstantsTest.java#L26)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

How about aa positive `ParsableAsClient` test?
</blockquote></details>

This is more of a test to ensure the internal namespace can't be parsed as a client though - checking whether a client name is allowed or not in general is already covered by the `TimeLockServerConfigurationTest` which does include positive examples (in particular, the regex is something that applies globally and isn't specific to Paxos).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by gsheasby** [comment]
Reviewed 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 33 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamOBelPxRrusChYPR8:-KamcxYSjUiGUA2jDEMD:b-un9ddf) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L33)):*
<details><summary><i>Previously, jeremyk-91 (Jeremy Kong) wrote…</i></summary><blockquote>

Added a test for Paxos acceptors, as suggested. Also added 3 more tests: that it does create a singleton list if no remote addresses are provided, throws if it tries to create proxies to a class which doesn't have jax-rs annotated methods, and throws if the class passed is null.

The class argument itself is parameterised, so it's nontrivial to pass in the wrong class unless I'm missing something.
</blockquote></details>

OK, sounds good to me - yep, sorry - the compiler does that test for you :)

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 93 at r15](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamdEJzsQv8jUDSCaa7:-KamdEJzsQv8jUDSCaa8:bu3vxgu) ([raw file](https://github.com/palantir/atlasdb/blob/718c80e2d9a2e416eaf2cca02cfc1833d4227556/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L93)):*
> ```Java
>                 Optional.absent(),
>                 BigInteger.class);
>         fail();
> ```

nit: these `fail()` lines are unnecessary, as the test will fail anyway if there's no exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by hsaraogi** [comment]
*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockServer.java, line 111 at r15](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamdesEI7_TEmq0qZw9:-KamdesEI7_TEmq0qZwA:bcgefwn) ([raw file](https://github.com/palantir/atlasdb/blob/718c80e2d9a2e416eaf2cca02cfc1833d4227556/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockServer.java#L111)):*
> ```Java
>     private LeaderConfig getLeaderConfig(TimeLockServerConfiguration configuration) {
>         return ImmutableLeaderConfig.builder()
>                     .leaders(addProtocols(configuration.cluster().servers()))
> ```

this misses the `sslConfiguration` parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
Review status: 39 of 40 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 33 at r14](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamOBelPxRrusChYPR8:-KamfFUpw8fP3M-F91mY:bglwvwx) ([raw file](https://github.com/palantir/atlasdb/blob/fe5721e0206050ed7b7336fa77988a9a59e86b42/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L33)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

OK, sounds good to me - yep, sorry - the compiler does that test for you :)
</blockquote></details>

Yep. There are probably [ways](http://io.livecode.ch/learn/namin/unsound) to force it to throw ClassCastException, though that would really be a test of the compiler :)

---

*[atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java, line 93 at r15](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamdEJzsQv8jUDSCaa7:-Kamf2kMAhTX0v-y1seZ:b-8e94tj) ([raw file](https://github.com/palantir/atlasdb/blob/718c80e2d9a2e416eaf2cca02cfc1833d4227556/atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java#L93)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

nit: these `fail()` lines are unnecessary, as the test will fail anyway if there's no exception.
</blockquote></details>

Ack, good spot. (I keep thinking I'm using the try-catch pattern where it is needed, for some reason...). Removed.

---

*[atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockServer.java, line 111 at r15](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-KamdesEI7_TEmq0qZw9:-KamfZhrdCZtLtnZWD-r:bgmujor) ([raw file](https://github.com/palantir/atlasdb/blob/718c80e2d9a2e416eaf2cca02cfc1833d4227556/atlasdb-timelock-server/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockServer.java#L111)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

this misses the `sslConfiguration` parameter.
</blockquote></details>

Added, good spot!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
(Marked as 'do not merge' as we're waiting for @rjullman to have a look through. Thanks in advance for the review!)

**Comment by harrybiddle** [comment]
Marking this as approved from me: I think I've added as much value as I can with the comments I've already given, and I'm not going to add any more value on top of the other awesome reviewers here.

**Comment by jeremyk-91** [comment]
I've received (at least some of) @rjullman 's comments from @gsheasby offline. Will update on Monday. Thanks for looking over this!

**Comment by gsheasby** [comment]
Reviewed 1 of 28 files at r10, 2 of 2 files at r16, 1 of 1 files at r17.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442)*

**Comment by jeremyk-91** [comment]
(Note: I've opened #1495 which also mentions the super edge case Bobby identified.)

**Comment by hsaraogi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1442#-:-KbBWB61lUYeuh8xuoNO:bnfp4nl)*
