### PR TITLE
Fix/hikari config for dbkvs

### LINKED ISSUE #675: Hikari configuration not being picked up by DbKVS
Although I’m configuring the socketTimeoutSeconds and connectionTimeoutSeconds in my Atlas configuration, Hikari logs report that the datasource socketTimeout, connectTimeout, and loginTimeout properties are all zero. Based on my configuration they should be 5, 30, and 30, respectively and by the default Atlas configurations they should be 45, 120, and 120 (see ConnectionConfig in Atlas). These need to be non-zero since we’re running on RDS and will otherwise get stale connections on a failover event.

### PR DESCRIPTION
**Pull request by gsheasby**
Added tests for various Hikari configurations. These options were not being passed through to Hikari by AtlasDB 0.8.0, but were working on develop.

This closes #675.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/707)

### CODE REVIEW

File: atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java [hunk 1]
```diff
@@ -123,6 +123,8 @@ public HikariConfig getHikariConfig() {
         config.setMaxLifetime(TimeUnit.SECONDS.toMillis(getMaxConnectionAge()));
         config.setIdleTimeout(TimeUnit.SECONDS.toMillis(getMaxIdleTime()));
         config.setLeakDetectionThreshold(getUnreturnedConnectionTimeout());
+        // Not a bug - we don't want to use connectionTimeout here, since Hikari uses a different terminology.
+        // See https://github.com/brettwooldridge/HikariCP/wiki/Configuration - connectionTimeout = how long to wait for a connection to be opened.
```
Comment (schlosna) [inline atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java]: Might be worth noting that the actual socket timeouts from `ConnectionConfig` `connectionTimeoutSeconds` and `socketTimeoutSeconds` are mapped in `com.palantir.nexus.db.pool.config.PostgresConnectionConfig#getHikariProperties` and `com.palantir.nexus.db.pool.config.OracleConnectionConfig#getHikariProperties` respectively.

**Comment by jboreiko** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java, line 127 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/707#-KNCoc0GIMOMpJZMtnwn-r1-127:-KNCy97a8fhFFHgCtFCL:-1399931497) ([raw file](https://github.com/palantir/atlasdb/blob/3fa6df341f07e88b2676669c3a249ab94fe6850a/atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java#L127)):*
<details><summary><i>Previously, schlosna (David Schlosnagle) wrote…</i></summary>
> Might be worth noting that the actual socket timeouts from `ConnectionConfig` `connectionTimeoutSeconds` and `socketTimeoutSeconds` are mapped in `com.palantir.nexus.db.pool.config.PostgresConnectionConfig#getHikariProperties` and `com.palantir.nexus.db.pool.config.OracleConnectionConfig#getHikariProperties` respectively.
</details>
That part seems a bit more obvious in the code, though I'll leave it up to Glenn to decide

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/707#-:-KNCyF8IhorJaXStRkFM:980077423)*

**Comment by gsheasby** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java, line 127 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/707#-KNCoc0GIMOMpJZMtnwn-r1-127:-KNDFf_Xo4698QdgJ2mu:10996545) ([raw file](https://github.com/palantir/atlasdb/blob/3fa6df341f07e88b2676669c3a249ab94fe6850a/atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java#L127)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> That part seems a bit more obvious in the code, though I'll leave it up to Glenn to decide
</details>
I added one extra line, mentioning where we are passing in the "real" connection timeout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/707)*

**Comment by schlosna** [comment]
Not sure if we want to put this under a separate PR, but there are still a few things odd with the DB KVS config. The following properties are under `DdlConfig`, but really have nothing to do with DDL, but are used for DML reads and writes:

```
    ddl:
      poolSize: 64 # thread pool size for DB KVS executor
      fetchBatchSize: 256 # large read batching into separate queries
      mutationBatchCount: 1000 # put batch partitioning
      mutationBatchSizeBytes: 2097152 # put batch partitioning
```

**Comment by rjullman** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/707)*

**Comment by rjullman** [comment]
Yeah, I agree that is a little confusing, but we can probably address that in a different PR.

In general this :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/707#-:-KNEwJMmdBYSiC9VB5pt:-606895644)*

**Comment by gsheasby** [comment]
@schlosna Thanks for the note about DDL config; I've added it to the epic #504.
