### PR TITLE
Hotfix: Schemas + UUIDs

### LINKED ISSUE #2587: Code generated for UUID value type column broken in 0.63.0
```
    private static void nameToUuidTable(Schema schema) {
        schema.addTableDefinition("name_to_uuid", new TableDefinition() {
            {
                allSafeForLoggingByDefault();

                javaTableName("NameToUUID");
                rowName();
                hashFirstRowComponent();
                rowComponent("name", ValueType.VAR_STRING);

                columns();
                column("uuid", "u", ValueType.UUID);
            }
        });
    }
```
In the generated `NameToUUIDTable.java` I get 
```

...
    public static final class Uuid implements NameToUUIDNamedColumnValue<UUID> {
        private final UUID value;

        public static Uuid of(UUID value) {
            return new Uuid(value);
        }

        private Uuid(UUID value) {
            this.value = value;
        }
...
```

and `java.util.UUID` is never imported. So, compilation of this class fails. In 0.62.0, the generated code directly uses the fully qualified class name `java.util.UUID` and hence an import isn't needed.

### PR DESCRIPTION
**Pull request by jeremyk-91**
@a-k-g for SA

**Goals (and why)**: Fix #2587. I've confirmed that the other datatypes are currently okay, because `Long` is a java.lang thing and `Sha256Hash` is used elsewhere in the class.

**Implementation Description (bullets)**:
- import `java.util.UUID`
- add a test that uses every possible primitive value type

**Concerns (what feedback would you like?)**:
Some alternatives include:
1. convert the general `getJavaObjectClassName()` to use the class's `getName()` - but this is a no-go when using arrays, because that returns `[B` e.g. for a byte array.
2. ~import `java.util.UUID` - but then we have an unused import for rendered classes that don't use UUIDs.~
3. just override `getJavaClassName()` in UUID to return the proper thing, but this still leaves `Sha256Hash` in a hacky state where we depend on us getting lucky with imports elsewhere.
4. define a flag that indicates whether a value-type is a Java Object type. This flag is false by default, but true for `UUID` and `Sha256Hash` (note: we "get lucky" for Sha256Hash because we already import the class and use it elsewhere). 

**Where should we start reviewing?**: `ValueTypeTest` outlines the model I'm going for.

**Priority (whenever / two weeks / yesterday)**: soon, we might want to patch 63 too

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2589)

### CODE REVIEW

**Comment by nziebart** [comment]
should we just do the same thing as for `Sha256Hash` and import `UUID.class` in `TableRenderer`?

**Comment by nziebart** [comment]
Ah, I see that was one of your proposed alternatives. I think the concern you mention isn't really an issue. We have plenty of unused imports - we actually include a big javadoc at the end of the generated classes that references all of the imports: `* This exists to avoid unused import warnings`

**Comment by jeremyk-91** [comment]
Hmm, I did not see that!

Yep, in general if we're okay with doing that, then that is a ton simpler - just that I didn't think we were okay with doing that at all :) seems worth the simplification, then!

File: atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java [hunk 1]
```diff
@@ -68,6 +69,20 @@ private static Schema generateSchema() {
...
+            {
+                javaTableName("AllValueTypesTest");
+
+                rowName();
+                rowComponent("component1", ValueType.STRING);
+
+                columns();
+                IntStream.range(0, ValueType.values().length)
+                        .forEachOrdered(typeIndex ->
+                                column("column" + typeIndex, "c" + typeIndex, ValueType.values()[typeIndex]));
```
Comment (nziebart) [inline atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java]: nice! should we do this for the row components as well?

Comment (jeremyk-91) [reply atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java]: Ah, good point - this only tests the named column renderer.

Comment (jeremyk-91) [reply atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java]: Rather annoyingly though I'm going to have to filter out one of string or blob because they have to be at the end. Probably going to write this as a stream of the types that aren't restricted, followed by a single blob component at the end for now.

Comment (jeremyk-91) [reply atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java]: also found a cleaner way to write the above (enums have an `ordinal()` method apparently)

**Comment by hsaraogi** [comment]
Lets release 0.63.1 after merging this to unblock products from upgrading.
