### PR TITLE
Fix race condition in PersistentTimestampService

### LINKED ISSUE #462: PersistentTimestampService Race Condition
I was fixing something else and came across
```
        if (isAllocationTaskSubmitted.compareAndSet(false, true) && isAllocationRequired(lastReturnedTimestamp.get(), upperLimitToHandOutInclusive.get())) {
            final Exception createdException = new Exception("allocation task called from here");
            executor.submit(new Runnable() {
                @Override
                public void run() {
                    try {
                        if (allocationFailure instanceof MultipleRunningTimestampServiceError) {
                            // We cannot allocate timestamps anymore because another server is running.
                            return;
                        }
                        allocateMoreTimestamps();
                        lastAllocatedTime = clock.getTimeMillis();
                        allocationFailure = null;
                    } catch (Throwable e) { // (authorized)
                        createdException.initCause(e);
                        if (allocationFailure != null
                                && e.getClass().equals(allocationFailure.getClass())) {
                            // QA-75825: don't keep logging error if we keep failing to allocate.
                            log.info("Throwable while allocating timestamps.", createdException);
                        } else {
                            log.error("Throwable while allocating timestamps.", createdException);
                        }
                        allocationFailure = e;
                    } finally {
                        isAllocationTaskSubmitted.set(false);
                    }
                }
            });
        }
```

Maybe there are secondary guarantees that protect us here, but it seems that isAllocationTaskSubmitted atomic boolean can be set to true and never unset if (1) the CAS succeeds but the isAllocationRequired() check fails or (2) something catastrophic happens to with your executor before the finally clause is called.  I think probably case (2) is safe depending on Executor documentation.  The other case (1) was introduced more recently in https://github.com/palantir/atlasdb/pull/354.

I'll fix this tomorrow, but wanted to give SA in case we have some procedure for handling/supporting regressions.

### PR DESCRIPTION
**Pull request by gbrova**
@joelea 

Fixes #462 

By swapping the order, it is no longer possible for isAllocationTaskSubmitted.compareAndSet(false, true) to happen and remain true forever.

### CODE REVIEW

**Comment by joelea** [comment]
Can you add a chunk to the release notes

**Comment by joelea** [comment]
@rjullman can you review this as well since you found it.

File: timestamp-impl/src/main/java/com/palantir/timestamp/PersistentTimestampService.java [hunk 1]
```diff
@@ -98,34 +98,38 @@ private static void advanceAtomicLongToValue(AtomicLong toAdvance, long val) {
...
+                        } finally {
+                            isAllocationTaskSubmitted.set(false);
                         }
-                        allocationFailure = e;
-                    } finally {
-                        isAllocationTaskSubmitted.set(false);
                     }
-                }
-            });
+                });
```
Comment (rjullman) [inline timestamp-impl/src/main/java/com/palantir/timestamp/PersistentTimestampService.java]: We probably can reduce the code here by reordering the check (doing the CAS second).  In the end it doesn't really matter -- happy to go with this code too.

Comment (gbrova) [inline timestamp-impl/src/main/java/com/palantir/timestamp/PersistentTimestampService.java]: That was my first thought too (see earlier commit on this branch).  Sadly, reordering the check makes it possible for this to run multiple times, which is not a disaster in practice but can lead to test flakiness. 

The clean/proper solution will be to let java handle the concurrency aspect for us, per #466 (which is already in progress).  Since that's coming soon anyway, I'm happy with this patched solution.

File: timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java [hunk 2]
```diff
@@ -90,7 +91,7 @@ public void incrementUpperLimitIfOneMinuteElapsedSinceLastUpdate() throws Interr
         Thread.sleep(10);
         persistentTimestampService.getFreshTimestamp();
         Thread.sleep(10);
-        verify(timestampBoundStore, times(2)).storeUpperLimit(anyLong());
+        verify(timestampBoundStore, atLeast(2)).storeUpperLimit(anyLong());
```
Comment (joelea) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Is there a danger of a loop which causes massive load of upper limit storing?

Comment (gbrova) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Theoretically yes, but in practice I've never seen it happen -- for this test, for example, most of the time it's _exactly 2_, and occasionally 3. Even repeating this test hundreds of times, I haven't seen it be more than 3 calls to storeUpperLimit.

Comment (joelea) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Cool, can we stick in a check that it's <= 3 then

Comment (gbrova) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Added a new test, let me know if that's what you meant.

Comment (joelea) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Seems reasonable.

Comment (jboreiko) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: Is there a ticket open to reduce this oddity of it setting the upper limit multiple times?

Comment (gbrova) [inline timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTest.java]: #466 should make this sadness go away (and it's unblocked now that DBKVS is in). 

The (soon-to-be-historical) reason this was set multiple times was that setting it happened in a busy-loop in a separate thread, so sometimes an extra call would sneak in. (That has no correctness implications because there is no harm in allocating more timestamps than necessary)
