### PR TITLE
don't log sql errors that are expected (+bonus cleanup)

### LINKED ISSUE #709: Atlas INFO logs exceptions that are expected / higher up logic wants to deal with them silently
Leads to a lot of (slightly scary lookgin) log spam with stacktraces on startup, e.g.:
```
[12:05:05,951][INFO][sqlException.com.palantir.sql.PreparedStatements] Caught SQLException
org.postgresql.util.PSQLException: ERROR: relation "dual" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:465)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.palantir.nexus.db.pool.InterceptorStatement.handleInvocation(InterceptorStatement.java:52)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy64.execute(Unknown Source)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.palantir.nexus.db.sql.BasicSQL$BlobCleanupPreparedStatement.invoke(BasicSQL.java:344)
        at com.sun.proxy.$Proxy65.execute(Unknown Source)
        at com.palantir.sql.PreparedStatements.execute(PreparedStatements.java:42)
        at com.palantir.nexus.db.sql.BasicSQL$4$1.visit(BasicSQL.java:543)
        at com.palantir.nexus.db.sql.BasicSQL$4$1.visit(BasicSQL.java:540)
        at com.palantir.nexus.db.sql.BasicSQL.wrapPreparedStatement(BasicSQL.java:482)
        at com.palantir.nexus.db.sql.BasicSQL.access$100(BasicSQL.java:72)
        at com.palantir.nexus.db.sql.BasicSQL$4.call(BasicSQL.java:540)
        at com.palantir.nexus.db.sql.BasicSQL$4.call(BasicSQL.java:537)
        at com.palantir.nexus.db.sql.BasicSQLUtils$1.call(BasicSQLUtils.java:284)
        at com.palantir.nexus.db.ThreadConfinedProxy$1.call(ThreadConfinedProxy.java:102)
        at com.palantir.common.concurrent.ThreadNamingCallable.call(ThreadNamingCallable.java:55)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:55)
        at com.palantir.common.concurrent.PTExecutors$5.run(PTExecutors.java:486)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by clockfort**
Fixes #709

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/765)

### CODE REVIEW

File: commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java [hunk 1]
```diff
@@ -70,6 +71,7 @@
 import com.palantir.util.sql.VerboseSQLException;
 
 public abstract class BasicSQL {
+    private static final Logger sqlExceptionlog = Logger.getLogger("sqlException." + PreparedStatements.class.getName());
```
Comment (jboreiko) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java]: Why not use the SqlLoggers.SQL_EXCEPTION_LOG?  The actual question being what is the difference between having it under PreparedStatements instead of BasicSql logger

Comment (jboreiko) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java]: Why not use the SqlLoggers.SQL_EXCEPTION_LOG?  The actual question being what is the difference between having it under PreparedStatements instead of BasicSql logger

Comment (clockfort) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java]: I agree, it should be SqlLoggers.SQL_EXCEPTION_LOG
