### PR TITLE
Fix/compact warning for non ee oracle users

### LINKED ISSUE #2276: Oracle non-EE should warn users saying that they will have to SHRINK space manually
A quick workaround for #2262 will be to at least warn non-EE users that there is no compaction being done and the DB will blow up even though background sweep is running. 

@NathanialNewman for SA.

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Fixes #2276.

**Implementation Description (bullets)**: If enterprise features are disabled, log a warning when calling `compactInternally`.

**Concerns (what feedback would you like?)**: This warning is going to be logged _every time_ we delete some data as part of sweep, _forever_. Should we add an option to ignore it, or otherwise somehow suppress further occurrences in order to reduce logspam?

**Where should we start reviewing?**: The one file

**Priority (whenever / two weeks / yesterday)**: ASAP

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2277)

### CODE REVIEW

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 1]
```diff
@@ -253,7 +252,18 @@ public void compactInternally() {
...
                         + " like more information. Underlying error was: {}", tableRef, e.getMessage());
             } catch (TableMappingNotFoundException e) {
-                throw Throwables.propagate(e);
+                throw new RuntimeException(e);
+            }
+        } else {
+            try {
+                log.warn("Tried to clean up table {}, but couldn't, because enterprise features are disabled. "
+                        + "This means that even if you are running sweep, you will need to manually clean up your "
+                        + "tables, otherwise disk usage will continually increase. To free up space, run the SHRINK "
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: SHRINK SPACE

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 2]
```diff
@@ -253,7 +252,18 @@ public void compactInternally() {
                         + " IOT tables to compensate for bloat. You can contact Palantir Support if you'd"
                         + " like more information. Underlying error was: {}", tableRef, e.getMessage());
             } catch (TableMappingNotFoundException e) {
-                throw Throwables.propagate(e);
+                throw new RuntimeException(e);
+            }
+        } else {
+            try {
+                log.warn("Tried to clean up table {}, but couldn't, because enterprise features are disabled. "
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: `Tried to clean up {} bloat after a sweep operation`: to be consistent with the above. In fact we should be able to consolidate the two error messages with the difference that Enterprise Edition features are not enabled in the later case.

Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: Note that we shouldnt break the existing message here as deployments might be parsing logs for this.

Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: Do we need to keep the whole existing message the same? I find the second part of the new log message more informative - it actually says which command to run, for instance. If the "advice" parts should be different for the two messages, then there really isn't much in common between the two log messages, so I don't see much value in extracting the common parts.

**Comment by hsaraogi** [comment]
Re concern on spamming logs: Compaction is attempted once sweeping a table is complete and shouldnt be too frequent.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 3]
```diff
@@ -253,7 +252,19 @@ public void compactInternally() {
...
             } catch (TableMappingNotFoundException e) {
-                throw Throwables.propagate(e);
+                throw new RuntimeException(e);
+            }
+        } else {
+            try {
+                log.warn("Tried to clean up {} bloat after a sweep operation, but couldn't, because enterprise "
+                        + "features are disabled. "
+                        + "This means that even if you are running sweep, you will need to manually clean up your "
+                        + "tables, otherwise disk usage will continually increase. To free up space, run the "
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: `will continually increase` has some caveats, you can reuse space if operating on a single table. i.e. you write many versions to a table, sweep it and you can write more versions reusing the deleted space.

Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: `might continually increase`?

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 4]
```diff
@@ -253,7 +252,19 @@ public void compactInternally() {
...
+                        + "SHRINK SPACE command on the underlying oracle table, {}.",
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: They should generally run `shrink space compact` (which only needs row-level locks, so that’s fine) and `shrink space` afterwards.(See #2262) We shouldn't advise this before testing ourselves that it is safe.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java [hunk 5]
```diff
@@ -238,34 +238,31 @@ private void executeIgnoringError(String sql, String errorToIgnore) {
...
-                throw new RuntimeException(e);
-            }
-        } else {
-            try {
-                log.warn("Tried to clean up {} bloat after a sweep operation, but couldn't, because enterprise "
-                        + "features are disabled. "
-                        + "This means that even if you are running sweep, you will need to manually clean up your "
-                        + "tables, otherwise disk usage will continually increase. To free up space, run the "
-                        + "SHRINK SPACE command on the underlying oracle table, {}.",
+                log.error(compactionFailureTemplate + "Underlying error was: {}",
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java]: There's a space missing here before "Underlying error"
