### PR TITLE
table name unmapping cache and connection cleanup

### LINKED ISSUE #1195: Oracle Table Name Mapping Perf
It seems like the following codepath hits a part of the new oracle table name mapping magics that should be behind a cache/supplier, but appears not to be; if it is indeed not, it is a sizable perf regression.

Snippet of my stacktrace:
```
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ConnectionSupplier.getFresh(ConnectionSupplier.java:49) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ConnectionSupplier.get(ConnectionSupplier.java:38) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.OracleTableNameUnmapper.getShortTableNameFromMappingTable(OracleTableNameUnmapper.java:37) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.OracleTableNameGetter.getInternalShortTableName(OracleTableNameGetter.java:58) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.PrefixedTableNames.getOraclePrefixedTableName(PrefixedTableNames.java:45) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.PrefixedTableNames.get(PrefixedTableNames.java:36) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getPrefixedTableName(DbKvsGetRanges.java:333) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getSimpleRowSelectOneQueryOracle(DbKvsGetRanges.java:326) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getRangeQueryAndArgs(DbKvsGetRanges.java:199) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getFirstPages(DbKvsGetRanges.java:107) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.ranges.DbKvsGetRanges.getFirstBatchForRanges(DbKvsGetRanges.java:94) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.dbkvs.impl.DbKvs.getFirstBatchForRanges(DbKvs.java:384) ~[atlasdb-dbkvs/:na]
	at com.palantir.atlasdb.keyvalue.impl.ForwardingKeyValueService.getFirstBatchForRanges(ForwardingKeyValueService.java:129) ~[atlasdb-client/:na]
```

### PR DESCRIPTION
**Pull request by clockfort**
~~This only partially addresses #1195 ; I believe there will be (now much smaller number of) connection tracker errors still from not properly closed connections.~~
schlos made me fix both issues; fixes #1195 

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1215)

### CODE REVIEW

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java [hunk 1]
```diff
@@ -26,23 +31,35 @@
...
-                        + "FROM " + AtlasDbConstants.ORACLE_NAME_MAPPING_TABLE
-                        + " WHERE table_name = ?", fullTableName);
-        if (results.size() == 0) {
-            throw new TableMappingNotFoundException(
-                    "The table " + fullTableName + " does not have a mapping."
-                    + "This might be because the table does not exist.");
+        try {
+            return unmappingCache.get(fullTableName);
+        } catch (ExecutionException e) {
+            throw new TableMappingNotFoundException(e);
```
Comment (schlosna) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: probably want `throw new TableMappingNotFoundException(e.getCause());`

Comment (clockfort) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: yep, thanks

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java [hunk 2]
```diff
@@ -26,23 +31,39 @@
 class OracleTableNameUnmapper {
     private final ConnectionSupplier conns;
 
+    private LoadingCache<String, String> unmappingCache = CacheBuilder.newBuilder().build(
+            new CacheLoader<String, String>() {
+                @Override
+                public String load(String fullTableName) throws Exception {
+                    AgnosticResultSet results = conns.get().selectResultSetUnregisteredQuery(
```
Comment (schlosna) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: The `ConnectionSupplier` and `SqlConnection` interface is a resource seive. You could do your own connection management using `conns.getFresh()` and ensure closure of that one, basically what's done in `com.palantir.atlasdb.keyvalue.dbkvs.impl.BatchedDbReadTable#run`.

Comment (clockfort) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: Fiiine, I'll fix all of #1195

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java [hunk 3]
```diff
@@ -15,34 +15,71 @@
...
+                                    + " WHERE table_name = ?", fullTableName);
+                    if (results.size() == 0) {
+                        throw new TableMappingNotFoundException(
+                                "The table " + fullTableName + " does not have a mapping."
+                                        + "This might be because the table does not exist.");
+                    }
+                    String mappedName = Iterables.getOnlyElement(results.rows()).getString("short_table_name");
+
+                    try {
+                        conn.getUnderlyingConnection().close();
```
Comment (schlosna) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: this needs to be in a finally block

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java [hunk 4]
```diff
@@ -15,34 +15,75 @@
...
+
     private final ConnectionSupplier conns;
 
+    private LoadingCache<String, String> unmappingCache = CacheBuilder.newBuilder().build(
+            new CacheLoader<String, String>() {
+                @Override
+                public String load(String fullTableName) throws Exception {
+                    SqlConnection conn = null;
+                    try {
+                        conn = conns.getFresh();
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: This will block on getting a new connection which might lead to long pauses/deadlocks, should we switch back to reusing a connection from the supplier?

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java [hunk 5]
```diff
@@ -15,34 +15,75 @@
...
+                            throw new TableMappingNotFoundException(
+                                    "The table " + fullTableName + " does not have a mapping."
+                                            + "This might be because the table does not exist.");
+                        }
+
+                        return Iterables.getOnlyElement(results.rows()).getString("short_table_name");
+                    } finally {
+                        if (conn != null) {
+                            try {
+                                conn.getUnderlyingConnection().close();
```
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java]: we might be able to call `conns.close()` in `OracleTableNameGetter` like most `Dbkvs` calls:

```
    public String getInternalShortTableName() throws TableMappingNotFoundException {
        ConnectionSupplier conns = new ConnectionSupplier(connectionSupplier);
        if (useTableMapping) {
            try {
                return new OracleTableNameUnmapper(conns).getShortTableNameFromMappingTable(tablePrefix,
                        tableRef);
            } finally {
                conns.close();
            }
        }
        return getPrefixedTableName();
    }
```

File: docs/source/release_notes/release-notes.rst [hunk 6]
```diff
@@ -55,6 +55,14 @@ develop
          - The migration CLI will now decrypt encrypted values and will now use the dropwizard config as the new configuration.
            (`Pull Request <https://github.com/palantir/atlasdb/pull/1171>`__)
 
+    *    - |improved|
+         - Oracle perf improvement; table names now cached, resulting in fewer round trips to the database.
```
Comment (hsaraogi) [inline docs/source/release_notes/release-notes.rst]: Add tests to check that the cache is hit.

File: docs/source/release_notes/release-notes.rst [hunk 7]
```diff
@@ -55,6 +55,14 @@ develop
...
+           (`Pull Request <https://github.com/palantir/atlasdb/pull/1215>`__)
+
+    *    - |fixed|
+         - Certain Oracle KVS calls no longer attempt to leak connections created internally.
```
Comment (hsaraogi) [inline docs/source/release_notes/release-notes.rst]: Tests to ensure what that the connection does not leak now.

**Comment by clockfort** [comment]
Should be g2g ; both tests added.

(I didn't do the other two suggestions for the reason schlos specified; I actually tried to do it that way originally and changed it)

**Comment by schlosna** [comment]
👍
