### PR TITLE
Downgrade C* connection failure log to warn

### LINKED ISSUE #3054: If one Cassandra node is down, BackgroundSweeper spams ERROR logs
We require consistency ALL when deleting values. When we have a quorum of nodes up and BackgroundSweeper is enabled, BackgroundSweeper will constantly try to delete and spam ERROR logs while doing so, since Cassandra will throw an UnavailableException.

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Fixes #3054 (see ticket for discussion, BLUF: The exception is rethrown to the calling service, who can log at error if desired.)

**Implementation Description (bullets)**:
- Error --> warn
- Also, added safe args to one of the log messages.

**Concerns (what feedback would you like?)**:
I wanted to add a note about _which_ exception is thrown, but from a partial investigation it seems we're not consistent in this. Sometimes we catch the C* exception and throw AtlasDbDependencyException, but not always. I deferred fully investigating this to a later time, as the issue on the ticket was fixed anyway.

**Where should we start reviewing?**: One java file

**Priority (whenever / two weeks / yesterday)**: This week

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3069)

### CODE REVIEW

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java [hunk 1]
```diff
@@ -98,13 +98,17 @@ RequestExceptionHandlerStrategy getStrategy() {
...
+                    UnsafeArg.of("exceptionMessage", ex.getMessage()));
+            String errorMsg = MessageFormatter.format(CONNECTION_FAILURE_MSG, numberOfAttempts).getMessage();
             throw (K) new TTransportException(((TTransportException) ex).getType(), errorMsg, ex);
         } else {
-            log.error("Tried to connect to cassandra {} times.",
-                    SafeArg.of("numTries", numberOfAttempts), ex);
+            log.warn("Tried to connect to cassandra {} times. Exception message was: {} : {}",
+                    SafeArg.of("numTries", numberOfAttempts),
+                    SafeArg.of("exceptionClass", ex.getClass().getTypeName()),
+                    UnsafeArg.of("exceptionMessage", ex.getMessage()));
```
Comment (jeremyk-91) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java]: In general one advantage of logging the exception here is that you get the (safe) stack-trace, though I guess in these circumstances it isn't normally very useful?

Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java]: We also log on the first failure (at INFO), so are not losing this information assuming we keep failing for the same reason.
