### PR TITLE
Fix/suppress ClientPoolImpl stacktrace spam 

### LINKED ISSUE #2280: Don't output the stacktrace for WARN logs on timeouts to C* nodes
Based on feedback from folks.

### PR DESCRIPTION
**Pull request by gsheasby**
Reapplied changes from #2373 after the Startup Ordering PR merged

* Copy-paste those changes
* Fix logic: numTries == 1 instead of numTries > 1
* Add SafeArg and remove exception from the fast failover message
* Added a release note

**Goals (and why)**: Fixes #2280.

**Implementation Description (bullets)**:
* For retryable exceptions, logged exception class name and message instead of stack trace
(the stack trace is still logged if we run out of retries)
* Added the query's toString to one of the log messages. The query string typically contains the type of Cassandra query, as well as the column family
* Added SafeArg calls for arguments that are considered safe.

**Concerns (what feedback would you like?)**:
* Is there anything extra that I missed?

**Where should we start reviewing?**: `CassandraClientPoolImpl`

**Priority (whenever / two weeks / yesterday)**: today - higher priority since one of our internal product gets indigestion when we feed them this spam. @chrisalice for SA.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2432)

### CODE REVIEW

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java [hunk 1]
```diff
@@ -581,8 +590,8 @@ private void refreshTokenRanges() {
                         = getRandomGoodHostForPredicate(address -> !triedHosts.contains(address));
                 hostPool = hostPoolCandidate.orElseGet(this::getRandomGoodHost);
                 log.warn("Randomly redirected a query intended for host {} to {}.",
-                        previousHostPool,
-                        hostPool.getHost());
+                        SafeArg.of("previousHost", previousHostPool),
+                        SafeArg.of("newHost", hostPool.getHost()));
```
Comment (hsaraogi) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: Maybe: newHost -> randomHost

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java [hunk 2]
```diff
@@ -592,18 +601,24 @@ private void refreshTokenRanges() {
                 triedHosts.add(hostPool.getHost());
                 this.<K>handleException(numTries, hostPool.getHost(), e);
                 if (isRetriableWithBackoffException(e)) {
-                    log.warn("Retrying with backoff a query intended for host {}.", hostPool.getHost(), e);
+                    // And value between -500 and +500ms to backoff to better spread load on failover
+                    int sleepDuration = numTries * 1000 + (ThreadLocalRandom.current().nextInt(1000) - 500);
+                    log.warn("Retrying with backoff ({}ms} a query, {}, intended for host {}.",
```
[the remark this answers is not in the document]
Comment (schlosna) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: yeah, there's a stray `}` in there after `ms`

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java [hunk 3]
```diff
@@ -350,8 +356,11 @@ private boolean isHostHealthy(InetSocketAddress host) {
             testingContainer.runWithPooledResource(validatePartitioner);
             return true;
         } catch (Exception e) {
-            log.error("We tried to add {} back into the pool, but got an exception"
-                    + " that caused us to distrust this host further.", host, e);
+            log.warn("We tried to add {} back into the pool, but got an exception"
+                            + " that caused us to distrust this host further. Exception message was: {} : {}",
+                    SafeArg.of("host", host),
+                    SafeArg.of("exceptionClass", e.getClass().getTypeName()),
```
Comment (schlosna) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: nit: `getTypeName` is a new one, should be fine though `e.getClass().getName()` or `e.getClass().getCanonicalName()` might be simpler

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java [hunk 4]
```diff
@@ -671,11 +686,23 @@ private void updateMetricOnAggregateAndHost(
...
+                    log.warn("Error occurred talking to cassandra. Attempt {} of {}. Exception message was: {} : {}",
+                            SafeArg.of("numTries", numTries),
+                            SafeArg.of("maxTotalTries", MAX_TRIES_TOTAL),
+                            SafeArg.of("exceptionClass", ex.getClass().getTypeName()),
+                            UnsafeArg.of("exceptionMessage", ex.getMessage()));
+                } else {
+                    log.warn("Error occurred talking to cassandra. Attempt {} of {}.",
+                            SafeArg.of("numTries", numTries),
+                            SafeArg.of("maxTotalTries", MAX_TRIES_TOTAL),
+                            ex);
```
Comment (schlosna) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: shouldn't the exception be the last arg in the if block, not else? I think we could actually do the following to cover all cases so that we include the exception class & message all the time, but only include stacktrace on first occurrence.

```
            log.warn("Error occurred talking to cassandra. Attempt {} of {}. Exception message was: {} : {}",
                    SafeArg.of("numTries", numTries),
                    SafeArg.of("maxTotalTries", MAX_TRIES_TOTAL),
                    SafeArg.of("exceptionClass", ex.getClass().getName()),
                    UnsafeArg.of("exceptionMessage", ex.getMessage()),
                    (numTries == 1) ? ex : null);
```

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java [hunk 5]
```diff
@@ -114,19 +116,34 @@ private InetSocketAddress getHostForRow(byte[] row) {
...
-            return clientPool.runWithRetryOnHost(host, client ->
-                    client.execute_cql3_query(queryBytes, Compression.NONE, consistency));
+            return clientPool.runWithRetryOnHost(host, fn);
         } catch (TException e) {
             throw Throwables.throwUncheckedException(e);
         }
     }
 
+    private FunctionCheckedException<Cassandra.Client, CqlResult, TException> getCqlFunction(String query) {
+        ByteBuffer queryBytes = ByteBuffer.wrap(query.getBytes(StandardCharsets.UTF_8));
```
Comment (schlosna) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java]: do we want to eagerly capture and retain both the query string & converted bytes & byte buffer or should this be inlined into `apply` below as:

```
            public CqlResult apply(Cassandra.Client client) throws TException {
                ByteBuffer queryBytes = ByteBuffer.wrap(query.getBytes(StandardCharsets.UTF_8));
                return client.execute_cql3_query(queryBytes, Compression.NONE, consistency);
            }
```

File: atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java [hunk 6]
```diff
@@ -360,13 +360,27 @@ private void runNoopOnHostWithException(InetSocketAddress host, CassandraClientP
...
         } catch (Exception e) {
             // expected
         }
     }
 
+    private FunctionCheckedException<Cassandra.Client, Object, RuntimeException> noOp() {
+        return new FunctionCheckedException<Cassandra.Client, Object, RuntimeException>() {
+            @Override
+            public Object apply(Cassandra.Client input) throws RuntimeException {
+                return null;
```
Comment (schlosna) [inline atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java]: nit: this should probably return `Void`:

```
    private FunctionCheckedException<Cassandra.Client, Void, RuntimeException> noOp() {
        return new FunctionCheckedException<Cassandra.Client, Void, RuntimeException>() {
            @Override
            public Void apply(Cassandra.Client input) throws RuntimeException {
                return null;
            }

            @Override
            public String toString() {
                return "no-op";
            }
        };
    }
```

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java (hunk 4 above)
Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: ....d'oh, I was right the first time!

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java (hunk 5 above)
Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java]: We need to override `toString` here to make the log message helpful - see `CassandraClientPoolImpl.runWithRetryOnHost`.

Comment (schlosna) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java]: You can still override toStringas you have it, this just avoids keeping the byte buffer around  after executing the query. If we are going to re-execute the query many times, then your original version of eagerly converting to bytes might be better tradeoff

Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java]: I would expect the query to execute one time in 99.9% of cases.
However, I'm a little confused about the comment about "keeping the byte buffer around" - doesn't it go away when we exit `getCqlFunction`?

Relatedly - I've been biasing towards keeping the stuff inside `clientPool.runWithRetryOnHost` as small as possible, ideally just `client.do_the_thing(the_arguments)`.

That way, it's more transparent which code might throw the exception we're passing, and it generally produces cleaner and more testable code - if we do that for long enough, eventually all of the clientPool-calling logic will live inside a small class which we can just mock for testing (and replace with CQL for production).

Does that practice lead to sub-optimal perf somehow?

Comment (schlosna) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutor.java]: I don't think this is actually a huge issue as I don't expect the queries to be that large, but my comment was more intended as context around potential issues with capturing references via lambda & anonymous inner classes. By "keeping the byte buffer around", what I mean is that in the current PR, the `ByteBuffer queryBytes` and `String query` references are captured as they are referenced in the `apply` and `toString` methods respectively. This means that both will live beyond the execution of the `getCqlFunction` method and until the `executeCqlFunctionOnHost` exits.

```
    private FunctionCheckedException<Cassandra.Client, CqlResult, TException> getCqlFunction(String query) {
        return new FunctionCheckedException<Cassandra.Client, CqlResult, TException>() {
            @Override
            public CqlResult apply(Cassandra.Client client) throws TException {
                ByteBuffer queryBytes = ByteBuffer.wrap(query.getBytes(StandardCharsets.UTF_8));
                return client.execute_cql3_query(queryBytes, Compression.NONE, consistency);
            }

            @Override
            public String toString() {
                return query;
            }
        };
    }
```

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java (hunk 4 above)
Comment (schlosna) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: @gsheasby isn’t your logic here backwards if you’re trying to only log the exception on first failed attempt? I am pretty sure the whole of/else should be replaced with my comment above

Comment (gsheasby) [reply atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java]: Looks correct on develop. We don't need to log exceptionClass or message on the first try, since we log the whole exception.
