### PR TITLE
Fix/mrtse failover

### LINKED ISSUE #1749: Better handling of MultipleRunningTimestampServiceError
@jboreiko identified an issue we think caused PDS-50340, whereby a leadership election occurs whilst the immutable timestamp is being updated by the existing leader, and a race condition causes a runtime exception in the existing leader. This causes the client call to fail at the very least, and possibly (?) death of the server (John and I weren't clear on the worst-case impact).

Since clustered lock should be highly available, this feels like a bad bug.

@jboreiko , if you could flesh out this explanation it would be great – but I believe the full timeline (assuming a SQL database) is:
* Server A is leader and is running low on timestamps
* Server A receives a request that requires the immutable timestamp to be updated
* Server A makes a SQL call to the underlying DB to update the timestamp bound
* A leadership election occurs, for whatever reason
* Server B is elected leader
* Server B tries to grab initial timestamps
* Server B makes a call to the DB to update the timestamp bound
* Server B's call completes
* Server A's DB transaction is now conflicted and fails
* This triggers a `MultipleRunningTimestampServiceError` in A

The change we discussed briefly was to make `MultipleRunningTimestampServiceError` a subclass of `NotCurrentLeaderException`. We think this should cause the client to failover cleanly to the new leader. However if for some reason there _are_ two running leaders this could worsen the impact, so we should think carefully about the minimum fix.

From a Support perspective this is a P1 issue for the customer due to having hard availability requirements, so it would be good to prioritize this if we can.

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: Fixes #1749 and #1609. Occurrences of MRTSE on Timelock can be explained by the race condition given in that issue description, and in these cases, it's safe to fail over.

**Implementation Description (bullets)**:
* Throw NotCurrentLeaderException instead of MultipleRunningTimestampServicesError
* Drive-by fixing of a few confusing log lines #1609.

**Concerns (what feedback would you like?)**:
We now have a method that declares `throws MRTSE` when in fact it does no such thing. I should probably explain this with a comment, right?

**Where should we start reviewing?**: Check out the ticket description and comments, and convince yourself that all we need to do is in this changeset.

**Priority (whenever / two weeks / yesterday)**: ASAP, this blocks GA of Timelock.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1934)

### CODE REVIEW

File: timestamp-impl/src/main/java/com/palantir/timestamp/AvailableTimestamps.java [hunk 1]
```diff
@@ -30,7 +30,9 @@
     private final PersistentUpperLimit upperLimit;
 
     public AvailableTimestamps(LastReturnedTimestamp lastReturnedTimestamp, PersistentUpperLimit upperLimit) {
-        DebugLogger.logger.info("Creating AvailableTimestamps object on thread {}. This should only happen once.",
+        DebugLogger.logger.info("Creating AvailableTimestamps object on thread {}. This should only happen once."
```
Comment (jeremyk-91) [inline timestamp-impl/src/main/java/com/palantir/timestamp/AvailableTimestamps.java]: nit: I think the `This should only happen once.` here should be removed (probably hanging from copypaste)

File: timestamp-impl/src/main/java/com/palantir/timestamp/PersistentUpperLimit.java [hunk 2]
```diff
@@ -32,7 +32,9 @@
     private volatile long lastIncreasedTime;
 
     public PersistentUpperLimit(TimestampBoundStore tbs, Clock clock, TimestampAllocationFailures allocationFailures) {
-        DebugLogger.logger.info("Creating PersistentUpperLimit object on thread {}. This should only happen once.",
+        DebugLogger.logger.info("Creating PersistentUpperLimit object on thread {}. This should only happen once."
```
Comment (jeremyk-91) [inline timestamp-impl/src/main/java/com/palantir/timestamp/PersistentUpperLimit.java]: nit: I think the `This should only happen once.` here should be removed (probably hanging from copypaste)

**Comment by jeremyk-91** [comment]
(Note: I'm actively tracking this, just somewhat slower than normal as timestamp logic must be handled very carefully - as you say "convince yourself that all we need to do is in this changeset" is the tricky bit with this PR!)
