### PR TITLE
Fix/table mapper pk constraint

### LINKED ISSUE #1551: Long Oracle tables cannot be created as they will collide on primary key constraint names

### PR DESCRIPTION
**Pull request by hsaraogi**
Fixes #1551.

Todo:
Make Postgres use the PrimaryKeyConstraintNames
Test against internal Oracle tests
Testing around primary key constraint names
Throw when Postgres truncates silently - separate PR probably

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1552)

### CODE REVIEW

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java [hunk 1]
```diff
@@ -15,21 +15,15 @@
  */
 package com.palantir.atlasdb.keyvalue.dbkvs.impl.oracle;
 
-import org.apache.commons.lang3.StringUtils;
+import com.palantir.atlasdb.AtlasDbConstants;
 
-import com.palantir.atlasdb.keyvalue.dbkvs.OracleTableNameMapper;
+public final class PrimaryKeyConstraintNames {
```
Comment (jeremyk-91) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java]: The `get()` method seems Oracle-specific - I would think a call to `PrimaryKeyConstraintNames.get(foo)`, which adds the Oracle prefix, should have Oracle somewhere in the name? I know you plan to extend this to Postgres in some way, so feel free to push back on this (or maybe this is some intermediate step along the way)

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameMapper.java [hunk 2]
```diff
@@ -25,9 +25,11 @@
 
 public class OracleTableNameMapper {
     public static final int ORACLE_MAX_TABLE_NAME_LENGTH = 30;
-    public static final int SUFFIX_NUMBER_LENGTH = 6;
+    private static final int PRIMARY_KEY_PREFIX_LENGTH = "pk_".length();
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameMapper.java]: should reuse the constant `ORACLE_PK_CONSTRAINT_PREFIX`.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameMapper.java [hunk 3]
```diff
@@ -63,19 +65,19 @@ private String getTableNumberSuffix(
             String fullTableName,
             String truncatedTableName) {
         int tableSuffixNumber = getNextTableNumber(connectionSupplier, truncatedTableName);
-        if (tableSuffixNumber >= 100_000) {
+        if (tableSuffixNumber >= 10_000) {
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameMapper.java]: this only actually allows 4 digits of tables (_0000 to _9999). This seems like too few, and contradicts the above `SUFFIX_NUMBER_LENGTH`.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java [hunk 4]
```diff
@@ -15,21 +15,15 @@
...
         //Utility class
     }
 
     public static String get(String name) {
-        return truncateToMaxOracleLength("pk_" + name);
-    }
-
-    private static String truncateToMaxOracleLength(String constraintName) {
-        return StringUtils.left(constraintName, OracleTableNameMapper.ORACLE_MAX_TABLE_NAME_LENGTH);
+        return AtlasDbConstants.ORACLE_PK_CONSTRAINT_PREFIX + name;
```
Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java]: Can't this suffer from name length constraint violation issues?

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java (hunk 1 above)
Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/PrimaryKeyConstraintNames.java]: Extended to Postgres and dropped Oracle specific naming.

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleTableInitializer.java [hunk 5]
```diff
@@ -55,7 +55,7 @@ public void createUtilityTables() {
                 String.format(
                         "CREATE TABLE %s ("
                                 + "table_name varchar(2000) NOT NULL,"
-                                + "short_table_name varchar(30) NOT NULL,"
+                                + "short_table_name varchar(27) NOT NULL,"
```
Comment (jeremyk-91) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleTableInitializer.java]: nit: would this make sense as a constant?

Comment (gsheasby) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleTableInitializer.java]: It can be derived from `OracleTableNameMapper.ORACLE_MAX_TABLE_NAME_LENGTH` and `AtlasDbConstants.PRIMARY_KEY_CONSTRAINT_PREFIX`.

Could be put in, but we might want to bind ourselves with a consistency test (assert that these two numbers combine to make 27), so that we don't change them and accidentally do something weird with schemas. Hmm, but probably a bunch of tests will fail anyway, if you change this number?

File: atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ranges/DbKvsGetRanges.java [hunk 6]
```diff
@@ -354,7 +341,7 @@ private String getPrefixedTableName(TableReference tableRef) {
 
     private static final String SIMPLE_ROW_SELECT_ONE_POSTGRES_TEMPLATE =
             " /* SIMPLE_ROW_SELECT_ONE_TEMPLATE_PSQL (%s) */ "
-            + " SELECT /*+ INDEX(t %s) */ "
```
Comment (jboreiko) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ranges/DbKvsGetRanges.java]: Why did we remove a hint here?

Comment (hsaraogi) [inline atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ranges/DbKvsGetRanges.java]: Postgres does not have a concept of index hints. These will be simply comments if present.
