### PR TITLE
Ensure that `NotCurrentLeaderExceptionMapper` can leverage the leader hint.

### LINKED ISSUE #4471: Client recovery after leader switch can fail
Refer to internal PDS-107023

### PR DESCRIPTION
**Pull request by felixdesouza**
**Goals (and why)**:
Fixes #4471. Instead of just randomly redirecting when we *do* know the leader, we use the leader hint that's gathered in the background whilst pinging the leader. When we don't know the leader, we still bias towards fast redirects by picking a random leader vs a 503 which will invoke backoff (we don't want this).

**Implementation Description (bullets)**:
Idea here is that we ping the leader and we know who that leader is every 50 milliseconds. We just need to associate a `HostAndPort`/`URL` when we *do* ping. We also want to encode recency since it's not necessarily the case that the logs are up to date, so we only return the `HostAndPort` if we've successfully pinged the leader within some time frame.

**Testing (What was existing testing like?  What have you done to improve it?)**:
Amended current tests to be aware of host and port etc.

**Concerns (what feedback would you like?)**:
Is remembering for 1 second too much? should it be 500ms? Bear in mind that we ping 20 times a second by default in timelock. I have made it 15 seconds in leader-block mode.

**Where should we start reviewing?**:
* `NotCurrentLeaderExceptionMapper`
* `LeaderElectionService`, `PaxosLeaderElectionService`
* `RetryRedirectTargeter`
* `SingleLeaderPinger`
* `AutobatchingPingableLeaderPingerFactory` if you're interested :P
* `PaxosRuntimeConfiguration` for the cache ttl defaults.

**Priority (whenever / two weeks / yesterday)**:
At some point this week, if not then over the christmas break.

### CODE REVIEW

File: atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java [hunk 1]
```diff
@@ -98,6 +99,11 @@ public Duration leaderPingResponseWait() {
         return Duration.ofMillis(leaderPingResponseWaitMs());
     }
 
+    @Value.Default
+    public HumanReadableDuration leaderAddressCacheTtl() {
+        return HumanReadableDuration.seconds(15);
```
Comment (jkozlowski) [inline atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: Do we need to have this be configurable?

Comment (jkozlowski) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: Also, I don't see this actually is used?

Comment (felixdesouza) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: Perhaps initially, whilst we iron it out. It may not need to go all the way to the config, but for tests it's a bit easier if it's configurable at the lower levels.

Comment (jkozlowski) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: Yeah, it looks like you missed wiring in Leaders#createInstrumentedLocalServices.

File: timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java [hunk 2]
```diff
@@ -68,6 +68,11 @@ default Duration leaderPingResponseWait() {
         return Duration.ofMillis(leaderPingResponseWaitMs());
     }
 
+    @JsonProperty("leader-address-cache-ttl")
+    default Duration leaderAddressCacheTtl() {
```
Comment (jkozlowski) [inline timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java]: Same here, is this used?

File: atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java (hunk 1 above)
Comment (jkozlowski) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: I think it's fine for it to be injectable to the class as a param, so in tests you can turn it off. But then there should just be a default in the default constructor that's used by prod code.

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java [hunk 3]
```diff
@@ -61,32 +65,38 @@
     private final LeaderPinger leaderPinger;
     private final PaxosLearnerNetworkClient learnerClient;
 
-    private final long updatePollingRateInMs;
-    private final long randomWaitBeforeProposingLeadership;
+    private final Duration updatePollingRate;
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: Looks like unrelated refactoring?

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java [hunk 4]
```diff
@@ -126,8 +136,8 @@ private void proposeLeadershipOrWaitForBackoff(LeadershipState currentState) thr
             return;
         }
 
-        if (pingLeader(currentState.greatestLearnedValue()).isSuccessful()) {
-            Thread.sleep(updatePollingRateInMs);
+        if (isSuccessfulPing(pingLeader(currentState.greatestLearnedValue()))) {
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: I think this name is misleading, "isSuccessfulPing suggests that you're just checking some invariant, but in fact you're also caching the result of the lookup. I would say that doing the caching in pingLeader is more appropriate.

File: leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java [hunk 5]
```diff
@@ -42,13 +43,13 @@
 
     private static final Logger log = LoggerFactory.getLogger(SingleLeaderPinger.class);
 
-    private final ConcurrentMap<UUID, PingableLeader> uuidToServiceCache = Maps.newConcurrentMap();
-    private final Map<PingableLeader, ExecutorService> leaderPingExecutors;
+    private final ConcurrentMap<UUID, LeaderPingerContext<PingableLeader>> uuidToServiceCache = Maps.newConcurrentMap();
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java]: Curious why this isn't a cache too? It doesn't look like anything ever expires values from here?

File: leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java [hunk 6]
```diff
@@ -58,44 +59,49 @@ public SingleLeaderPinger(
...
+            return getLeaderPingResult(uuid, pingFuture);
         } catch (InterruptedException ex) {
             Thread.currentThread().interrupt();
             return LeaderPingResults.pingCallFailure(ex);
         }
     }
 
-    private static LeaderPingResult getAndRecordLeaderPingResult(
-            @Nullable Future<Map.Entry<PingableLeader, Boolean>> pingFuture) throws InterruptedException {
+    private static LeaderPingResult getLeaderPingResult(
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java]: Would it work if instead we just had a method to return HostAndPort for a UUID? then we wouldn't need to change the LeaderPingResult at all, and I feel the diff would be much smaller.

File: leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java (hunk 5 above)
Comment (felixdesouza) [reply leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java]: no reason for it not to be, just been like that since whenever really

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java (hunk 4 above)
Comment (felixdesouza) [reply leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: fair, bit difficult to describe since I want to say "is this successful and if it is cache it, but I don't want to know whether or not the cache operation is successful"

File: timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java (hunk 2 above)
Comment (felixdesouza) [reply timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java]: turns out I didn't wire it in, thanks!

File: leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java (hunk 4 above)
Comment (jkozlowski) [reply leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java]: I feel like pingLeader is basically where this should happen, then you don't need a name.

File: atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java (hunk 1 above)
Comment (felixdesouza) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: still need it to be on `LeaderConfig`, I've made it `@JsonIgnore` however, so it's only done through code. I've removed it off of `PaxosRuntimeConfiguration`.

It only needs to be on `LeaderConfig` because timelock creates a leader config and calls `Leaders#createInstrumentedLocalServices` as opposed to using the builder itself. This goes away with my partitioning work, since that path is completely changed. Once I bring that back, I can remove it off of `LeaderConfig`.

File: leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+
+package com.palantir.paxos;
+
+import org.immutables.value.Value;
+
+import com.google.common.net.HostAndPort;
+
+@Value.Immutable
+@Value.Style(allParameters = true)
+public interface LeaderPingerContext<T> {
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java]: Do you need the generic param here?

Comment (jkozlowski) [reply leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java]: This looks like a lot of typing all around the place, maybe we could restructure SingleLeaderPinger somehow, so maybe it just uses HostAndPort everywhere as keys, instead of this thing.

File: timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java [hunk 8]
```diff
@@ -22,36 +22,39 @@
...
+import com.palantir.paxos.LeaderPingerContext;
 
 public class AutobatchingPingableLeaderFactory implements Closeable {
 
     private static final Logger log = LoggerFactory.getLogger(AutobatchingPingableLeaderFactory.class);
 
     private final Collection<? extends Closeable> closeables;
     private final DisruptorAutobatcher<UUID, Optional<ClientAwarePingableLeader>> uuidToRemoteAutobatcher;
-    private final Map<? extends ClientAwarePingableLeader, ExecutorService> executors;
+    private final Map<LeaderPingerContext<BatchPingableLeader>, ExecutorService> executors;
```
Comment (jkozlowski) [inline timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java]: As an aside, all those executor services feel weird, can we not use retrofit and just get non-blocking futures?

Comment (felixdesouza) [reply timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java]: probably, it's a pretty large change, and something I have wanted to do previously, but relatively low priority

File: leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java (hunk 7 above)
Comment (felixdesouza) [reply leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java]: it's not just `SingleLeaderPinger` that uses this. Granted, could probably just make two separate immutable objects that contain `PingableLeader` and `HostAndPort` and `BatchPingableLeader` and `HostAndPort`.

The issue here is that we need to keep the association between the rpc class we just invoked ping on and the the host and port information. It's easier to keep them as a "tuple" as opposed to having another map (in both impls) to associate the rpc class and the address info.

In an ideal world with retrofit, this would be pretty straightforward since we'd just get the information from `Call<T>`. But alas, we are not there.

Comment (jkozlowski) [reply leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java]: I feel like HostAndPort is the unique key though? So maybe the BatchPingableLeader and PingableLeader should be part of the value, not key?

File: leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java (hunk 6 above)
Comment (felixdesouza) [reply leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java]: Not necessarily, to do that, we'd need `pinghLeaderWithUuid` to record the same amount of inforamtion it's doing now, and save it locally, and then expose that it up via a method you method. Similarly for `AutobatchingPingableLeaderFactory`. In a sense, it'd look like ping, except that it would return host and port, this feels pretty weird imo.

Throughout, you need to keep the association, so you can't really get rid of it.

File: leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java (hunk 7 above)
Comment (felixdesouza) [reply leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingerContext.java]: It is unique, but not useful by itself. The `PaxosQuorumChecker` takes in `Map<RPC, Executor>`. If you want to just have a single key (`RPC`), you will need a separate map to keep the association between `HostAndPort` and `RPC` in all the places you will use this.

File: atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java [hunk 9]
```diff
@@ -29,33 +30,52 @@
...
     public ServiceNotAvailableException(String message, HostAndPort serviceHint) {
         super(message);
         this.serviceHint = Optional.of(serviceHint);
+        this.serviceHintUrl = Optional.empty();
     }
 
     public ServiceNotAvailableException(String message, Throwable cause) {
         super(message, cause);
         this.serviceHint = Optional.empty();
+        this.serviceHintUrl = Optional.empty();
```
Comment (felixdesouza) [inline atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java]: don't really like this, it's somewhat awful, it's also difficult to change because `serviceHint` is used/passed in big internal product.

service hint is now bifurcated depending on which one you created the exception with, I'd prefer using `HostAndPort` over this tbh.

Comment (jkozlowski) [reply atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java]: Yeah, not ideal but we need a URL coming into RetryOther right? do you want to manually hardcode the https part there?

Comment (felixdesouza) [reply atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java]: sure, I'd rather pass the `HostAndPort` around and then establish the mapping inside the only place we want it.

Comment (jkozlowski) [reply atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java]: Sure, that's what it was. I didn't realize that large internal product was setting this so we can't just change the exception. In that case your plan sounds solid

File: atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java [hunk 10]
```diff
@@ -98,6 +98,12 @@ public Duration leaderPingResponseWait() {
         return Duration.ofMillis(leaderPingResponseWaitMs());
     }
 
+    @JsonIgnore
+    @Value.Default
+    public Duration leaderAddressCacheTtl() {
```
Comment (jkozlowski) [inline atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: If we could remove this config, it would be nice.

File: leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java [hunk 11]
```diff
@@ -58,44 +59,48 @@ public SingleLeaderPinger(
...
+            LeaderPingerContext<PingableLeader> remote,
+            @Nullable Future<Map.Entry<LeaderPingerContext<PingableLeader>, Boolean>> pingFuture) {
         if (pingFuture == null) {
             return LeaderPingResults.pingTimedOut();
         }
 
         try {
-            boolean isLeader = pingFuture.get().getValue();
-            return LeaderPingResult.fromBooleanResult(isLeader);
+            if (Futures.getDone(pingFuture).getValue()) {
```
Comment (jkozlowski) [inline leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java]: This is great API in MultiplexingCompletionService

File: atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java (hunk 10 above)
Comment (felixdesouza) [reply atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java]: I can remove it when I've reintroduced partitioning, which skips this codepath entirely.

**Comment by felixdesouza** [comment]
> * The value of recency to me at least in terms of avoiding failing loops is to check that the node that we are redirecting to is still alive (rather than that it is the leader).
Being a bit pedantic, I would say being alive should be defined as the `AwaitingLeadershipProxy` for that namespace being alive and running in the background.
