### PR TITLE
Sweep on non-existing table should not print spurious messages

### LINKED ISSUE #1512: SweepCommand silently passes incorrect tables when running with --table option
```
[palantir@il-pg-alpha-770348 <prod>-1.14.0.dirty]$ ./service/bin/<prod> atlasdb sweep var/conf/<prod>.yml --table <keyspace>.<keyspace>__blob_stream_value
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Swept from  to FFFFFFFFFFFFFFFFFFFFFFFF in table <keyspace>.<keysace>__blob_stream_value in 8 ms, examined 0 unique cells, deleted 0 cells.
Finished sweeping <keyspace>.<keyspace>__blob_stream_value, examined 0 unique cells, deleted 0 cells.
```
The table name given does exist in the db (it should be <keyspace>.blob_stream_value) but the sweep cli behaves as if it exists is empty and was swept very quickly.

### PR DESCRIPTION
**Pull request by hsaraogi**
Fixes #1512.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1530)

### CODE REVIEW

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java [hunk 1]
```diff
@@ -98,11 +98,16 @@ public int execute(final AtlasDbServices services) {
...
-            Optional<byte[]> startRow = Optional.of(new byte[0]);
-            if (row != null) {
-                startRow = Optional.of(decodeStartRow(row));
+            TableReference tableToSweep = TableReference.createUnsafe(table);
+            if (services.getKeyValueService().getAllTableNames().contains(tableToSweep)) {
+                Optional<byte[]> startRow = Optional.of(new byte[0]);
+                if (row != null) {
+                    startRow = Optional.of(decodeStartRow(row));
+                }
+                tableToStartRow.put(tableToSweep, startRow);
```
Comment (gsheasby) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java]: Why are we using an optional here if it's _never_ null?

This would be a good opportunity to refactor this class (possibly in a separate PR). Happy to pair on this! :)

File: atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java [hunk 2]
```diff
@@ -98,11 +98,16 @@ public int execute(final AtlasDbServices services) {
...
+            } else {
+                printer.info("The table passed in to sweep {} does not exist", tableToSweep);
```
Comment (gsheasby) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java]: `The table {} passed...` would read better.

Comment (gsheasby) [inline atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java]: Also, it would be better to invert the if (to deal with the error case first) and then return 1, as above.
