### PR TITLE
Fix/unignore ignored sweeper tests

### LINKED ISSUE #308: Enable @Ignore-d Tests in AbstractSweeperTest
This will probably require refactoring the BackgroundSweeper to allow the test to control table priority selection.

### PR DESCRIPTION
**Pull request by gsheasby**
Fixes #308 

Cleaned up tests that were leaving tables around, and now all the sweeper tests pass.

Is this worthy of a release notes entry? It's one more barrier down before we enable sweep by default (the last one being the backup lock stuff).

#NoDocs

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/872)

### CODE REVIEW

**Comment by gsheasby** [comment]
One test is still failing (but only on circle...) - will see if I can fix that one tomorrow. No need to review this yet.

File: atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationTest.java [hunk 1]
```diff
@@ -84,6 +87,9 @@ public void testCreatingMultipleTablesAtOnce() {
             });
         });
 
+        threadPool.shutdown();
+        assertTrue(threadPool.awaitTermination(60, TimeUnit.SECONDS));
```
Comment (gbrova) [inline atlasdb-cassandra-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationTest.java]: Maybe use `Preconditions.checkState`?

`assertTrue` from JUnit suggests we're testing for correctness rather than verifying that some cleanup action has happened.

**Comment by gsheasby** [comment]
It's actually more absurd. All of the tests for `CassandraSweeperTest` are passing, but four tests of `InMemorySweeperTest` are failing (and I can reproduce this locally).

**Comment by jboreiko** [comment]
So anther complication of this ticket is that if it's run as part of internal test suites the same poisoning of the tables can occur (as a heads up).  This may no longer be an issue as we move toward artifacts and no longer rerun the tests internally.

**Comment by gbrova** [comment]
So I looked a little more at those 4 failing tests.  Whether they pass depends on the order in which things are picked out of a Set on [line 243](https://github.com/palantir/atlasdb/blob/fix/unignore-ignored-sweeper-tests/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java#L243) in BackgroundSweeperImpl (!!) 

You can see this behavior by running the tests on Rocks instead of InMemoryKVS and watching them pass, then changing line 243 to return the last element instead of the first one (eg. `return Iterables.get(unsweptTables, unsweptTables.size() - 1)`), then rerunning the tests to watch them fail. 

The fact that all four of these tests depend on this ordering makes them too brittle imo. 
`testBackgroundSweepWritesPriorityTableWithDifferentTime` has a [comment](https://github.com/palantir/atlasdb/blob/fix/unignore-ignored-sweeper-tests/atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweeperTest.java#L364) suggesting it might actually be trying to test the priority order, but I think in that case we should do it at the unit test level.  `testBackgroundSweeperWritesFromProgressToPriority` seems to be failing for the same reason too. 

I'm strongly in favor of rewriting these tests (possibly as unit tests on `BackgroundSweeperImpl`). To unblock us short term, I also wouldn't object to straight-up delete them (considering that (1) they were `@Ignore`d anyway, and (2) I think sweeping tables in priority order is not the most critical thing for us to add testing for)

**Comment by gsheasby** [comment]
That sounds like there might be a bug in BackgroundSweeperImpl which was exposed by the InMemory tests but not the C* tests (which would be a little weird, but w/e). If I get the chance, I'll look into fixing them up today.

**Comment by gbrova** [comment]
That's also possible (though I'm still not a fan of these tests the way they're written) - I'll leave you to figure it out :-)

**Comment by gsheasby** [comment]
Looked into the background sweeper. Does it expect the sweep tables to be swept first because it expected the tables to be picked out in alphabetical order?

**Comment by gsheasby** [comment]
OK, so replacing the Set by a sorted List makes all the tests pass...

Since picking the first element alphabetically is at least predictable, and no less arbitrary than picking the first element from a Set iterable... it still doesn't mean the tests are very good, but they do test things in their own special way. Pushing up my code, let's see what the jury thinks.

File: atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java [hunk 2]
```diff
@@ -84,6 +87,9 @@ public void testCreatingMultipleTablesAtOnce() {
             });
         });
 
+        threadPool.shutdown();
+        assertTrue(threadPool.awaitTermination(60, TimeUnit.SECONDS));
```
Comment (gbrova) [inline atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java]: I said this before but I think GitHub ate my comment: 

Maybe use `Preconditions.checkState`?

`assertTrue` from JUnit suggests we're testing for correctness rather than verifying that some cleanup action has happened.

File: atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweeperTest.java [hunk 3]
```diff
@@ -341,9 +344,8 @@ public void testSweepResultsIncludeMinimumTimestamp() {
     }
 
     @Test
-    @Ignore
     /*
-     * These tests have been ignored pending internal ticket 94009
+     * These tests were ignored pending internal ticket 94009
```
Comment (gbrova) [inline atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweeperTest.java]: Does this PR resolve the internal ticket? 

I'm in favor of deleting this whole comment block.

File: atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweeperTest.java [hunk 4]
```diff
@@ -108,9 +107,13 @@ protected static void setupTables(KeyValueService kvs) {
     }
 
     private static void tearDownTables(KeyValueService kvs) {
+        Set<TableReference> before = kvs.getAllTableNames();
+        System.out.println("All tables before cleanup: " + before);
         kvs.dropTable(TABLE_NAME);
         TransactionTables.deleteTables(kvs);
         Schemas.deleteTablesAndIndexes(SweepSchema.INSTANCE.getLatestSchema(), kvs);
+        Set<TableReference> after = kvs.getAllTableNames();
+        System.out.println("All tables after cleanup: " + after);
```
Comment (gbrova) [inline atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweeperTest.java]: These 4 lines look like debugging code - do we still need them?

**Comment by gbrova** [comment]
I'm not convinced about blindly sorting just to make the tests pass - like you pointed out earlier, the failure might have been exposing a bug. We should try to understand what the expected behavior is / what we're trying to test.

**Comment by gsheasby** [comment]
Having looked at the code and internal documentation, I'm pretty sure that the code I changed is a tiebreaker. Here is the relevant piece of documentation:

> The Background Sweep Job determines which table to sweep by estimating which would be most beneficial based on I/O activity and frequency, considering the following criteria:
> 
> The number of cells written to a table since it was last swept.
> The number of cells that were deleted the last time a table was swept.
> The number of cells that were not deleted the last time a table was swept.
> The amount of time that has passed since the it was last swept.
> 

Based on that, we should probably have tests that say:
- if A and B have never been swept, then we sweep the table with more writes
- if they have the same number of writes, then we can pick whatever we want

**Comment by gsheasby** [comment]
"if A and B have never been swept, then we sweep the table with more writes"

- That's not so clear-cut. It's beyond this PR to figure it out, but at some point we should figure out what background sweeper is _supposed_ to do, and then have tests that reflect that.

Until then, these tests should either be made to pass (by sorting the list) or deleted.

**Comment by gbrova** [comment]
> at some point we should figure out what background sweeper is supposed to do, and then have tests that reflect that.

Cool, sounds like we're on the same page. Merge away!

File: atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java [hunk 5]
```diff
@@ -58,7 +60,7 @@ public void setUp() {
                 CassandraKeyValueServiceConfigManager.createSimpleManager(quickTimeoutConfig), CassandraTestSuite.LEADER_CONFIG);
 
         ImmutableCassandraKeyValueServiceConfig slowTimeoutConfig = CassandraTestSuite.CASSANDRA_KVS_CONFIG
-                .withSchemaMutationTimeoutMillis(60 * 1000);
+                .withSchemaMutationTimeoutMillis(6 * 1000);
```
Comment (jboreiko) [inline atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java]: Is this related to this PR?

Comment (gsheasby) [inline atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java]: Yes - so, originally, the test didn't have an `awaitTermination` check, so:
a) it didn't actually test what was intended
b) the threads continued after the test was done, causing tables to bleed into other tests

I think that bumping this timeout down was necessary to get this test running in a reasonable amount of time, since other threads seemed to be waiting for this long before trying again to get the schemaMutationLock.
