### PR TITLE
bypass a schema lock on startup if table exists; fixes #989

### LINKED ISSUE #989: clean-cass-locks-state doesn't work
Apparently the CassandraKeyValueService.create() codepath has a createTable call which attempts to grab the schema lock so it fails.

### PR DESCRIPTION
**Pull request by clockfort**
In general this would have been automatically prevented if we had a core internal atlas schema, and the metadata / timestamp / sweep / ??? tables lived in that.

This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/991)

### CODE REVIEW

**Comment by gsheasby** [comment]
Removing the +1 label while we play Flicker or No Flicker.

**Comment by gsheasby** [comment]
This looks like an actual failure - @clockfort could you look into the ETE tests, please?

**Comment by tpetracca** [comment]
I don't think this really solves the issue.  We'll route through the ValidatingQueryRewritringKVS but all that's doing is a sanity check on the table name.  I think what we want to do here is add an abstract KeyValueService getTables that returns currently created tables in the DB.  Then ValidatingQueryRewritingKVS.createTable wouldn't create a table if it exists in getTables

**Comment by clockfort** [comment]
did a different thing. As a bonus this actually reduces number of schema locks we take out in other cases than the one this ticket was originally about.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 1]
```diff
@@ -1424,23 +1424,62 @@ public void createTable(final TableReference tableRef, final byte[] tableMetadat
...
+        Map<TableReference, byte[]> tablesToActuallyCreate = filterOutExistingTables(tableNamesToTableMetadata);
+        Map<TableReference, byte[]> tablesToUpdateMetadataFor = filterOutNoOpMetadataChanges(tableNamesToTableMetadata);
+
+        boolean onlyMetadataChangesAreForNewTables =
+                tablesToUpdateMetadataFor.keySet().equals(tablesToActuallyCreate.keySet());
+        boolean putMetadataWillNeedASchemaChange = !onlyMetadataChangesAreForNewTables;
+
+        if (!tablesToActuallyCreate.isEmpty()) {
+            schemaMutationLock.runWithLock(() -> {
+                createTablesInternal(tableNamesToTableMetadata);
```
Comment (tpetracca) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: should be `tablesToActuallyCreate`

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 2]
```diff
@@ -1449,22 +1488,41 @@ private void createTablesInternal(final Map<TableReference, byte[]> tableNamesTo
                     TableReference tableRefLowerCased = TableReference
                             .createUnsafe(table.getQualifiedName().toLowerCase());
                     if (!existingTablesLowerCased.contains(tableRefLowerCased)) {
-                        client.system_add_column_family(getCfForTable(table, metadata));
+                        filteredTables.put(table, metadata);
                     } else {
                         log.debug("Ignored call to create table ({}) that already existed (case insensitive).", table);
```
Comment (tpetracca) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: Maybe modify this to say "Filtering out existing table {{}) yadda yadda"? Could potentially have another consumer that isn't createTables in the future?

Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: 👍

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java (hunk 1 above)
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: 👍

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 3]
```diff
@@ -1424,23 +1424,76 @@ public void createTable(final TableReference tableRef, final byte[] tableMetadat
...
+                // completely new table, not an update
+                if (matchingTables.isEmpty()) {
+                    tableMetadataUpdates.put(tableReference, newMetadata);
                 }
 
+                // table already exists but has different metadata, so we should perform an update
+                if (!matchingTables.isEmpty() && !Arrays.equals(
+                        existingTableMetadata.get(Iterables.getOnlyElement(matchingTables)), newMetadata)) {
+                    tableMetadataUpdates.put(tableReference, newMetadata);
+                }
```
Comment (gsheasby) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: `if (!matchingTables.isEmpty() && Arrays.equals(thatThing) {`

then we will skip the table without logging that we're skipping it. Is this desired?

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java [hunk 4]
```diff
@@ -1424,23 +1424,76 @@ public void createTable(final TableReference tableRef, final byte[] tableMetadat
...
+
+        return tableMetadataUpdates;
+    }
+
+    private Map<TableReference, byte[]> filterOutExistingTables(
+            final Map<TableReference, byte[]> tableNamesToTableMetadata) {
+        Map<TableReference, byte[]> filteredTables = Maps.newHashMap();
+        try {
+            clientPool.runWithRetry((FunctionCheckedException<Client, Void, Exception>) client -> {
+                Set<TableReference> existingTablesLowerCased = getExistingTablesLowerCased(client);
```
Comment (gsheasby) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: I think we now only need to wrap this line in the clientPool.runWithRetry.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java (hunk 3 above)
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: Sure, we can log something here along the lines of "table exists, but had the same metadata already, so we don't need to do anything"

File: atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java [hunk 5]
```diff
@@ -148,4 +148,30 @@ public void testCreateTableCanRestoreLostMetadata() {
...
+        byte[] initialMetadata = new TableDefinition() {{
+            rowName();
+            rowComponent("blob", ValueType.BLOB);
+            columns();
+            column("bar", "b", ValueType.BLOB);
+            conflictHandler(ConflictHandler.IGNORE_ALL);
+            sweepStrategy(TableMetadataPersistence.SweepStrategy.NOTHING);
+        }}.toTableMetadata().persistToBytes();
+
+        kvs.createTable(caseSensitiveTable, initialMetadata);
```
Comment (clockfort) [inline atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java]: Done.

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java (hunk 4 above)
Comment (clockfort) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java]: Done

**Comment by gsheasby** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/991#-:-KTMA8GhvhK25hG0ti6h:bnfp4nl)*

**Comment by gsheasby** [comment]
Looks good - want to merge in develop and add a release note first.

**Comment by gsheasby** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/991#-:-KTMD6uKSXNeq5hqP8o4:bnfp4nl)*

**Comment by gsheasby** [comment]
I think we need to merge develop into the branch again (or maybe rebase) - a big revert just went in, and now this branch has over 100 commits according to circle.

**Comment by gsheasby** [comment]
https://circleci.com/gh/palantir/atlasdb/3350

**Comment by gsheasby** [comment]
"remove unused KVS method as a ritual sacrfice to the file-length checker"

- we also plan to pull out some of the table creation logic to make it more testable. @jboreiko for SA.
