### PR TITLE
Retry on Distinct Servers; fixes #885

### LINKED ISSUE #885: Randomly redirecting a query can redirect back to the same host
Transactions retry total of 6 times and 3 times per host.
If random redirection directs to the same host, transactions fail without actually retrying multiple nodes. (CassandraClientPool#runWithRetryOnHost).

### PR DESCRIPTION
**Pull request by jeremyk-91**
This addresses #885 by adding a mechanism for filtering of which servers should be considered when doing runWithRetryOnHost(). We then keep track of which servers we've tried on the current run, and where feasible don't try them again after hitting a retriable exception. If we run out of servers (e.g. a 3-node cluster with all nodes failing in this sense) then we select randomly from any server in the pool once this happens.

I've also added a few unit tests around this predicate matching and the retry logic.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1139)

### CODE REVIEW

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 1]
```diff
@@ -264,13 +267,24 @@ private boolean isHostHealthy(InetSocketAddress host) {
...
+    }
+
+    @VisibleForTesting
+    CassandraClientPoolingContainer getRandomGoodHostForPredicate(Predicate<InetSocketAddress> predicate) {
         Map<InetSocketAddress, CassandraClientPoolingContainer> pools = currentPools;
 
-        Set<InetSocketAddress> livingHosts = Sets.difference(pools.keySet(), blacklistedHosts.keySet());
+        Set<InetSocketAddress> filteredHosts = pools.keySet().stream().filter(predicate).collect(Collectors.toSet());
+        if (filteredHosts.isEmpty()) {
+            log.error("No hosts match the provided predicate. We will ignore said predicate.");
```
Comment (SerialVelocity) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: This seems super weird. We should throw or return no container and do this logic one level up

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 2]
```diff
@@ -264,13 +267,24 @@ private boolean isHostHealthy(InetSocketAddress host) {
...
     private CassandraClientPoolingContainer getRandomGoodHost() {
+        return getRandomGoodHostForPredicate(address -> true);
+    }
+
+    @VisibleForTesting
+    CassandraClientPoolingContainer getRandomGoodHostForPredicate(Predicate<InetSocketAddress> predicate) {
         Map<InetSocketAddress, CassandraClientPoolingContainer> pools = currentPools;
 
-        Set<InetSocketAddress> livingHosts = Sets.difference(pools.keySet(), blacklistedHosts.keySet());
+        Set<InetSocketAddress> filteredHosts = pools.keySet().stream().filter(predicate).collect(Collectors.toSet());
```
Comment (jeremyk-91) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: OK, done.

**Comment by clockfort** [comment]
There is a slightly improvement that you could do, if your stuff was passed in a list of hosts from CassandraClientPool#getRandomHostForKey(byte[]) that it would prefer to do retries on before falling back on truly random nodes.

(the gist being "if I am going to retry a query, I would better-like to retry it on a node that actually owns that data or a copy of it rather than a fail onto a Cassandra node that has no idea what I'm talking about and is going to have to do more internode communication to figure it out")

That said, your code seems fine and is an improvement as-is and you don't have to do this.

**Comment by jeremyk-91** [comment]
@clockfort I've opened a separate issue for the host hinting suggestion; happy to take ownership of that as well. Thanks!

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 3]
```diff
@@ -463,13 +485,22 @@ private void refreshTokenRanges() {
 
             if (blacklistedHosts.containsKey(specifiedHost) || hostPool == null || shouldRetryOnDifferentHost) {
                 log.warn("Randomly redirected a query intended for host {}.", specifiedHost);
-                hostPool = getRandomGoodHost();
+                Optional<CassandraClientPoolingContainer> hostPoolCandidate
+                        = getRandomGoodHostForPredicate(address -> !triedHosts.contains(address));
+                if (hostPoolCandidate.isPresent()) {
```
Comment (SerialVelocity) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: `hostPool = hostPoolCandidate.or(this::getRandomGoodHost);`

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 4]
```diff
@@ -264,16 +268,33 @@ private boolean isHostHealthy(InetSocketAddress host) {
     }
 
     private CassandraClientPoolingContainer getRandomGoodHost() {
+        // Note that this is safe (unless there are 0 hosts in the pool, in which case IllegalStateException is not
+        // unreasonable)
+        return getRandomGoodHostForPredicate(address -> true).get();
```
Comment (SerialVelocity) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: I think having `.orThrow(...)` would be slightly better where we return something saying there are no hosts.

Comment (jeremyk-91) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: Changed method name (and removed comments).

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java (hunk 3 above)
Comment (jeremyk-91) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: Thanks, wasn't aware of this!

File: atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java [hunk 5]
```diff
@@ -264,16 +268,32 @@ private boolean isHostHealthy(InetSocketAddress host) {
...
+            log.error("There are no known live hosts in the connection pool matching the predicate. We're choosing"
                     + " one at random in a last-ditch attempt at forward progress.");
-            livingHosts = pools.keySet();
+            livingHosts = filteredHosts;
         }
 
-        return pools.get(getRandomHostByActiveConnections(Maps.filterKeys(currentPools, livingHosts::contains)));
+        CassandraClientPoolingContainer poolingContainer
+                = pools.get(getRandomHostByActiveConnections(Maps.filterKeys(currentPools, livingHosts::contains)));
+        return Optional.of(poolingContainer);
```
Comment (SerialVelocity) [inline atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java]: pools is a concurrent container. `ofNullable` would probably be better.
