### PR TITLE
Fix/retry lock request after interrupt

### LINKED ISSUE #2057: Lock Service should 503, not 500 when leadership is lost
Currently, if leadership is lost, we close the lock service, which results in an `InterruptedException` being thrown for all blocked threads. This translates to a 500 error to the client.

We should detect this scenario and return a 503 so that clients can fail over to the new leader.

### PR DESCRIPTION
**Pull request by hsaraogi**
**Goals (and why)**: Fixes #2057. This maps a 500 from the RemotelockService.lock to a retryable 503 exception.

**Implementation Description (bullets)**: AtlasDbErrorDecoder will map 500 from lock requests to 503. Tests to show a 500 is received and that it is retried.

**Concerns (what feedback would you like?)**: 
The use of the methodKey is a bit funky, is that fine?

**Where should we start reviewing?**: AtlasDbErrorDecoder

**Priority (whenever / two weeks / yesterday)**: this week

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2098)

### CODE REVIEW

File: timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java [hunk 1]
```diff
@@ -64,6 +78,50 @@ public void bringAllNodesOnline() {
     }
 
     @Test
+    public void lockRequestThrows500DueToLeaderElection() throws InterruptedException {
+        CLUSTER.lock(CLIENT_1, BLOCKING_LOCK_REQUEST);
+
+        TestableTimelockServer leader = CLUSTER.currentLeader();
+        Executors.newSingleThreadExecutor().submit(() -> {
+            assertThatThrownBy(() -> leader.lock(CLIENT_2, BLOCKING_LOCK_REQUEST))
+                    .isInstanceOf(InterruptedException.class);
```
Comment (nziebart) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: does this actually result in an `InterruptedException` locally?
also note that if this assertion fails, it won't fail the test, because it's running on another thread

File: timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java [hunk 2]
```diff
@@ -75,7 +75,8 @@ private static void registerResources(
                         configuration.slowLockLogTriggerMillis())));
 
         environment.getObjectMapper().registerModule(new Jdk8Module());
-        environment.jersey().register(HttpRemotingJerseyFeature.DEFAULT);
+        environment.jersey().register(
+                HttpRemotingJerseyFeature.with(HttpRemotingJerseyFeature.StacktracePropagation.PROPAGATE));
```
Comment (nziebart) [inline timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java]: remove this change

File: atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbErrorDecoder.java [hunk 3]
```diff
@@ -27,6 +27,8 @@
 import feign.codec.ErrorDecoder;
 
 public class AtlasDbErrorDecoder implements ErrorDecoder {
+    private static final String LOCK_METHOD_KEY = "RemoteLockService#lock(String,LockRequest)";
```
Comment (nziebart) [inline atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbErrorDecoder.java]: Hmm, this is a little fragile. Also not sure that we want to retry on all 500 errors (at least in the scope of this PR).

It may be better to catch `InterruptedException` server-side and map it to a 503. I would not be opposed to having a check in `AwaitingLeadershipProxy` that checks if the delegate throws interrupted exception, and if we are no longer the leader propagates it as `NotCurrentLeaderException`

Comment (nziebart) [inline atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbErrorDecoder.java]: this would also make testing easier as we can just write a unit test on `AwaitingLeadershipProxy` given that we don't currently have a good mechanism for forcing a node to step down as leader (https://github.com/palantir/atlasdb/issues/2100)

File: leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java [hunk 4]
```diff
@@ -178,14 +178,21 @@ protected Object handleInvocation(Object proxy, Method method, Object[] args) th
...
             return method.invoke(delegate, args);
         } catch (InvocationTargetException e) {
-            if (e.getCause() instanceof ServiceNotAvailableException
-                    || e.getCause() instanceof NotCurrentLeaderException) {
+            if (e.getTargetException() instanceof ServiceNotAvailableException
+                    || e.getTargetException() instanceof NotCurrentLeaderException) {
                 markAsNotLeading(leadershipToken, e.getCause());
             }
-            throw e.getCause();
+            if (e.getTargetException() instanceof InterruptedException && !(checkIfLeading(leadershipToken))) {
```
Comment (nziebart) [inline leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java]: might be worth a quick comment here explaining that this is for the lock service

File: leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java [hunk 5]
```diff
@@ -178,14 +178,21 @@ protected Object handleInvocation(Object proxy, Method method, Object[] args) th
...
+                throw notCurrentLeaderException("received an interrupt due to leader election.", e.getTargetException());
+            }
+            throw e.getTargetException();
         }
     }
 
+    private boolean checkIfLeading(LeadershipToken leadershipToken) {
+        return leaderElectionService.isStillLeading(leadershipToken) == StillLeadingStatus.LEADING;
```
Comment (nziebart) [inline leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java]: I think this will result in a network call - we could alternatively just quickly check if the given token is equal to the current `leadershipTokenRef` (since it gets nulled out when we lose leadership)

File: leader-election-impl/src/test/java/com/palantir/leader/proxy/TestRunnableWhichThrows.java [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.palantir.leader.proxy;
+
+public interface TestRunnableWhichThrows {
```
Comment (nziebart) [inline leader-election-impl/src/test/java/com/palantir/leader/proxy/TestRunnableWhichThrows.java]: this can be replaced by `Callable` which allows exceptions

File: timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java [hunk 7]
```diff
@@ -64,6 +79,29 @@ public void bringAllNodesOnline() {
     }
 
     @Test
+    public void blockedLockRequestThrows503OnLeaderElection() throws InterruptedException {
+        LockRefreshToken lock = CLUSTER.lock(CLIENT_1, BLOCKING_LOCK_REQUEST);
+        assertThat(lock).isNotNull();
+
+        TestableTimelockServer leader = CLUSTER.currentLeader();
+        Future<LockRefreshToken> lock2 = Executors.newSingleThreadExecutor()
```
Comment (nziebart) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: nit: use `CompletableFuture.supplyAsync`

File: timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java [hunk 8]
```diff
@@ -64,6 +79,29 @@ public void bringAllNodesOnline() {
...
+        Uninterruptibles.sleepUninterruptibly(5, TimeUnit.SECONDS);
+        CLUSTER.nonLeaders().forEach(TestableTimelockServer::kill);
+        // Lock on leader so that AwaitingLeadershipProxy notices leadership loss.
+        assertThatThrownBy(() -> leader.lock(CLIENT_3, BLOCKING_LOCK_REQUEST))
+                .satisfies(ExceptionMatchers::isRetryableExceptionWhereLeaderCannotBeFound);
+        try {
+            lock2.get();
+            fail(String.format("Lock client %s should have thrown an execution exception as leader is not available",
+                    CLIENT_2));
+        } catch (ExecutionException e) {
```
Comment (nziebart) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: nit: use `assertThatThrownBy(() -> lock2.get()).getCause().satisfies(...)` (not sure if that exact syntax works)

File: timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java [hunk 9]
```diff
@@ -64,6 +79,29 @@ public void bringAllNodesOnline() {
     }
 
     @Test
+    public void blockedLockRequestThrows503OnLeaderElection() throws InterruptedException {
```
Comment (nziebart) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: any idea how long this takes to run? i'm worried it might be a little flaky given how hard it was for us to repro this.

File: leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java (hunk 5 above)
Comment (hsaraogi) [inline leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java]: This will mean the proxy will not be aware until a second call received a 503 and makes the leadershipToken as null. The leadership token is changed when someone `gainsLeadership` or a request receives ServiceUnavailable/NCLE. So, if we check the `leadershipTokenRef ` all lock requests will 500 until another request hits and 503. :(

Comment (nziebart) [inline leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java]: The lock service is actually not closed until the `leadershipTokenRef` has been nulled out (in `markAsNotLeading`)

File: timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java (hunk 9 above)
Comment (nziebart) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: (if we think this is flaky i'd be fine with removing until https://github.com/palantir/atlasdb/issues/2100)

Comment (hsaraogi) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: The build time has not increased significantly. Ran 6 builds, 2 of which flaked but in the CassandraIntegrationTests(old known flake).

Comment (hsaraogi) [inline timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java]: We can ignore it if any flakes are observed going further.

File: leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java [hunk 10]
```diff
@@ -67,4 +81,103 @@ public void shouldAllowObjectMethodsWhenNotLeading() throws Exception {
...
+        assertThatThrownBy(proxy::call)
+                .isInstanceOf(InterruptedException.class)
+                .hasMessage(TEST_MESSAGE);
+
+        assertThat(catchThrowable(callToProxy::get).getCause())
+                .isInstanceOf(InterruptedException.class)
+                .hasMessage(TEST_MESSAGE);
+    }
+
+    private Future makeARequestThatThrowsAndCauseLeadershipLoss(Exception ex) throws InterruptedException {
```
Comment (nziebart) [inline leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java]: I think it would be more readable to break this into two methods. e.g.,
```
Future blockingRequest = ...
loseLeadership();

assertThat(blockingRequest.get()).isInstanceOf(...)
```

File: leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java [hunk 11]
```diff
@@ -67,4 +81,103 @@ public void shouldAllowObjectMethodsWhenNotLeading() throws Exception {
...
+        return callToProxy;
+    }
+
+    private Callable getCallableProxy(
+            Exception ex,
+            LeaderElectionService.StillLeadingStatus status1,
+            LeaderElectionService.StillLeadingStatus status2) throws InterruptedException {
+
+        Callable runnableWithInterruptedException = () -> {
+            Uninterruptibles.sleepUninterruptibly(10, TimeUnit.SECONDS);
```
Comment (nziebart) [inline leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java]: One strategy that might be useful here is using a `CountdownLatch`. You can do:
```
CountdownLatch latch = new CountdownLatch(1);
Callable callable = () -> {
    latch.await();
    throw ...;
}
```

this could maybe be used as:
```
Callable proxy = proxyFor(() -> {
    latch.await();
    throw ...;
}
Future blockingCall = executor.submit(() -> proxy.call());

loseLeadership();
latch.countdown();

assertThatThrownBy(blockingCall.get()).isInstanceOf(...);
```
