### PR TITLE
Fix/remove create unsafe from gen code

### LINKED ISSUE #1172: Generated code should not use TableReference.createUnsafe
We deprecated this method in #1121, but the code generation still uses it, which will generate warnings for clients that use Atlas schemas.

We should follow our own advice and use createFromFullyQualifiedName instead.

### PR DESCRIPTION
**Pull request by hsaraogi**
This closes #1172.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1194)

### CODE REVIEW

File: atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java [hunk 1]
```diff
@@ -62,14 +62,14 @@ public static void createTables(KeyValueService kvs, Map<TableReference, TableDe
...
+    public static String getTableReferenceString(String tableName, Namespace namespace) {
         Preconditions.checkArgument(isTableNameValid(tableName), "%s is not a valid table name", tableName);
         String namespaceName = namespace.getName();
         // Hacks for schemas that were created before namespaces were created.
         if (namespace.isEmptyNamespace() || namespaceName.equals("met")) {
-            return tableName;
+            return "TableReference.createWithEmptyNamespace(\"" + tableName + "\")";
         } else {
-            return namespace.getName() + "." + tableName;
+            return "TableReference.createFromFullyQualifiedName(\"" + namespace.getName() + "." + tableName + "\")";
```
Comment (SerialVelocity) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java]: Shouldn't this just be `.create(namespace.getName(), tableName)`?

Comment (SerialVelocity) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java]: Or an equivalent thing

Comment (hsaraogi) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java]: This will look like `TableReference.create(Namespace.create(\" + namespace.getName()+ "\", \"" + tableName+ ")"` .. dont like this is better over `createFromFullyQualifiedName` and  as there is no change in behavior.

Comment (gsheasby) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java]: This is a public method that we're changing here, and the change will be breaking for anyone who used `getFullTableName`. Did you check that this method is unused?

File: atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemasTest.java [hunk 2]
```diff
@@ -53,23 +53,23 @@ public void setup() {
     @Test
     public void testGetFullTableName() {
```
Comment (gsheasby) [inline atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemasTest.java]: Tests need to be renamed, as the tested code no longer gets the full table name.

File: atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/cas/generated/CheckAndSetTable.java [hunk 3]
```diff
@@ -16,6 +16,7 @@
 
 import javax.annotation.Generated;
 
+
```
Comment (gsheasby) [inline atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/cas/generated/CheckAndSetTable.java]: Random blank line shouldn't be there...

Comment (SerialVelocity) [inline atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/cas/generated/CheckAndSetTable.java]: This is what I found weird. It's generated code though...

Comment (hsaraogi) [inline atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/cas/generated/CheckAndSetTable.java]: Regenerated and can confirm that the newline is not stray.

File: atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableRenderer.java [hunk 4]
```diff
@@ -199,7 +199,6 @@ protected void run() {
                 line("package ", packageName, ";");
                 line();
                 importRenderer.renderImports();
-                line();
```
Comment (SerialVelocity) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableRenderer.java]: I think removing the line() in renderImports is better since I would expect this to only have one line (when you call line())

Comment (SerialVelocity) [inline atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableRenderer.java]: It will also fix the issue where there's an extra line when there are no `javax` imports
