### PR TITLE
Remove stack traces from large logging warnings

### LINKED ISSUE #1416: Reduce log level of large cassandra gets
We currently log at ERROR when a user performs an operation that triggers a large get in Cassandra, and there isn't really anything the user can do in this situation and it leads to spammy logs. I think this should ideally be logged at WARN. An example log line looks like:

```
ERROR [2017-01-05 19:34:53,067] com.palantir.atlasdb.transaction.impl.SnapshotTransaction: A single get had a lot of bytes: 154355299 for table myKeyspace.myTable. The number of results was 121. The first 10 results were
[Cell{rowName=xxx, columnName=xxx, no TTL}=Value [contents=xxx, contentsLength=xxx, timestamp=xxx], 
Cell{rowName=xxx, columnName=xxx, no TTL}=Value [contents=xxx, contentsLength=xxx, timestamp=xxx], 
...
...
Cell{rowName=xxx, columnName=xxx, no TTL}=Value [contents=xxx, contentsLength=xxx, timestamp=xxx]
This can potentially cause out-of-memory errors. 
```

We should also make sure we tag these lines with whatever logback tagging we decide on in #867 because this contains sensitive data. We may want to entirely remove the `contents` argument from the log line as this isn't likely to be helpful and just creates a way data can leak.

### PR DESCRIPTION
**Pull request by rhero**
Moved scary stack traces from large put/get warnings to debug, get rid of error logs here.

Fixes #1416. 

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1590)

### CODE REVIEW

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java [hunk 1]
```diff
@@ -949,17 +949,14 @@ private int estimateSize(List<RowResult<Value>> rangeRows) {
...
-                            + "The first 10 results were {}. This can potentially cause out-of-memory errors.",
-                    bytes, tableRef.getQualifiedName(), rawResults.size(), Iterables.limit(rawResults.entrySet(), 10),
-                    new RuntimeException("This exception and stack trace are provided for debugging purposes."));
-        } else if (bytes > TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES && log.isWarnEnabled()) {
+        if (bytes > TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES && log.isWarnEnabled()) {
             log.warn("A single get had quite a few bytes: {} for table {}. The number of results was {}. "
-                            + "The first 10 results were {}.",
-                    bytes, tableRef.getQualifiedName(), rawResults.size(), Iterables.limit(rawResults.entrySet(), 10),
-                    new RuntimeException("This exception and stack trace are provided for debugging purposes."));
+                    + " Enable debug logging for more information.",
```
Comment (jeremyk-91) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java]: note: We'll have two spaces between the sentences this way - I'd suggest removing the space at the beginning of this line if only 1 was intended. I'm fine either way.

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java [hunk 2]
```diff
@@ -1125,14 +1122,12 @@ private void putWritesAndLogIfTooLarge(Map<Cell, byte[]> values, SortedMap<Cell,
...
-                    log.warn("A single transaction has put quite a few bytes: {}", newVal, new RuntimeException(
-                            "This exception and stack trace are provided for debugging purposes."));
-                }
-                if (newVal >= TransactionConstants.ERROR_LEVEL_FOR_QUEUED_BYTES
-                        && newVal - toAdd < TransactionConstants.ERROR_LEVEL_FOR_QUEUED_BYTES) {
-                    log.warn("A single transaction has put too many bytes: {}. This can potentially cause"
-                            + " out-of-memory errors.", newVal, new RuntimeException(
-                            "This exception and stack trace are provided for debugging purposes."));
+                    log.warn("A single transaction has put quite a few bytes: {}. "
+                            + " Enable debug logging for more information", newVal);
```
Comment (jeremyk-91) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java]: As above, note that we'll have 2 spaces between sentences (while the current message has 1).

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java (hunk 1 above)
Comment (rhero) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java]: Yeah I was copying line 992, but I hate the two space after a sentence convention (psst, I think @jboreiko is a fanboy). Going to remove them.

File: atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java [hunk 3]
```diff
@@ -949,17 +949,14 @@ private int estimateSize(List<RowResult<Value>> rangeRows) {
...
             bytes += e.getValue().getContents().length + Cells.getApproxSizeOfCell(e.getKey());
         }
-        if (bytes > TransactionConstants.ERROR_LEVEL_FOR_QUEUED_BYTES
-                && !AtlasDbConstants.TABLES_KNOWN_TO_BE_POORLY_DESIGNED.contains(tableRef)) {
-            log.error("A single get had a lot of bytes: {} for table {}. The number of results was {}. "
-                            + "The first 10 results were {}. This can potentially cause out-of-memory errors.",
-                    bytes, tableRef.getQualifiedName(), rawResults.size(), Iterables.limit(rawResults.entrySet(), 10),
-                    new RuntimeException("This exception and stack trace are provided for debugging purposes."));
-        } else if (bytes > TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES && log.isWarnEnabled()) {
+        if (bytes > TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES && log.isWarnEnabled()) {
```
Comment (tpetracca) [inline atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java]: what the if enabled here? the log line itself doesn't seem to be doing work.
