### PR TITLE
Fix/guard ql statements

### LINKED ISSUE #670: Properly guard SQL statement caches with the cachelock
Follow up to discussion on #649.  Would be as simple as making both cachedUnregistered / cachedKeyed private and put them behind locking getters and setters.

### PR DESCRIPTION
**Pull request by hsaraogi**
Fixes #670.

Make the maps for the caches private to enforce safety if subclassing.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/727)

### CODE REVIEW

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java [hunk 1]
```diff
@@ -367,4 +364,28 @@ public String getKey() {
...
+        synchronized (cacheLock) {
+            return cachedKeyed;
+        }
+    }
+
+    protected static void setCachedKeyed(ImmutableMap<String, FinalSQLString> cachedKeyed) {
+        synchronized (cacheLock) {
+            SQLString.cachedKeyed = cachedKeyed;
+        }
+    }
```
Comment (schlosna) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java]: Where are the getters/setters callers? Are these fields still accessed directly?

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java [hunk 2]
```diff
@@ -367,4 +364,28 @@ public String getKey() {
     public static RegisteredSQLString getRegisteredQueryByKey(FinalSQLString key) {
          return new RegisteredSQLString(key.delegate);
     }
+
+    protected static ImmutableMap<String, FinalSQLString> getCachedUnregistered() {
+        synchronized (cacheLock) {
```
Comment (schlosna) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java]: The GuardedBy comments indicate that we should be able to do a volatile read without locking, is that no longer the case?

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java [hunk 3]
```diff
@@ -367,4 +364,28 @@ public String getKey() {
...
+    }
+
+    protected static void setCachedUnregistered(ImmutableMap<String, FinalSQLString> cachedUnregistered) {
+        synchronized (cacheLock) {
+            SQLString.cachedUnregistered = cachedUnregistered;
+        }
+    }
+
+    protected static ImmutableMap<String, FinalSQLString> getCachedKeyed() {
+        synchronized (cacheLock) {
```
Comment (schlosna) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java]: The GuardedBy comments indicate that we should be able to do a volatile read without locking, is that no longer the case?

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java (hunk 2 above)
Comment (hsaraogi) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java]: I agree, we will get valid values without locking here.

File: commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java (hunk 1 above)
Comment (hsaraogi) [inline commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java]: The getter/setter are not being used now. They have been added so that the caches are accessible to subclasses in the future.

**Comment by jboreiko** [comment]
To be clear this was developed to resolve an issue tracked internally QA-95698.  It's important that we view these changes in the context of the above ticket.  Pinging @safreiberg as I'm not immediately sure these have the correct structure for this use case and we should remove the unused methods.
